/*
2025-08
ESP32 Whatsapp
avec le freebroker HiveMQ + BT keyboard +

Old
Tools > Boards :           D1Mini : Connecter avec "LOLIN(WEMOS) D1 R2 & mini", baud 115200
                           ESP32 : ESP32 Dev Module
Tools > Partition Scheme : For ESP32, try the "Huge App" partition (1.9MB app space, 320KB SPIFFS).

Faire le tri des boards :
  Wemos/Lolin do sell ESP32-based boards in similar form factors, but they ship under different names and live under the ESP32 boards
  package (Espressif Systems):
  - "LOLIN D32" — ESP32 (classic)
  - "LOLIN D32 Pro" — ESP32 with PSRAM + SD slot
  - "LOLIN S2 Mini" — ESP32-S2 (mini form factor, often confused with the D1 mini)
  - "LOLIN S3 Mini" / "LOLIN C3 Mini" — ESP32-S3 / -C3


2026-05

ArduinoIDE :               2.3.8_Linux_64bit.AppImage
Tools > Boards  :          ESP32 >> ESP32 Dev Module,
                           /dev/ttyUSB0, Baud 115200
Tools > Partition Scheme : "Huge APP (3MB No OTA / 1MB SPIFFS)"
COMPILE: OK
LINK   : OK
UPLOAD : OK
RUN    : ?

Sa console web : https://console.hivemq.cloud/clusters/8f76c91610f343c2b6795974c58861c7/web-g_mqttClient

TODO
- renommer "lineCount", TextLine... en ConvoItem
- gérer les accents entrants
- tester perte de connection wifi (refaire boucle de co ?)
- tester perte MQTT et affichage msg
- check NTP
- couleur et affichage du pseudo remote (pour chan room multi )
- gerer un delta de temps contre le réaffichage du timestamp
- utiliser WiFiManager (cf mistral) pour configurer le wifi - https://github.com/tzapu/WiFiManager, sinon déplacer la connection dans loop
- commandes pour shutdown la nuit

- taille program:
  Remove Debug Code: Strip out all Serial.print() and debug code for production.
  Use PROGMEM: Store large constants (e.g., strings, images) in PROGMEM.
    pour la font ? ou le logo ? ou certificat ?
  Disable Unused Features: In your library includes, disable features you don’t use (e.g., Adafruit_GFX has options for this).

- indicator
BTKB bonded
BTKB capslock
WIFI ok
MQ ok
Friend present
*/


//#define PAC_ON_D1MINI
#define PAC_ON_ESP32


// ================================================================================
// Librairies
// ================================================================================

// Provided by Arduino IDE (with ESP8266 board plugins ?)
#ifdef PAC_ON_D1MINI
#include <ESP8266WiFi.h>
#endif
#ifdef PAC_ON_ESP32
// Provided by ESP32 boards
#include <WiFi.h>
#endif

// Install from library manager: "PubSubClient" (2.8)
#include <PubSubClient.h>

// Provided by Arduino IDE (with ESP8266 board plugins ?)
#include <WiFiClientSecure.h>

// Install from library manager:
// - "Adafruit ST7735 and ST7789" (1.11.0)
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_ST7789.h>  // 320x240

// To get current date & time for timestamping messages.
// configTime() sets the ESP system clock via SNTP; required for TLS cert
// validity checks against the HiveMQ broker.
#include <time.h>

#include <Fonts/FreeSans9pt7b.h>  // Police avec accents 9x7 au lieu de 7x5


// Numerical values of HID codes generated by the keyboard on keystrokes
#include "hid_keys.h"

// Our code to manage scan+connection to a BT keyboard
#include "mm_blekb.h"

// Our misc enums
#include "symbols.h"


// ================================================================================
// Toggles
// ================================================================================

// Serial
#define FLAG_READ_SERIAL_INPUTS

#define WITH_LOGS


// ================================================================================
// User configuration
// ================================================================================

// WiFi credentials
const char* ssid = "SatelliteThree";  // Wifi SSID
const char* password = "xxxxxxx";  // WiFi Password
//const char* ssid = "AndroidPACPAC5";          // Wifi SSID
//const char* password = "apapapap";          // WiFi Password

// MQTT Broker details
const char* mqtt_server = "xxxxxx.s1.eu.hivemq.cloud";  // MQTT Broker's URL
const int mqtt_port = 8883;                                                       // TLS Port
const char* mqtt_user = "xxxxx";                                                  // Credential Username
const char* mqtt_password = "xxxxxxx";                                           // Credential Password

const char* g_mqttOutgoingTopicLogs = "admin/logs";
const char* g_mqttOutgoingTopicLive = "admin/live";
const char* g_mqttOutgoingTopicWill = "admin/dead";
const char* g_mqttIncomingTopicBroadcast = "msg/broadcast";
//                                         "msg/unicast/12"


#define NTP_UTC_OFFSET_S 7200  // UTC+2

// Certificate linked in https://community.hivemq.com/t/frequently-asked-questions-hivemq-cloud/514
const char* root_ca =
  "-----BEGIN CERTIFICATE-----\n"
  "MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw\n"
  "TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\n"
  "cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4\n"
  "WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu\n"
  "ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY\n"
  "MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc\n"
  "h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+\n"
  "0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U\n"
  "A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW\n"
  "T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH\n"
  "B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC\n"
  "B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv\n"
  "KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn\n"
  "OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn\n"
  "jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw\n"
  "qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI\n"
  "rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV\n"
  "HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq\n"
  "hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL\n"
  "ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ\n"
  "3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK\n"
  "NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5\n"
  "ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur\n"
  "TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC\n"
  "jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc\n"
  "oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq\n"
  "4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA\n"
  "mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d\n"
  "emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=\n"
  "-----END CERTIFICATE-----\n";



// ================================================================================
// Configurable behaviour
// ================================================================================

#define LED_BLINK_FAST_DURATION 150
#define LED_BLINK_SLOW_DURATION 700

// Period between sending 2 "keepalive" messages
#define MQTT_KEEPALIVE_INTERVAL 30000
// Period between retring connection to MQTT broker
#define MQTT_CONNECT_RETRY_INTERVAL 5000


// MAC found by sketchbook/esp32_scan_bt_classic_and_ble/ project
#define KEYBOARD_MAC_ADDRESS "xx:xx:xx:xx:xx:xx"


// ================================================================================
// Hardware configuration
// ================================================================================

// Pins configuration
// ------------------
// Pins OK:
// D0 GPIO16 Attention : Ne supporte pas les interruptions. Doit être à HIGH au démarrage pour éviter les problèmes.
// D5 GPIO14 Disponible.
// D6 GPIO12 Disponible.
// D7 GPIO13 Recommandée pour une LED.
// D8 GPIO15 Attention : Doit être à LOW au démarrage pour le mode flash.
// Pins Not OK:
// Évite les broches D3 (GPIO0) et D4 (GPIO2) si tu utilises le WiFi ou le bootloader.
// D1 GPIO5 : OLED shield pour la communication I2C (SCL)
// D2 GPIO4 : OLED shield pour la communication I2C (SDA)
// D3 GPIO0 Attention : Doit être à HIGH au démarrage (sinon, le D1 Mini passe en mode flash).
// D4 GPIO2 LED intégrée (inversée : LOW = allumée). Peut être utilisée, mais la LED bleue intégrée s'allumera aussi.


#ifdef PAC_ON_D1MINI
//Préfère les broches D1, D2, D5, D6, D7 ou D8 pour une LED.
#define LED_STATUS D8
#define LED_FRIEND_1 D6
#define LED_FRIEND_2 D1
#endif
#ifdef PAC_ON_ESP32
#define LED_STATUS 32
#define LED_FRIEND_1 33
#define LED_FRIEND_2 25
#endif


// OLED configuration
// ------------------
// SCL GPIO5
// SDA GPIO4
#define OLED_RESET 0  // GPIO0  TODO Correct?


// STT7789v pins, vue de dessus
// GND, VCC, SCL, SDA, RST, DC, CS


// On TFT to D1mini :
//
//   CS:  D1Mini pin D2 (GPIO4)
//   RST: D1Mini pin D3 (GPIO0)
//   DC:  D1Mini pin D4 (GPIO2)
//   No need for constants if using std pins:
#ifdef PAC_ON_D1MINI
//     SCK (CLK) ---> D1Mini pin D5 (GPIO14, SLCK).  By default
//     MOSI(DIN) ---> D1Mini pin D7 (GPIO13)
#define TFT_RST D3
#define TFT_CS D2
#define TFT_DC D4
#endif

// On ESP32:
#ifdef PAC_ON_ESP32
// SCL : D18 GPIO18 "SCK". By default
// SDA : D23 GPIO23 "MOSI"
#define TFT_RST -1  // optional, can use RST pin
#define TFT_DC 2    // GPIO2 : Data/Command select
#define TFT_CS 5    // GPIO5 : chip select, optionnal, can tie to GND if only one device
#endif



// ================================================================================
// Global variables
// ================================================================================


// Position d’écriture dans l’espace virtuel
uint16_t g_nextTextTopY = 0;

// Objet représentant une ligne
#define BOX_X 0
#define BOX_Y 1
#define BOX_W 2
#define BOX_H 3

#include "display.h"


const int MAX_LINES = 40;   // nombre max de lignes gardées en mémoire
TextLine lines[MAX_LINES];  // buffer des lignes
int lineCount = 0;          // nombre de lignes utilisées

#define CONVO_TS_FONT_SIZE 1
#define CONVO_TS_MARGIN_BOTTOM 3  // avec font par defaut: 3
#define CONV0_TS_COLOR ST77XX_CYAN

#define CONVO_MSG_FONT_SIZE 1      // 2 est vraiment trop énorme avec la font FreeSans9pt7b
#define CONVO_MSG_MARGIN_BOTTOM 7  //

#define CONVO_INFO_COLOR ST77XX_GREEN
#define CONVO_ERROR_COLOR ST77XX_RED

// WiFi
WiFiClientSecure g_wifiClient;

// MQTT
PubSubClient g_mqttClient(g_wifiClient);  // a WiFiClientSecure instance is needed for HiveMQ connection
int g_mqttConnectionId = -1;
unsigned int g_mqttOutputMsgId = 0;
bool g_mqttWasConnected = false;
unsigned long g_mqttLastReconnectTryTimestampMs = 0;
unsigned long g_mqttPreviousKeepAliveTimestampMs = 0;


// Size includes all standard fields plus user's payload
#define MSG_BUFFER_SIZE 500
char g_mqttOutgoingMsg[MSG_BUFFER_SIZE];

#define MQTT_TOPIC_SIZE 30
char g_mqttOutoingRecipientTopic[MQTT_TOPIC_SIZE];


// OLED Display
DisplayType g_displayType = ST7789;

Adafruit_GFX* g_disp = NULL;

static const unsigned char PROGMEM logo16_glcd_bmp[] = { B00000000, B11000000,
                                                         B00000001, B11000000,
                                                         B00000001, B11000000,
                                                         B00000011, B11100000,
                                                         B11110011, B11100000,
                                                         B11111110, B11111000,
                                                         B01111110, B11111111,
                                                         B00110011, B10011111,
                                                         B00011111, B11111100,
                                                         B00001101, B01110000,
                                                         B00011011, B10100000,
                                                         B00111111, B11100000,
                                                         B00111111, B11110000,
                                                         B01111100, B11110000,
                                                         B01110000, B01110000,
                                                         B00000000, B00110000 };


// format "YYYY-MM-DD HH:MM:SS"
char g_ts[20];


// Serial
#ifdef FLAG_READ_SERIAL_INPUTS
#define MAX_SERIAL_MSG_LENGTH 100
char g_contentFromSerial[MAX_SERIAL_MSG_LENGTH + 1];
char g_inChar;
byte g_inNextCharIndex = 0;
#endif

// Messaging
// Device IDs are unsigned bytes [0..255]. 0xFF is the "unset" sentinel — any
// real device gets a small positive ID assigned in identifyDevice().
#define DEVICE_ID_UNSET 0xFF
byte g_deviceIdMe = DEVICE_ID_UNSET;
byte g_deviceIdFriend1 = DEVICE_ID_UNSET;
byte g_deviceIdFriend2 = DEVICE_ID_UNSET;
char g_deviceIdChars[4];
char g_deviceName[40];
char g_userPseudo[40];


#define LED_STATE_NOT_CONFIGURED -1
#define LED_STATE_OFF 0
#define LED_STATE_ON 1
#define LED_STATE_BLINK_FAST 2
#define LED_STATE_BLINK_SLOW 3
#define LED_QTY 17
byte g_ledRequiredState[LED_QTY];
bool g_ledBlinkStateIsHigh[LED_QTY];
unsigned long g_ledBlinkLastTimestampMs[LED_QTY];

// Keyboard
bool kbIsCapsLockOn = false;
String g_currentMsg = "";


// ================================================================================
// H zzz
// ================================================================================

void setRecipient(int recipientDeviceId);
void showUpdatedInfoScreen(bool withMQTTInfo);


// ================================================================================
// Logging
// ================================================================================

// Impression d'une seule valeur
template<typename T>
void p_single(const T& val) {
  Serial.print(val);
}

// Impression de plusieurs valeurs
template<typename T, typename... Args>
void p_single(const T& first, const Args&... rest) {
  Serial.print(first);
  p_single(rest...);
}

template<typename... Args>
void hlog(const Args&... args) {
#ifdef WITH_LOGS
  Serial.print(g_deviceName);
  Serial.print(" - ");
  p_single(args...);  // Imprime tous les arguments
#endif WITH_LOGS
}

template<typename... Args>
void hlogn(const Args&... args) {
#ifdef WITH_LOGS
  Serial.print(g_deviceName);
  Serial.print(" - ");
  p_single(args...);  // Imprime tous les arguments
  Serial.println();
#endif WITH_LOGS
}

template<typename... Args>
void log(const Args&... args) {
#ifdef WITH_LOGS
  p_single(args...);  // Imprime tous les arguments
#endif WITH_LOGS
}

template<typename... Args>
void logn(const Args&... args) {
#ifdef WITH_LOGS
  p_single(args...);  // Imprime tous les arguments
  Serial.println();
#endif WITH_LOGS
}


void error(String msg) {
#ifdef WITH_LOGS
  Serial.print("ERROR: ");
  Serial.println(msg);
#endif
}

void assertTrue(boolean condition, String msg) {
#ifdef WITH_LOGS
  if (!condition) {
    Serial.print("ERROR: ");
    Serial.println(msg);
  }
#endif
}

// ================================================================================
// char* & Strings
// ================================================================================

char* trim(char* str) {
  // Left trim
  while (isspace((unsigned char)*str)) str++;

  if (*str == 0)  // all spaces?
    return str;

  // Right trim
  char* end = str + strlen(str) - 1;
  while (end > str && isspace((unsigned char)*end)) end--;

  // Write new null terminator
  *(end + 1) = '\0';

  return str;
}

// ================================================================================
// Time
// ================================================================================
void setupNTP() {
  hlog("Init NTP...");
  configTime(NTP_UTC_OFFSET_S, 0, "europe.pool.ntp.org", "pool.ntp.org");

  // Block until SNTP returns a plausible epoch (after 2023-11) so the first
  // TLS handshake doesn't run with a 1970 clock and reject the broker cert.
  time_t now = 0;
  int tries = 0;
  while ((now = time(nullptr)) < 1700000000 && tries++ < 30) {
    delay(500);
    log(".");
  }
  logn(" NTP synced, epoch=", (long)now);
}

char* getCurrentDateTime() {
  time_t epochTime = time(nullptr);
  struct tm timeInfo;
  localtime_r(&epochTime, &timeInfo);

  snprintf(g_ts, sizeof(g_ts), "%04d-%02d-%02d|%02d:%02d:%02d",
           timeInfo.tm_year + 1900,
           timeInfo.tm_mon + 1,
           timeInfo.tm_mday,
           timeInfo.tm_hour,
           timeInfo.tm_min,
           timeInfo.tm_sec);

  return g_ts;
}

char* getCurrentTime() {
  time_t epochTime = time(nullptr);
  struct tm timeInfo;
  localtime_r(&epochTime, &timeInfo);

  snprintf(g_ts, sizeof(g_ts), "%02d:%02d:%02d",
           timeInfo.tm_hour,
           timeInfo.tm_min,
           timeInfo.tm_sec);

  return g_ts;
}


// ============================================================================
// Keystrokes
// ============================================================================

// USB HID keycode to ASCII lookup tables
char keymapLower[128] = {
  0, 0, 0, 0, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
  'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
  '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
  '\n', 0, '\b', '\t', ' ', '-', '=', '[', ']', '\\',
  '#', ';', '\'', '`', ',', '.', '/',
  // extend if needed
};

char keymapUpper[128] = {
  0, 0, 0, 0, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
  'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
  '!', '@', '#', '$', '%', '^', '&', '*', '(', ')',
  '\n', 0, '\b', '\t', ' ', '_', '+', '{', '}', '|',
  '~', ':', '"', '~', '<', '>', '?',
  // extend if needed
};

void decodeHIDReport(uint8_t* pData, size_t length) {
  if (length < 8) return;  // HID report is usually 8 bytes

  uint8_t modifiers = pData[0];
  uint8_t key1 = pData[2];  // First key pressed (others in pData[3..7])

  if (key1 != 0) {

    // Handle Caps Lock toggle
    if (key1 == KEY_CAPSLOCK) {  // HID code for Caps Lock
      kbIsCapsLockOn = !kbIsCapsLockOn;
      Serial.printf("CapsLock toggled: %s\n", (kbIsCapsLockOn ? "ON" : "OFF"));
      return;
    }
    // Backspace, removes one char in buffer
    else if (key1 == KEY_BACKSPACE) {
      if (g_currentMsg.length() >= 1) {
        g_currentMsg.remove(g_currentMsg.length() - 1);
        Serial.printf("Current msg: [%s]\n", g_currentMsg.c_str());
      }
      return;
    } else if (key1 == KEY_ENTER) {
      Serial.println("ENTER key. Sending message buffer");
      Serial.println("TODO Send message !");
      g_currentMsg = "";
      return;
    } else if (key1 == KEY_LEFT) {
      Serial.println("TODO KEY_LEFT key. ");
      return;
    } else if (key1 == KEY_RIGHT) {
      Serial.println("TODO KEY_RIGHT key. ");
      return;
    }

    else if (key1 == KEY_ESC) {
      Serial.println("ESC key. Resetting message buffer");
      g_currentMsg = "";
      return;
    }
    // Keys we don't want to deal with
    else if (key1 == KEY_TAB || key1 == KEY_UP || key1 == KEY_DOWN) {
      Serial.printf("HID code [%d] explicitly ignored\n", key1);
      return;
    }

    bool usingSomeShift = (modifiers & 0x22);  // LeftShift(0x02) or RightShift(0x20)

    Serial.printf("HID Code: [%d], modifiers [%d], shift [%d]\n", key1, modifiers, usingSomeShift);

    char ascii = 0;
    if (key1 < 128) {
      if ((kbIsCapsLockOn ^ usingSomeShift) && keymapUpper[key1]) {
        ascii = keymapUpper[key1];
      } else {
        ascii = keymapLower[key1];
      }
    }

    if (ascii) {
      Serial.printf("Key: [%c]\n", ascii);
      g_currentMsg.concat(ascii);
      Serial.printf("Current msg: [%s]\n", g_currentMsg.c_str());

    } else {
      Serial.print("Unknown HID code: ");
      Serial.println(key1);
    }
  }
}


void onBluetoothKeyboardConnectionCallback(bool isFullyConnected) {
  Serial.printf("onKeyboardConnectionCallback(%d)\n", isFullyConnected);
  showUpdatedInfoScreen(true);
}

static void onBluetoothKeyboardNotifyCallback(uint8_t* pData, size_t length) {
  decodeHIDReport(pData, length);
}



// ================================================================================
// Connectivity
// ================================================================================

void identifyDevice() {
  // Read the MAC from eFuse directly. The WiFi.macAddress() String overload uses
  // esp_wifi_get_mac() which races with the async WiFi driver init on ESP32 core 3.x
  // and can return all zeros. The byte-buffer overload reads from eFuse and works
  // regardless of WiFi state.
  String mac;
#ifdef PAC_ON_ESP32
  uint8_t macBytes[6];
  WiFi.macAddress(macBytes);
  char macStr[18];
  snprintf(macStr, sizeof(macStr), "%02X:%02X:%02X:%02X:%02X:%02X",
           macBytes[0], macBytes[1], macBytes[2], macBytes[3], macBytes[4], macBytes[5]);
  mac = macStr;
#else
  mac = WiFi.macAddress();
#endif
  hlogn("MAC Address: ", mac);

  int recipientId = 3;

  if (mac == "xx:xx:xx:xx:xx:xx") {
    g_deviceIdMe = 1;
    snprintf(g_deviceName, sizeof(g_deviceName), "D1M_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Papa");
    g_deviceIdFriend1 = 2;
    g_deviceIdFriend2 = 3;

    //    g_displayType = DISPLAY_TYPE_OLEDSHIELD;
    g_displayType = DisplayType::ST7789;
  } else if (mac == "xx:xx:xx:xx:xx:xx") {
    g_deviceIdMe = 2;
    snprintf(g_deviceName, sizeof(g_deviceName), "D1M_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Maïa");
    g_deviceIdFriend1 = 1;
    g_deviceIdFriend2 = 3;
  } else if (mac == "xx:xx:xx:xx:xx:xx") {
    g_deviceIdMe = 3;
    snprintf(g_deviceName, sizeof(g_deviceName), "D1M_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Jolan");
    g_deviceIdFriend1 = 1;
    g_deviceIdFriend2 = 2;
    recipientId = 2;

    g_displayType = DisplayType::OLEDSHIELD;

  } else if (mac == "xx:xx:xx:xx:xx:xx") {
    // ESP32-02
    g_deviceIdMe = 4;

    snprintf(g_deviceName, sizeof(g_deviceName), "E32_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Proto");
    g_deviceIdFriend1 = 2;
    g_deviceIdFriend2 = 3;

    //    g_displayType = DISPLAY_TYPE_OLEDSHIELD;
    g_displayType = DisplayType::ST7789;
  } else if (mac == "00:00:00:00:00:00") {

    error("MAC address is unknown. WiFi.begin() was not enough in bootstrap sequence.");

  } else {
    strcpy(g_userPseudo, "JohnDoe");
    g_deviceIdMe = random(100, 1000);
    snprintf(g_deviceName, sizeof(g_deviceName), "E32_%03d", g_deviceIdMe);
  }

  // Non formated g_deviceIdMe (pour Will topic)
  snprintf(g_deviceIdChars, 4, "%d", g_deviceIdMe);

  hlogn("Identified device: name=", g_deviceName, ", id=", g_deviceIdMe, ", screenType:", g_displayType);

  setRecipient(recipientId);
}


// ================================================================================
// WIFI
// ================================================================================

void setupWifi() {
  hlogn("setupWifi()...");
  WiFi.disconnect(true, true);     // clear any prior config & stop in-flight attempts
  WiFi.mode(WIFI_STA);
  WiFi.setHostname(g_deviceName);  // ESP32 core 3.x: setHostname() must be called before begin()

  WiFi.begin(ssid, password);

  hlog("WiFi: Connecting...");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    log(".");
  }
  logn(" Connected. IP=", WiFi.localIP().toString());

  setupNTP();  // For ESP32 boards, this call must be done after the Wifi is connected (was not important on D1mini though)


  // TODO mettre un define
  // TODO tester sans
  if (true) {
    g_wifiClient.setInsecure();  // Use this if you don't have a certificate
  } else {
    // For HiveMQ TLS
    g_wifiClient.setCACert(root_ca);  // Set the root CA
  }
}

// ================================================================================
// BLUETOOTH KEYBOARD
// ================================================================================

MiniMessengerBLEKeyboardInterface g_kb;

boolean setupKeyboard() {
  Serial.println("setupKeyboard()...");

  g_currentMsg.reserve(100);

  return g_kb.setup(
    "Bluetooth Keyboard",
    true, //false,
    onBluetoothKeyboardConnectionCallback,
    onBluetoothKeyboardNotifyCallback);
}



// ================================================================================
// MQTT
// ================================================================================

#define MQTT_MSG_RETAINED true
#define MQTT_MSG_NOT_RETAINED false

#define MQTT_SESSION_VOLATILE true
#define MQTT_SESSION_PERSISTED false

#define MQTT_QOS_0 0
#define MQTT_QOS_1 1
#define MQTT_QOS_2 2

// Return true is reconnection is successfull
bool mqttReconnect() {
  hlog("MQTT: Attempting connection...");
  hlogn(" heap free=", ESP.getFreeHeap(), " largest block=", ESP.getMaxAllocHeap());

  unsigned long t0 = millis();
  bool connected = g_mqttClient.connect(
        g_deviceName,
        mqtt_user, mqtt_password,
        g_mqttOutgoingTopicWill, MQTT_QOS_0, MQTT_MSG_NOT_RETAINED, g_deviceIdChars,
        MQTT_SESSION_VOLATILE);
  hlogn("MQTT: connect() returned ", connected, " after ", (millis() - t0), "ms, rc=", g_mqttClient.state());

  if (connected) {
    logn("mqtt connected");
    hlogn("MQTT: MQTT_MAX_PACKET_SIZE=", MQTT_MAX_PACKET_SIZE);

    g_mqttClient.subscribe(g_mqttIncomingTopicBroadcast, MQTT_QOS_1);

    String myUnicastTopic = String("msg/unicast/") + g_deviceIdMe;
    g_mqttClient.subscribe(myUnicastTopic.c_str(), MQTT_QOS_1);
    g_mqttClient.subscribe(g_mqttOutgoingTopicLive, MQTT_QOS_0);
    g_mqttClient.subscribe(g_mqttOutgoingTopicWill, MQTT_QOS_0);

    g_mqttWasConnected = true;
    g_mqttConnectionId++;
    ledSetState(LED_STATUS, LED_STATE_ON);

    // Send public liveness
    mqttSendAlive((g_mqttConnectionId == 0 ? 0 : 1));

    return true;
  } else {
    logn("failed, rc=", g_mqttClient.state(), " trying again in ", MQTT_CONNECT_RETRY_INTERVAL, "ms for device ", g_deviceName);
    // rc=-4 : MQTT_CONNECTION_REFUSED_BAD_USERNAME_OR_PASSWORD (or not using WiFiClientSecure)
    // rc=-2 : MQTT_CONNECTION_REFUSED_SERVER_UNAVAILABLE
    return false;
  }
}

// 0: boot, 1:reco, 2:keepalive
void mqttSendAlive(int liveType) {
  char payload[MSG_BUFFER_SIZE];
  snprintf(payload, MSG_BUFFER_SIZE,
           "%d %s mac:%s ssid:%s ip:%s recoId:%d",
           g_deviceIdMe,
           (liveType == 0 ? "boot" : (liveType == 1 ? "reco" : "keep")),
           WiFi.macAddress().c_str(),
           ssid,
           WiFi.localIP().toString().c_str(),
           g_mqttConnectionId);
  mqttPushFormattedMessage(g_mqttOutgoingTopicLive, payload);
}


void mqttPushFormattedMessage(const char* topic, const char* payload) {
  snprintf(g_mqttOutgoingMsg, MSG_BUFFER_SIZE,
           "%s ### ts:%s deviceId:%d msgId:%d",
           payload,
           getCurrentDateTime(), g_deviceIdMe, g_mqttOutputMsgId);

  hlog("MQTT: Publishing message #", g_mqttOutputMsgId, " to topic [", topic, "] : [", g_mqttOutgoingMsg, ']');
  // Publishing. Only QoS 0 is possible at publish time with PubSubClient
  bool ok = g_mqttClient.publish(topic, g_mqttOutgoingMsg, MQTT_MSG_RETAINED);
  if (ok) {
    logn(". Done.");
  } else {
    logn(". Failed.");
  }

  g_mqttOutputMsgId++;
}


// ================================================================================
// LED
// ================================================================================

void ledSetState(int pin, int requiredState) {
  hlogn("Setting led state for pin #", pin, " to state ", requiredState);
  g_ledRequiredState[pin] = requiredState;

  if (requiredState == LED_STATE_OFF) {
    digitalWrite(pin, LOW);
  } else if (requiredState == LED_STATE_ON) {
    digitalWrite(pin, HIGH);
  } else {
    g_ledBlinkStateIsHigh[pin] = false;
    g_ledBlinkLastTimestampMs[pin] = millis();
    digitalWrite(pin, g_ledBlinkStateIsHigh[pin] ? HIGH : LOW);
    //hlogn("details pin #", pin, " g_ledBlinkStateIsHigh[pin]=", g_ledBlinkStateIsHigh[pin], " g_ledBlinkLastTimestampMs[pin]=", g_ledBlinkLastTimestampMs[pin]);
  }
}

void ledCommuteBlinkState(int pin) {
  g_ledBlinkStateIsHigh[pin] = !g_ledBlinkStateIsHigh[pin];
  g_ledBlinkLastTimestampMs[pin] = millis();
  digitalWrite(pin, g_ledBlinkStateIsHigh[pin] ? HIGH : LOW);
  //hlogn("Switching led state for blinking pin #", pin, " to new state ", g_ledBlinkStateIsHigh[pin]);
}

void setupLeds() {
  pinMode(LED_STATUS, OUTPUT);
  pinMode(LED_FRIEND_1, OUTPUT);
  pinMode(LED_FRIEND_2, OUTPUT);

  for (int i = 0; i < 4; i++) {
    digitalWrite(LED_STATUS, HIGH);
    digitalWrite(LED_FRIEND_1, HIGH);
    digitalWrite(LED_FRIEND_2, HIGH);
    delay(150);
    digitalWrite(LED_STATUS, LOW);
    digitalWrite(LED_FRIEND_1, LOW);
    digitalWrite(LED_FRIEND_2, LOW);
    delay(150);
  }

  for (int pin = 0; pin < LED_QTY; pin++) {
    g_ledRequiredState[pin] = LED_STATE_NOT_CONFIGURED;
  }
  ledSetState(LED_STATUS, LED_STATE_BLINK_FAST);
  ledSetState(LED_FRIEND_1, LED_STATE_OFF);
  ledSetState(LED_FRIEND_2, LED_STATE_OFF);
}



// ================================================================================
// OLED
// ================================================================================

void setupDisplay() {
  if (g_displayType == DisplayType::ST7789) {
    Adafruit_ST7789* pDisp = new Adafruit_ST7789(TFT_CS, TFT_DC, TFT_RST);

    pDisp->init(240, 320);
    pDisp->setRotation(1);

    //pDisp->setScrollMargins(0, 0);  // Pas de marges haute/basse
    // scrollPos = 0;
    // pDisp->setScrollOffset(scrollPos);

    g_disp = pDisp;
  } else {
    hlogn("setupDisplay: DISPLAY_TYPE_NOT_CONFIGURED");
  }
}


void showSplashScreen() {
  // Show image buffer on the display hardware.
  // Since the buffer is intialized with an Adafruit splashscreen internally, this will display the splashscreen.
  int duration = 1000;

  if (g_displayType == DisplayType::ST7789) {
    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    pDisp->fillScreen(ST77XX_BLACK);
    pDisp->print("Splash!");

    duration = 1000;
  } else {
    hlogn("Display: no splash screen");
    duration = 0;
  }

  delay(duration);
}


// Renvoie l'avance de ligne (baseline → baseline) pour la police active
static int lineAdvanceFor(const GFXfont* font, uint8_t textSize) {
  if (font) return font->yAdvance * textSize;  // GFX font
  return 8 * textSize;                         // font bitmap 5x7 par défaut
}


void redrawAllConversations() {
  g_disp->fillScreen(ST77XX_BLACK);

  bool showEnclosingRect = false;
  int nextMessageY = 0;

  // Gestion verticale :
  // - currentTopY = haut de la ligne
  // - baseline = currentTopY - y1  (car y1 est la distance du haut au baseline, souvent négative)
  int lineAdv = lineAdvanceFor(&FreeSans9pt7b, CONVO_MSG_FONT_SIZE);

  //for (int i = 0; i < lineCount; i++) {
  for (auto& line : lines) {
    if (!line.ts.isEmpty()) {
      g_disp->setFont(NULL);
      g_disp->setTextSize(line.tsFontSize);
      g_disp->setTextColor(line.tsColor);

      // Text X/Y bounds are used to tweak text positionning (and not a potential rectangle in background)
      g_disp->setCursor(line.tsX - line.tsBounds[BOX_X], nextMessageY - line.tsBounds[BOX_Y]);
      g_disp->print(line.ts);
      if (showEnclosingRect) {
        g_disp->drawRect(line.tsX, nextMessageY, line.tsBounds[BOX_W], line.tsBounds[BOX_H], ST77XX_MAGENTA);
      }

      nextMessageY += line.tsHeightWithBottomMargin;
    }

    g_disp->setFont(&FreeSans9pt7b);
    g_disp->setTextSize(line.msgFontSize);
    g_disp->setTextColor(line.msgColor);
    g_disp->setCursor(line.msgX - line.msgBounds[BOX_X], nextMessageY - line.msgBounds[BOX_Y]);
    g_disp->print(line.msg);
    if (showEnclosingRect) {
      g_disp->drawRect(line.msgX, nextMessageY, line.msgBounds[BOX_W], line.msgBounds[BOX_H], ST77XX_GREEN);
    }

    nextMessageY += line.msgHeightWithBottomMargin;
  }

  g_nextTextTopY = nextMessageY;
}



void addConversationBlock(String ts, String msg, uint16_t msgColor, Align align) {

  // Dimension TS
  uint16_t tsBlockHWithMargin = 0;

  static int16_t tsBox[4] = { 0, 0, 0, 0 };  // x1, y1, w, h

  /*
1. Pourquoi getTextBounds retourne des valeurs de y négatives avec certaines polices comme FreeSans9pt7b ?
Dans les bibliothèques graphiques comme Adafruit_GFX, le système de coordonnées pour le texte est basé sur le point de base (baseline) du texte. Voici ce qui se passe :


Origine du texte :
Le point (0, 0) pour le texte est généralement placé sur la ligne de base (baseline) du texte, c'est-à-dire la ligne sur laquelle reposent les lettres (sans les descendantes comme "j", "p", "g", etc.).

Valeurs négatives de y :
Pour les polices avec des ascendantes (parties des lettres qui montent au-dessus de la ligne de base, comme "h", "b", "d"), la coordonnée y du rectangle englobant (getTextBounds) peut être négative. Cela signifie que la partie supérieure du texte s'étend au-dessus de la ligne de base.

Exemple : Si la police a une hauteur de 9 pixels et que la ligne de base est à y=0, le sommet des ascendantes pourrait être à y=-2 (selon la police).

Polices comme FreeSans9pt7b :
Ces polices sont souvent conçues avec des ascendantes et descendantes importantes, ce qui explique pourquoi getTextBounds peut retourner des valeurs de y négatives.


Dans la méthode getTextBounds de la bibliothèque Adafruit_GFX, les paramètres retournés sont généralement les suivants :

x : Coordonnée horizontale du coin supérieur gauche du rectangle englobant.
y : Coordonnée verticale du coin supérieur gauche du rectangle englobant (peut être négative si le texte dépasse au-dessus de la ligne de base).
w : Largeur du rectangle englobant.
h : Hauteur totale du rectangle englobant, c'est-à-dire la distance entre le point le plus haut (ascendantes) et le point le plus bas (descendantes) du texte.
Pas besoin d'ajouter l'opposé de y : h est déjà calculé comme la distance entre le point le plus haut (même s'il est au-dessus de la ligne de base, donc y négatif) et le point le plus bas.
*/

  if (!ts.isEmpty()) {
    g_disp->setFont(NULL);
    g_disp->setTextSize(CONVO_TS_FONT_SIZE);
    g_disp->getTextBounds(ts, 0, 0, &tsBox[BOX_X], &tsBox[BOX_Y], (uint16_t*)&tsBox[BOX_W], (uint16_t*)&tsBox[BOX_H]);

    tsBlockHWithMargin = tsBox[BOX_H] + CONVO_TS_MARGIN_BOTTOM;
  }

  // Dimension msg
  uint16_t msgBlockHWithMargin = 0;
  static int16_t msgBox[4] = { 0, 0, 0, 0 };

  g_disp->setFont(&FreeSans9pt7b);
  g_disp->setTextSize(CONVO_MSG_FONT_SIZE);
  g_disp->getTextBounds(msg, 0, 0, &msgBox[BOX_X], &msgBox[BOX_Y], (uint16_t*)&msgBox[BOX_W], (uint16_t*)&msgBox[BOX_H]);
  msgBlockHWithMargin = msgBox[BOX_H] + CONVO_MSG_MARGIN_BOTTOM;


  // Vérifier si ça dépasse la hauteur (on ignore la margin bottom du msg)
  while (g_nextTextTopY + tsBlockHWithMargin + msgBox[BOX_H] >= g_disp->height() || lineCount >= MAX_LINES) {
    // Décaler toutes les lignes d'une place vers le haut
    int regainedY = lines[0].tsHeightWithBottomMargin + lines[0].msgHeightWithBottomMargin;

    for (int i = 1; i < lineCount; i++) {
      lines[i - 1] = lines[i];
    }
    if (lineCount > 0) lineCount--;  // on libère une place

    g_nextTextTopY -= regainedY;
  }

  // Sinon, juste écrire à la suite
  uint16_t tsX = 0, msgX = 0;
  if (align == RIGHT) {
    tsX = g_disp->width() - tsBox[BOX_W];
    msgX = g_disp->width() - msgBox[BOX_W];
  } else if (align == CENTER) {
    tsX = (g_disp->width() - tsBox[BOX_W]) / 2;
    msgX = (g_disp->width() - msgBox[BOX_W]) / 2;
  }

  // Serial.printf("TS  box=(%d, %d, %d, %d) ; msgX=%d \n", tsBox[BOX_X], tsBox[BOX_Y], tsBox[BOX_W], tsBox[BOX_H], tsX);
  //Serial.printf("MSG box=(%d, %d, %d, %d) ; msgX=%d \n", msgBox[BOX_X], msgBox[BOX_Y], msgBox[BOX_W], msgBox[BOX_H], msgX);

  // Créer la nouvelle ligne
  lines[lineCount++] = TextLine(ts, CONV0_TS_COLOR, NULL, CONVO_TS_FONT_SIZE, tsBlockHWithMargin, tsX, tsBox,
                                msg, msgColor, &FreeSans9pt7b, CONVO_MSG_FONT_SIZE, msgBlockHWithMargin, msgX, msgBox);

  // Redessiner tout (scroll inclus)
  redrawAllConversations();
}


// ================================================================================
// Messaging
// ================================================================================

void setRecipient(int recipientDeviceId) {
  snprintf(g_mqttOutoingRecipientTopic, MQTT_TOPIC_SIZE,
           "msg/unicast/%d",
           recipientDeviceId);
  hlogn("MQTT: Setting recipient topic to [", g_mqttOutoingRecipientTopic, ']');
}

void onIncomingTextMessage(String messageDate, String pseudoOther, String message) {

  if (g_displayType == DisplayType::ST7789) {
    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    if (message == "dis") {
      g_mqttClient.disconnect();
    } else {
      addConversationBlock(messageDate, message, ST77XX_YELLOW, LEFT);
    }
  } else {
    hlogn("onMqttIncomingMessage: DISPLAY_TYPE_NOT_CONFIGURED");
  }
}

void onOutgoingMessage(String message) {
  if (g_displayType == DisplayType::ST7789) {
    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    addConversationBlock(getCurrentTime(), message, ST77XX_WHITE, RIGHT);

  } else {
    hlogn("onMqttIncomingMessage: DISPLAY_TYPE_NOT_CONFIGURED");
  }
}


// ================================================================================
// Entrypoints
// ================================================================================

void cleanScreen() {
  if (g_displayType == DisplayType::ST7789) {

    g_disp->fillScreen(ST77XX_BLACK);

  } else {
    hlogn("cleanScreen: DISPLAY_TYPE_NOT_CONFIGURED");
  }
}

void showUpdatedInfoScreen(bool withMQTTInfo) {
  String mac = WiFi.macAddress();


  if (g_displayType == DisplayType::ST7789) {

    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    pDisp->fillScreen(ST77XX_BLACK);

    pDisp->setFont(NULL);  // font par défaut
    pDisp->setTextSize(2);

    int colHeaders = 2;
    int colValues = 70;
    int lineHeight = 22;

    int nextY = 0;

    pDisp->setCursor(colHeaders, nextY);
    pDisp->setTextColor(ST77XX_RED);
    pDisp->print("ID:");
    pDisp->setCursor(colValues, nextY);
    pDisp->setTextColor(ST77XX_WHITE);
    pDisp->print(g_deviceIdMe);
    nextY += lineHeight;

    pDisp->setCursor(colHeaders, nextY);
    pDisp->setTextColor(ST77XX_RED);
    pDisp->print("Name:");
    pDisp->setCursor(colValues, nextY);
    pDisp->setTextColor(ST77XX_WHITE);
    pDisp->print(g_deviceName);
    nextY += lineHeight;

    pDisp->setCursor(colHeaders, nextY);
    pDisp->setTextColor(ST77XX_RED);
    pDisp->print("MAC:");
    pDisp->setCursor(colValues, nextY);
    pDisp->setTextColor(ST77XX_WHITE);
    pDisp->print(mac);
    nextY += lineHeight;

    // Blank line to separate static vs dynamic values
    nextY += lineHeight;

    pDisp->setCursor(colHeaders, nextY);
    pDisp->setTextColor(ST77XX_RED);
    pDisp->print("BTKB:");
    pDisp->setCursor(colValues, nextY);
    pDisp->setTextColor(ST77XX_WHITE);
    pDisp->print(g_kb.isFullyConnected() ? "Connected" : "Not found");
    nextY += lineHeight;

    pDisp->setCursor(colHeaders, nextY);
    pDisp->setTextColor(ST77XX_RED);
    pDisp->print("SSID:");
    pDisp->setCursor(colValues, nextY);
    pDisp->setTextColor(ST77XX_WHITE);
    pDisp->print(ssid);
    nextY += lineHeight;

    pDisp->setCursor(colHeaders, nextY);
    pDisp->setTextColor(ST77XX_RED);
    pDisp->print("IP:");
    pDisp->setCursor(colValues, nextY);
    pDisp->setTextColor(ST77XX_WHITE);
    if (WiFi.status() != WL_CONNECTED) {
      pDisp->print("NO WIFI");
    } else {
      pDisp->print(WiFi.localIP().toString());
    }

    nextY += lineHeight;

    if (withMQTTInfo) {
      pDisp->setCursor(colHeaders, nextY);
      pDisp->setTextColor(ST77XX_RED);
      pDisp->print("MQTT: ");
      pDisp->setCursor(colValues, nextY);
      pDisp->setTextColor(ST77XX_WHITE);
      if (!g_mqttClient.connected()) {
        pDisp->print("NOT OK");
      } else {
        pDisp->print("OK");
      }
    }

  } else {
    hlogn("showUpdatedInfoScreen: DISPLAY_TYPE_NOT_CONFIGURED");
  }
}


void setupTests() {
  // ==== Font default
  // lineAdvance : 8
  // Bounds for text [jjjjj]: x1=0, y1=0, w=30, h=8
  // Bounds for text [Abefg]: x1=0, y1=0, w=30, h=8
  // Bounds for text [     ]: x1=0, y1=0, w=30, h=8
  // Bounds for text [_____]: x1=0, y1=0, w=30, h=8
  // ==== Font FreeSans9pt7b
  // yAdvance : 22
  // lineAdvance : 22
  // Bounds for text [aaaaa]: x1=1, y1=-9, w=49, h=10
  // Bounds for text [ttttt]: x1=1, y1=-11, w=24, h=12
  // Bounds for text [jjjjj]: x1=0, y1=-12, w=20, h=17
  // Bounds for text [Abefg]: x1=0, y1=-12, w=46, h=17
  // Bounds for text [     ]: x1=0, y1=0, w=20, h=0
  // Bounds for text [_____]: x1=0, y1=3, w=50, h=1

  uint8_t textSize = 1;
  String texts[] = { "aaaaa", "AAAAA", "ttttt", "qqqqq", "Attqq", "     ", "_____" };
  String fontNames[] = { "default", "FreeSans9pt7b" };
  const GFXfont* fonts[] = { NULL, &FreeSans9pt7b };

  int16_t x1, y1;
  uint16_t w, h;

  for (int f = 0; f < 2; f++) {
    hlogn("==== Font ", fontNames[f]);
    const GFXfont* font = fonts[f];

    g_disp->setFont(font);
    g_disp->setTextSize(textSize);

    uint8_t yAdvance = 8;
    if (font != NULL) {
      yAdvance = pgm_read_byte(&font->yAdvance);
      hlogn("yAdvance : ", yAdvance);
    }
    uint8_t lineAdvance = yAdvance * textSize;
    hlogn("lineAdvance : ", lineAdvance);

    for (auto& text : texts) {
      g_disp->getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
      hlogn("Bounds for text [", text, "]: x1=", x1, ", y1=", y1, ", w=", w, ", h=", h);
    }
  }

  //     g_disp->fillScreen(ST77XX_BLACK);
  //     g_disp->setFont(&FreeSans9pt7b);
  //         g_disp->setTextColor(ST77XX_YELLOW);
  //             g_disp->setTextSize(2);
  //       g_disp->setCursor(0,0);  // "- bound.y" = decale vers le bas qd .y est négatif (sinon=0)
  //       g_disp->print("Abbppgg");
  //g_disp->display();
  // delay(10000);
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  delay(1000);
  Serial.println("setup()");

  Serial.println("=== minimessenger build " __DATE__ " " __TIME__ " ===");



  // Initialise le générateur de nombres aléatoires
  // Utilise une broche non connectée pour varier la graine (seed)
  randomSeed(analogRead(A0));  // A0 est une broche non connectée (bruit analogique)

  identifyDevice();

  setupDisplay();
  setupLeds();

  //setupTests();

  showSplashScreen();
  showUpdatedInfoScreen(false);

  // Connect to BT
  setupKeyboard();

  // Connect to WiFi
  setupWifi();

  showUpdatedInfoScreen(true);


  // Set up MQTT with TLS
  g_mqttClient.setServer(mqtt_server, mqtt_port);
  g_mqttClient.setCallback(onMqttIncomingMessage);

  //g_mqttWasConnected = true;
  // Test blinking
  //g_mqttLastReconnectTryTimestampMs = millis();

  resetSerialBuffer();

  Serial.println("setup() completed.");
}

void resetSerialBuffer() {
  // Reset g_inNextCharIndex and clean buffer (then no need to add '\0' at end of current msg)
  g_inNextCharIndex = 0;
  for (int i = 0; i <= MAX_SERIAL_MSG_LENGTH; i++) {
    g_contentFromSerial[i] = 0;
  }
}

bool g_firstLoop = true;

void loop() {
  unsigned long currentMillis = millis();  // Temps actuel en millisecondes depuis le démarrage

  g_kb.tryToMaintainConnection();


  if (!g_mqttClient.connected()) {
    if (g_mqttWasConnected) {
      g_mqttWasConnected = false;
      ledSetState(LED_STATUS, LED_STATE_BLINK_FAST);

      addConversationBlock("", "Lost server", CONVO_ERROR_COLOR, CENTER);
      addConversationBlock("", "Trying to reconnect...", CONVO_ERROR_COLOR, CENTER);
    }

    // Time to try to reconnect ?
    if (g_firstLoop || currentMillis - g_mqttLastReconnectTryTimestampMs > MQTT_CONNECT_RETRY_INTERVAL) {
      // Reconnection attempt is successfull
      if (mqttReconnect()) {
        showUpdatedInfoScreen(true);
        delay(1000);

        cleanScreen();
        addConversationBlock("", "Ready !", CONVO_INFO_COLOR, CENTER);
      } else {
        delay(MQTT_CONNECT_RETRY_INTERVAL);
      }
    }
  } else {
    g_mqttClient.loop();

    // MQTT: Send keep-alive
    if (currentMillis - g_mqttPreviousKeepAliveTimestampMs >= MQTT_KEEPALIVE_INTERVAL) {
      // Met à jour le temps de la dernière exécution
      g_mqttPreviousKeepAliveTimestampMs = currentMillis;

      // Send public liveness
      mqttSendAlive(2);
    }
  }



#ifdef FLAG_READ_SERIAL_INPUTS

  // Add a new char to the buffer
  while (Serial.available() > 0) {
    g_inChar = Serial.read();

    // 'Enter key' : send message
    if (g_inChar == '\n') {
      if (g_inNextCharIndex > 0) {
        hlogn("Serial: Read msg id #", g_mqttOutputMsgId, " : ", g_contentFromSerial);
        onOutgoingMessage(g_contentFromSerial);
        mqttPushFormattedMessage(g_mqttOutoingRecipientTopic, g_contentFromSerial);

        resetSerialBuffer();
      } else {
        // Message is empty. Do nothing
        hlogn("Serial: Not publishing an empty message.");
      }
    } else {
      // Too long ?
      if (g_inNextCharIndex >= MAX_SERIAL_MSG_LENGTH) {
        // Force reset all
        hlogn("Serial: Msg too long. Dropping it");
        resetSerialBuffer();
      } else {
        g_contentFromSerial[g_inNextCharIndex] = g_inChar;
        g_inNextCharIndex++;
      }
    }
  }
#endif


  // Blinking leds management
  for (int pin = 0; pin < LED_QTY; pin++) {
    if (g_ledRequiredState[pin] == LED_STATE_BLINK_FAST) {
      if (currentMillis - g_ledBlinkLastTimestampMs[pin] > LED_BLINK_FAST_DURATION) {
        ledCommuteBlinkState(pin);
      }
    } else if (g_ledRequiredState[pin] == LED_STATE_BLINK_SLOW) {
      if (currentMillis - g_ledBlinkLastTimestampMs[pin] > LED_BLINK_SLOW_DURATION) {
        ledCommuteBlinkState(pin);
      }
    }
  }

  g_firstLoop = false;

  // Short cooperative yield. delay(5) on ESP cores calls yield()/vTaskDelay()
  // internally, which lets the lwIP / BLE / Wi-Fi background tasks run and
  // feeds the watchdog. We keep some delay (rather than 0) so a tight loop
  // does not starve those background tasks on single-core paths or hog the CPU
  // for nothing — but we don't want it large because BLE scan, keystroke
  // dispatch, MQTT keepalive and the LED blink tick all live in this loop and
  // each extra millisecond shows up directly as input lag.
  delay(5);
}

void onMqttIncomingMessage(char* topic, byte* payload, unsigned int length) {
  String message;
  for (unsigned int i = 0; i < length; i++) {
    message += (char)payload[i];
  }
  message.trim();

  if (strcmp(topic, g_mqttOutgoingTopicLive) == 0) {
    int remoteDeviceId = atoi(message.c_str());
    onLiveness(remoteDeviceId, true);
  } else if (strcmp(topic, g_mqttOutgoingTopicWill) == 0) {
    int remoteDeviceId = atoi(message.c_str());
    onLiveness(remoteDeviceId, false);
  }
  // msg/unicast/<me> or msg/broadcast
  else if (topic[0] == 'm') {
    hlogn("MQTT: Incoming message [", message, ']');

    onIncomingTextMessage("13:34:23", "Jolan", message);

  } else {
    hlogn("MQTT: Message received in unknown topic [", topic, "] : [", message, ']');
  }
}

void onLiveness(int remoteDeviceId, bool isLive) {
  if (remoteDeviceId == g_deviceIdMe) {
    return;
  }

  hlogn("MQTT: Liveness device #", remoteDeviceId, " isLive:", isLive);
  if (remoteDeviceId == g_deviceIdFriend1) {
    ledSetState(LED_FRIEND_1, (isLive ? LED_STATE_ON : LED_STATE_OFF));
    //digitalWrite(LED_FRIEND_1, (isLive ? HIGH : LOW) );
  } else if (remoteDeviceId == g_deviceIdFriend2) {
    ledSetState(LED_FRIEND_2, (isLive ? LED_STATE_ON : LED_STATE_OFF));
    //digitalWrite(LED_FRIEND_2, (isLive ? HIGH : LOW) );
  }
}