/*
2025-08
ESP32 Whatsapp
avec le freebroker HiveMQ + BT keyboard +

Screen layout (portrait, 240×320, see docs/howto_hardware_scrolling.md):
VSCRDEF = Vertical Scroll Definition =  TFA (Top Fixed Area) + VSA (Vertical Scroll Area) + (BFA Bottom Fixed Area)

  +---------------------------------------------+   ← y=0
  |  ● ● ●                                ●     |   STATUS_BAR (25 px, VSCRDEF TFA)
  |  WiFi BT MQTT                       Contact |   filled/empty per state
  |  (wh) (bl) (yel)                    (red)   |
  |.............................................|   ← y=23 (light gray hairline)
  |                                             |   ← y=24 (1 px black breathing gap)
  +---------------------------------------------+   ← y=25
  |                                             |
  |                                             |
  |   Conversation messages — HW scroll up      |   SCROLL_AREA (272 px, VSCRDEF VSA)
  |   (newest at the bottom, older above)       |   VSCSAD bumped on each new line
  |                                             |
  |                                             |
  |                                             |
  |                                             |         FOOTER (19 px, VSCRDEF BFA)
  |                                             |   ← y=301 (1 px black, aerates against scroll area)
  |---------------------------------------------|   ← y=302 (light gray hairline)
  |                                             |   ← y=303 (1 px black margin)
  +                     typed_msg_buffer_here | +   ← y=304..319 (size-2 text = 16 pixels ; yellow cursor bar)


ArduinoIDE :               2.3.8_Linux_64bit.AppImage
Tools > Boards  :          ESP32 >> ESP32 Dev Module,
                           /dev/ttyUSB0, Baud 115200
Tools > Partition Scheme : "Huge APP (3MB No OTA / 1MB SPIFFS)"
Tools > Core Debug Level : "Verbose"  (flasher après tout changement - pour les libs systèmes, pas notre code qui a ses propres niveaux)

COMPILE: OK
LINK   : OK
UPLOAD : OK
RUN    : ?

Sa console web : https://console.hivemq.cloud/clusters/8f76c91610f343c2b6795974c58861c7/web-g_mqttClient

TODO
- couleur et affichage du pseudo remote (pour chan room multi )
- utiliser WiFiManager (cf mistral) pour configurer le wifi - https://github.com/tzapu/WiFiManager, sinon déplacer la connection dans loop

- taille program:
  Remove Debug Code: Strip out all Serial.print() and debug code for production.
  Use PROGMEM: Store large constants (e.g., strings, images) in PROGMEM.
    pour la font ? ou le logo ? ou certificat ?
  Disable Unused Features: In your library includes, disable features you don’t use (e.g., Adafruit_GFX has options for this).

- indicator
BTKB bonded
BTKB capslock
WIFI ok
MQ ok
Friend present
*/

// ================================================================================
// Librairies
// ================================================================================


// Provided by ESP32 boards
#include <WiFi.h>

// WiFi state machine + onboarding (NVS / WiFiMulti / WiFiManager) lives in wifi.ino. This header pulls in the shared enum and the function
// prototypes that minimessenger.ino calls (setupWifi, wifiTick, wifiGetState, drawPortalInstructions, /wifi-* command helpers).
#include "wifi_state.h"

// Install from library manager: "PubSubClient" (2.8)
#include <PubSubClient.h>

// Provided by Arduino IDE (with ESP8266 board plugins ?)
#include <WiFiClientSecure.h>

// Install from library manager:
// - "Adafruit ST7735 and ST7789" (1.11.0)
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_ST7789.h>  // 320x240

// To get current date & time for timestamping messages.
// configTime() sets the ESP system clock via SNTP; required for TLS cert
// validity checks against the HiveMQ broker.
#include <time.h>

// Cf howto_fond pour la bascule vers une font buildée pour les accents
//#include <Fonts/FreeSans9pt8b.h>  // Police SANS accents 9x7 au lieu de 7x5 de la font par defaut
//#include "FreeSans9pt8b_latin1.h"  // Police AVEC accents (et 9x7 au lieu de 7x5)
#include "FreeSans10pt8b_latin1.h"  // Police AVEC accents (et 9x7 au lieu de 7x5)
// Alias to decouple the sketch from the specific generated font. To switch
// font size or range (7b/8b), change ONLY the #include above + this #define.
#define CONVO_MSG_FONT FreeSans10pt8b


// Numerical values of HID codes generated by the keyboard on keystrokes
#include "hid_keys.h"

// Our code to manage scan+connection to a BT keyboard
#include "mm_blekb.h"

// Our misc enums
#include "symbols.h"

// ESP_LOG* facade + tag definitions (shared with mm_blekb.cpp). Per-tag
// severity is set by setupLogging() in setup().
#include "mm_log.h"


// ================================================================================
// Toggles
// ================================================================================

// Serial
#define FLAG_READ_SERIAL_INPUTS

#define WITH_LOGS


// ================================================================================
// User configuration
// ================================================================================

// WiFi credentials are no longer kept here — see wifi.ino + compiled_wifi.h (gitignored) + NVS for the new onboarding flow. WiFiMulti picks the
// strongest known network at boot; if none respond, the WiFiManager captive portal opens automatically. See docs/howto_wifi.md.

// MQTT Broker details
const char* mqtt_server = "xxxxxx.s1.eu.hivemq.cloud";  // MQTT Broker's URL
const int mqtt_port = 8883;                                                       // TLS Port
const char* mqtt_user = "xxxxx";                                                  // Credential Username
const char* mqtt_password = "xxxxxxx";                                           // Credential Password

const char* g_mqttOutgoingTopicLogs = "admin/logs";
const char* g_mqttOutgoingTopicLive = "admin/live";
const char* g_mqttOutgoingTopicWill = "admin/dead";
const char* g_mqttIncomingTopicBroadcast = "msg/broadcast";
//                                         "msg/unicast/12"


// POSIX timezone string for Paris (Europe/Paris). Decoded:
//   CET-1     standard time name = CET, POSIX offset -1 → human UTC+1
//   CEST      daylight time name = CEST (implicit offset = CET + 1h = UTC+2)
//   M3.5.0    DST starts: Month 3 (March), week 5 (= last), day 0 (Sunday) → last Sunday of March
//   M10.5.0/3 DST ends:   last Sunday of October at 03:00 local
// With this in configTzTime(), the libc handles DST automatically; tm.tm_isdst tells us which side we are on.
#define TZ_PARIS "CET-1CEST,M3.5.0,M10.5.0/3"


// ================================================================================
// Configurable behaviour
// ================================================================================

#define LED_BLINK_FAST_DURATION 150
#define LED_BLINK_SLOW_DURATION 700

// Period between sending 2 "keepalive" messages
#define MQTT_KEEPALIVE_INTERVAL 30000
// Period between retring connection to MQTT broker
#define MQTT_CONNECT_RETRY_INTERVAL 5000

// "Screen saver" Burn-in protection: time without local input (BT keystroke / serial) and
// without a remote message before the screen dims, then fully turns off.
#define DISPLAY_IDLE_BEFORE_DIM_MS 60000UL   // 5 min  -> dim to 50%
#define DISPLAY_IDLE_BEFORE_OFF_MS 800000UL  // 5 + 1 min -> panel off


// ================================================================================
// Hardware configuration
// ================================================================================

// Pins configuration
// ------------------

#define LED_STATUS 32
#define LED_FRIEND_1 33
#define LED_FRIEND_2 25


// OLED configuration
// ------------------
// SCL GPIO5
// SDA GPIO4
#define OLED_RESET 0  // GPIO0  TODO Correct?


// STT7789v pins, vue de dessus
// GND, VCC, SCL, SDA, RST, DC, CS


// On TFT to D1mini :
//   CS:  D1Mini pin D2 (GPIO4)
//   RST: D1Mini pin D3 (GPIO0)
//   DC:  D1Mini pin D4 (GPIO2)
//   No need for constants if using std pins:
//     SCK (CLK) ---> D1Mini pin D5 (GPIO14, SLCK).  By default
//     MOSI(DIN) ---> D1Mini pin D7 (GPIO13)

// On ESP32:
// SCL : D18 GPIO18 "SCK". By default
// SDA : D23 GPIO23 "MOSI"
#define TFT_RST -1  // optional, can use RST pin
#define TFT_DC 2    // GPIO2 : Data/Command select
#define TFT_CS 5    // GPIO5 : chip select, optionnal, can tie to GND if only one device

// Backlight pin for PWM dimming. Set to a GPIO if the BL/LED pin of the panel
// is wired to one (then dim = 50% PWM, off = 0% PWM). Set to -1 if the BL pin
// is tied straight to 3.3 V — the dim phase becomes invisible but the OFF
// state still works because it uses Adafruit_ST7789::enableDisplay(false).
#define TFT_BL -1



// ================================================================================
// Global variables
// ================================================================================


// Certificate linked in https://community.hivemq.com/t/frequently-asked-questions-hivemq-cloud/514
const char* g_hiveMQRootCA =
  "-----BEGIN CERTIFICATE-----\n"
  "MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw\n"
  "TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\n"
  "cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4\n"
  "WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu\n"
  "ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY\n"
  "MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc\n"
  "h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+\n"
  "0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U\n"
  "A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW\n"
  "T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH\n"
  "B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC\n"
  "B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv\n"
  "KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn\n"
  "OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn\n"
  "jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw\n"
  "qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI\n"
  "rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV\n"
  "HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq\n"
  "hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL\n"
  "ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ\n"
  "3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK\n"
  "NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5\n"
  "ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur\n"
  "TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC\n"
  "jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc\n"
  "oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq\n"
  "4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA\n"
  "mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d\n"
  "emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=\n"
  "-----END CERTIFICATE-----\n";


// === Hardware scroll state (ST7789, portrait, partitioned framebuffer) ===
// FB_HEIGHT is the ST7789 framebuffer height in its NATIVE portrait
// orientation. The scroll commands (VSCRDEF / VSCSAD) always operate on
// framebuffer coordinates, irrespective of setRotation().
//
// We partition the 320 framebuffer lines into three regions:
//   [0, 25)             Top Fixed Area     → status bar (indicators)
//   [25, 301)           Vertical Scroll    → conversation messages
//   [301, 320)          Bottom Fixed Area  → input feedback footer
// The Top/Bottom Fixed areas are not affected by VSCSAD — we draw to them
// directly with normal GFX calls.
#define FB_WIDTH 240
#define FB_HEIGHT 320
// STATUS_BAR_H = 24 (icons + separator hairline) + 1 (black gap to aerate
// before the scroll area). The separator is drawn at line STATUS_BAR_H - 2.
#define STATUS_BAR_H 25
// FOOTER_H = 1 (top aération) + 1 (white hairline) + 1 (margin) + 16 (size-2
// text) + 0 (text flush with screen bottom). See the diagram at the top of
// this file for the row-by-row breakdown.
#define FOOTER_H 19
#define SCROLL_AREA_H (FB_HEIGHT - STATUS_BAR_H - FOOTER_H)  // 276
#define SCROLL_AREA_Y_FB STATUS_BAR_H                        // 25
#define FOOTER_Y_FB (FB_HEIGHT - FOOTER_H)                   // 301

// g_scrollY: scroll OFFSET inside the scroll area, in [0, SCROLL_AREA_H).
//            The absolute VSCSAD value sent to the controller is
//            g_scrollY + STATUS_BAR_H.
// g_drawY:   offset inside the scroll area where the next conversation
//            block's top will be drawn. In [0, SCROLL_AREA_H).
//            After a draw + scroll, g_drawY == g_scrollY (mod SCROLL_AREA_H).
uint16_t g_scrollY = 0;
uint16_t g_drawY = 0;

// === Status bar layout ===
// Two network-state chips on the left (WiFi white, MQTT yellow), a 50 px visual spacer, two input-state chips (BT blue + CapsLock A/a in white), then
// the contact silhouette in red on the right. The radius is sized to fit comfortably in the 24 px high bar with a few pixels of margin.
#define ICON_RADIUS 6
#define ICON_Y_CENTER (STATUS_BAR_H / 2)  // 12
// Order from left to right: WiFi, MQTT, [50 px spacer], BT, CapsLock, …, Contact. The 50 px gap separates "network reachability" indicators (left
// cluster) from "keyboard input" indicators (right cluster) so the user can scan their meaning at a glance.
#define ICON_WIFI_X 12
#define ICON_MQTT_X 32
// BT sits 50 px right of MQTT's right edge: ICON_MQTT_X + ICON_RADIUS + 50 + ICON_RADIUS = 32 + 6 + 50 + 6 = 94.
#define ICON_BT_X 94
#define ICON_CAPS_X 114
#define ICON_CONTACT_X (FB_WIDTH - 12)  // 228

// Light-gray hairline drawn on the bottom row of the status bar to visually
// separate it from the scroll area. RGB565 of #DDDDDD = 0xDEFB.
#define STATUS_BAR_SEPARATOR_COLOR 0xDEFB

// Last drawn state — used to skip a redraw when nothing changed.
bool g_lastDrawnBt = false;
bool g_lastDrawnWifi = false;
bool g_lastDrawnMqtt = false;
bool g_lastDrawnCaps = false;
bool g_lastDrawnContact = true;  // placeholder until contact tracking exists
bool g_statusBarDirty = true;
unsigned long g_lastStatusBarPollMs = 0;
#define STATUS_BAR_POLL_INTERVAL_MS 500

// Boot phase = before the very first successful MQTT connect. We sit on the info screen and repaint it periodically so BTKB / WiFi / MQTT state
// transitions are visible while the user waits. Once MQTT comes up for the first time, onMQTTReconnected() flips into conversation mode and this
// refresh stops (the status bar takes over the live status display from then on, see redrawStatusBar). Subsequent MQTT drops do NOT come back here.
unsigned long g_lastInfoScreenRefreshMs = 0;
#define INFO_SCREEN_REFRESH_INTERVAL_MS 2000

// Non-zero value = the info screen is currently shown as a temporary overlay (triggered by "/status") and we should auto-revert to nominal once
// millis() crosses it. Zero = not in the status-overlay state. The revert path is in loop() near the status bar polling block.
unsigned long g_statusScreenEndMs = 0;
#define STATUS_SCREEN_DURATION_MS 10000

// Conversation mode = status bar + scroll area + input footer are all live.
// Fullscreen modes (splash, info) set this to false to suppress the periodic
// status bar repaint that would otherwise draw indicators over their content.
bool g_inConversationMode = false;

// Objet représentant une ligne
#define BOX_X 0
#define BOX_Y 1
#define BOX_W 2
#define BOX_H 3

#include "display.h"


const int MAX_LINES = 13;  // nombre max de lignes gardées en mémoire. Utile uniquement quand on redessine les conversations depuis l'écran de status

// True ring buffer: no per-element shift, no copy on scroll. Logical index i
// (0 = oldest visible line) maps to `lines[(g_lineHead + i) % MAX_LINES]`.
// Adding a line: write at (g_lineHead + g_lineCount) % MAX_LINES, ++g_lineCount.
// Dropping the oldest: ++g_lineHead, --g_lineCount.
TextLine lines[MAX_LINES];
int g_lineHead = 0;
int g_lineCount = 0;

#define CONVO_TS_FONT_SIZE 1
#define CONVO_TS_MARGIN_BOTTOM 3  // avec font par defaut: 3
#define CONV0_TS_COLOR ST77XX_CYAN

#define CONVO_MSG_FONT_SIZE 1      // 2 est vraiment trop énorme avec la font FreeSans9pt8b
#define CONVO_MSG_MARGIN_BOTTOM 7  //

#define CONVO_INFO_COLOR ST77XX_GREEN
#define CONVO_ERROR_COLOR ST77XX_RED
// Hot pink (RGB565 ≈ #FF69B4). Used by command-output listings (help / cmd echoes) to make them visually distinct from regular messages and from info/error notices.
#define CONVO_CMD_COLOR 0xFB56

// When two messages (incoming or outgoing) land within this many seconds,
// suppress the second one's timestamp to declutter the conversation view.
// The "last visible timestamp" tracking continues until a message arrives
// outside the window, at which point the timestamp is shown again.
#define CONVO_TS_HIDE_THRESHOLD_S 10
time_t g_lastShownTsEpoch = 0;

// WiFi
WiFiClientSecure g_wifiClient;

// WiFi reconnection state moved to wifi.ino along with the rest of the WiFi machinery. The state machine there drives banners on rising / falling
// edges; this .ino just exposes UI surfaces.

// MQTT
PubSubClient g_mqttClient(g_wifiClient);  // a WiFiClientSecure instance is needed for HiveMQ connection
int g_mqttConnectionId = -1;
unsigned int g_mqttOutputMsgId = 0;
bool g_mqttWasConnected = false;
unsigned long g_mqttLastReconnectTryTimestampMs = 0;
unsigned long g_mqttPreviousKeepAliveTimestampMs = 0;


// Size includes all standard fields plus user's payload
#define MSG_BUFFER_SIZE 500
char g_mqttOutgoingMsg[MSG_BUFFER_SIZE];

#define MQTT_TOPIC_SIZE 30
char g_mqttOutoingRecipientTopic[MQTT_TOPIC_SIZE];


// OLED Display
DisplayType g_displayType = ST7789;

Adafruit_GFX* g_disp = NULL;

// Burn-in protection state
DisplayPowerState g_displayPowerState = DISPLAY_ON;
unsigned long g_lastActivityMs = 0;

static const unsigned char PROGMEM logo16_glcd_bmp[] = { B00000000, B11000000,
                                                         B00000001, B11000000,
                                                         B00000001, B11000000,
                                                         B00000011, B11100000,
                                                         B11110011, B11100000,
                                                         B11111110, B11111000,
                                                         B01111110, B11111111,
                                                         B00110011, B10011111,
                                                         B00011111, B11111100,
                                                         B00001101, B01110000,
                                                         B00011011, B10100000,
                                                         B00111111, B11100000,
                                                         B00111111, B11110000,
                                                         B01111100, B11110000,
                                                         B01110000, B01110000,
                                                         B00000000, B00110000 };


// format "YYYY-MM-DD HH:MM:SS"
char g_ts[20];


// Serial
#ifdef FLAG_READ_SERIAL_INPUTS
#define MAX_SERIAL_MSG_LENGTH 100
char g_fullMsgFromSerial[MAX_SERIAL_MSG_LENGTH + 1];
char g_inChar;
byte g_inNextCharIndex = 0;
#endif

// Messaging
// Device IDs are unsigned bytes [0..255]. 0xFF is the "unset" sentinel — any
// real device gets a small positive ID assigned in identifyDevice().
#define DEVICE_ID_UNSET 0xFF
byte g_deviceIdMe = DEVICE_ID_UNSET;
byte g_deviceIdFriend1 = DEVICE_ID_UNSET;
byte g_deviceIdFriend2 = DEVICE_ID_UNSET;
char g_deviceIdChars[4];
char g_deviceName[40];
char g_userPseudo[40];


#define LED_STATE_NOT_CONFIGURED -1
#define LED_STATE_OFF 0
#define LED_STATE_ON 1
#define LED_STATE_BLINK_FAST 2
#define LED_STATE_BLINK_SLOW 3
#define LED_QTY 17
byte g_ledRequiredState[LED_QTY];
bool g_ledBlinkStateIsHigh[LED_QTY];
unsigned long g_ledBlinkLastTimestampMs[LED_QTY];

// Keyboard
bool kbIsCapsLockOn = false;
String g_currentMsgFromKeyboard = "";

// Insertion point inside g_currentMsgFromKeyboard, range [0, g_currentMsgFromKeyboard.length()].
// When equal to length(), the cursor sits after the last character (default
// state — equivalent to "append at end").
// Mutated only via the currentMsgXxxCursor() helpers so the invariant is centrally enforced.
size_t g_msgCursorIdx = 0;


// ================================================================================
// H zzz
// ================================================================================

void setRecipient(int recipientDeviceId);
void showUpdatedInfoScreen();
void redrawStatusBar();
void redrawInputFooter();


// ================================================================================
// Logging
// ================================================================================
// All logging uses ESP-IDF's esp_log via mm_log.h. Per-tag severity is
// configured in setup() through setupLogging().

void assertTrue(bool condition, String msg) {
  if (!condition) {
    ESP_LOGE(TAG_MM, "ASSERT FAILED: %s", msg.c_str());
  }
}

// ================================================================================
// char* & Strings
// ================================================================================

char* trim(char* str) {
  // Left trim
  while (isspace((unsigned char)*str)) str++;

  if (*str == 0)  // all spaces?
    return str;

  // Right trim
  char* end = str + strlen(str) - 1;
  while (end > str && isspace((unsigned char)*end)) end--;

  // Write new null terminator
  *(end + 1) = '\0';

  return str;
}

// ================================================================================
// Time
// ================================================================================
void setupNTP() {
  ESP_LOGI(TAG_MM, "Init NTP...");
  // configTzTime (vs configTime with a fixed offset) installs a POSIX TZ rule that auto-switches between CET and CEST. localtime_r will then
  // populate tm.tm_isdst correctly twice a year without us touching anything.
  configTzTime(TZ_PARIS, "europe.pool.ntp.org", "pool.ntp.org");

  // Block until SNTP returns a plausible epoch (after 2023-11) so the first
  // TLS handshake doesn't run with a 1970 clock and reject the broker cert.
  time_t now = 0;
  int tries = 0;
  while ((now = time(nullptr)) < 1700000000 && tries++ < 30) {
    delay(500);
  }
  ESP_LOGI(TAG_MM, "NTP synced after %d tries, epoch=%ld", tries, (long)now);
}

char* getCurrentDateTime() {
  time_t epochTime = time(nullptr);
  struct tm timeInfo;
  localtime_r(&epochTime, &timeInfo);

  snprintf(g_ts, sizeof(g_ts), "%04d-%02d-%02d|%02d:%02d:%02d",
           timeInfo.tm_year + 1900,
           timeInfo.tm_mon + 1,
           timeInfo.tm_mday,
           timeInfo.tm_hour,
           timeInfo.tm_min,
           timeInfo.tm_sec);

  return g_ts;
}

char* getCurrentTime() {
  time_t epochTime = time(nullptr);
  struct tm timeInfo;
  localtime_r(&epochTime, &timeInfo);

  snprintf(g_ts, sizeof(g_ts), "%02d:%02d:%02d",
           timeInfo.tm_hour,
           timeInfo.tm_min,
           timeInfo.tm_sec);

  return g_ts;
}

// Returns "Paris (UTC+1)" in winter (CET) or "Paris (UTC+2)" in summer (CEST). Relies on the POSIX TZ rule installed by setupNTP() via
// configTzTime(TZ_PARIS, ...): the libc populates tm.tm_isdst correctly and we just translate it to the human label.
const char* getTimezoneLabel() {
  time_t epochTime = time(nullptr);
  struct tm timeInfo;
  localtime_r(&epochTime, &timeInfo);
  // tm_isdst > 0 → DST in effect (CEST, UTC+2). 0 → standard (CET, UTC+1). < 0 → unknown (would happen if TZ isn't set; we still default to UTC+1).
  return (timeInfo.tm_isdst > 0) ? "Paris (UTC+2)" : "Paris (UTC+1)";
}


// ============================================================================
// Keystrokes
// ============================================================================

// USB HID keycode to ASCII lookup tables
char keymapLower[128] = {
  0, 0, 0, 0, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
  'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
  '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
  '\n', 0, '\b', '\t', ' ', '-', '=', '[', ']', '\\',
  '#', ';', '\'', '`', ',', '.', '/',
  // extend if needed
};

char keymapUpper[128] = {
  0, 0, 0, 0, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
  'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
  '!', '@', '#', '$', '%', '^', '&', '*', '(', ')',
  '\n', 0, '\b', '\t', ' ', '_', '+', '{', '}', '|',
  '~', ':', '"', '~', '<', '>', '?',
  // extend if needed
};


// === Message buffer editing helpers ==========================================
// All keystroke effects on g_currentMsgFromKeyboard go through these helpers so that the
// cursor invariant (0 <= g_msgCursorIdx <= length()) is enforced in one place
// and decodeHIDReport() stays a flat dispatch table.
// Each helper redraws the footer at the end so callers don't have to.

void currentMsgClear() {
  g_currentMsgFromKeyboard = "";
  g_msgCursorIdx = 0;
  redrawInputFooter();
}

void currentMsgInsertCharAtCursor(char c) {
  g_currentMsgFromKeyboard = g_currentMsgFromKeyboard.substring(0, g_msgCursorIdx)
                             + c
                             + g_currentMsgFromKeyboard.substring(g_msgCursorIdx);
  g_msgCursorIdx++;
  ESP_LOGD(TAG_BTKB, "Insert [%c] at %u → msg=[%s] cur=%u",
           c, (unsigned)(g_msgCursorIdx - 1), g_currentMsgFromKeyboard.c_str(), (unsigned)g_msgCursorIdx);
  redrawInputFooter();
}

// Backspace: removes the character just left of the cursor (and the cursor
// follows). No-op when at the beginning of the buffer. Uses String::remove()
// to shrink in place — no reallocation, friendly to the reserved capacity.
void currentMsgDeleteCharBeforeCursor() {
  if (g_msgCursorIdx == 0) return;
  g_currentMsgFromKeyboard.remove(g_msgCursorIdx - 1, 1);
  g_msgCursorIdx--;
  ESP_LOGD(TAG_BTKB, "Backspace → msg=[%s] cur=%u",
           g_currentMsgFromKeyboard.c_str(), (unsigned)g_msgCursorIdx);
  redrawInputFooter();
}

// Delete (Suppr): removes the character under the cursor. Cursor stays put.
// No-op when at the end of the buffer (nothing to the right).
void currentMsgDeleteCharAtCursor() {
  if (g_msgCursorIdx >= g_currentMsgFromKeyboard.length()) return;
  g_currentMsgFromKeyboard.remove(g_msgCursorIdx, 1);
  ESP_LOGD(TAG_BTKB, "Delete → msg=[%s] cur=%u",
           g_currentMsgFromKeyboard.c_str(), (unsigned)g_msgCursorIdx);
  redrawInputFooter();
}

void currentMsgMoveCursorLeft() {
  if (g_msgCursorIdx == 0) {
    ESP_LOGD(TAG_BTKB, "LEFT at cur=0 — no-op");
    return;
  }
  g_msgCursorIdx--;
  ESP_LOGD(TAG_BTKB, "LEFT → cur=%u", (unsigned)g_msgCursorIdx);
  redrawInputFooter();
}

void currentMsgMoveCursorRight() {
  if (g_msgCursorIdx >= g_currentMsgFromKeyboard.length()) {
    ESP_LOGD(TAG_BTKB, "RIGHT at cur=%u (end) — no-op", (unsigned)g_msgCursorIdx);
    return;
  }
  g_msgCursorIdx++;
  ESP_LOGD(TAG_BTKB, "RIGHT → cur=%u", (unsigned)g_msgCursorIdx);
  redrawInputFooter();
}


void decodeHIDReport(uint8_t* pData, size_t length) {
  if (length < 8) return;  // HID boot keyboard report is 8 bytes

  // HID Boot Keyboard report layout:
  //   pData[0]    = modifier bitmask (Shift/Ctrl/Alt/GUI, left+right)
  //   pData[1]    = reserved (always 0)
  //   pData[2..7] = up to 6 currently-held key codes (6KRO — 6-key rollover)
  //
  // IMPORTANT: a report describes the CURRENT STATE (which keys are held
  // right now), not an event. The keyboard emits a new report on every
  // state change — press OR release. Slots [2..7] are unordered and a given
  // key can migrate between slots from one report to the next.
  //
  // To turn this state stream into discrete keypresses we keep the previous
  // report's key set and only fire for keys that are NEWLY present. This
  // fixes two real-world bugs:
  //
  //   1. Duplicates on dwell / HID auto-repeat
  //      Holding a key past ~500 ms makes the keyboard re-emit the same
  //      report periodically. Reading pData[2] naively appended the same
  //      character on every notification. With press-edge diffing, the key
  //      stays in s_prevKeys[] for the whole hold and triggers exactly once.
  //
  //   2. Lost keys on fast two-hand typing
  //      When B is pressed before A is released, a single report carries
  //      [A, B] together — and the old code (which only looked at pData[2])
  //      never saw B. The diff loop below walks all 6 slots and catches
  //      every newly-pressed one, even when several arrive in the same
  //      notification.

  static uint8_t s_prevKeys[6] = { 0 };
  uint8_t curKeys[6] = { pData[2], pData[3], pData[4], pData[5], pData[6], pData[7] };
  uint8_t modifiers = pData[0];

  // Wake screen on any keystroke. If we were sleeping, discard this report:
  // the user pressed a key to light the screen, not to type. We still commit
  // curKeys into s_prevKeys so a key held across the wake-up boundary isn't
  // mistakenly seen as "newly pressed" on the next report.
  bool anyKeyHeld = false;
  for (int i = 0; i < 6; i++) {
    if (curKeys[i] != 0) {
      anyKeyHeld = true;
      break;
    }
  }
  if (anyKeyHeld && noteUserActivity()) {
    memcpy(s_prevKeys, curKeys, 6);
    return;
  }

  bool usingSomeShift = (modifiers & 0x22);  // LeftShift(0x02) or RightShift(0x20)

  // Walk every slot in the new report; handle each key that wasn't already
  // present in the previous report. Order within [2..7] is whatever the
  // keyboard firmware chose — in practice it matches the press order for the
  // common alternating-fingers case.
  for (int i = 0; i < 6; i++) {
    uint8_t key = curKeys[i];
    if (key == 0) continue;

    bool wasHeldBefore = false;
    for (int j = 0; j < 6; j++) {
      if (s_prevKeys[j] == key) {
        wasHeldBefore = true;
        break;
      }
    }
    if (wasHeldBefore) continue;  // still held since the previous report, not a new press

    // --- Press edge: handle this newly-pressed key ---

    // Log every press at DEBUG so missing keys (e.g. KEY_RIGHT not reaching us
    // at all) are distinguishable from "received but unhandled by our dispatch".
    ESP_LOGD(TAG_BTKB, "HID press code=%u modifiers=%u shift=%d", key, modifiers, usingSomeShift ? 1 : 0);

    if (key == KEY_CAPSLOCK) {
      kbIsCapsLockOn = !kbIsCapsLockOn;
      g_statusBarDirty = true;  // pousse un repaint immédiat de la barre pour faire basculer le glyphe 'A'/'a' sans attendre le tick périodique.
      ESP_LOGD(TAG_BTKB, "CapsLock toggled: %s", kbIsCapsLockOn ? "ON" : "OFF");
      continue;
    } else if (key == KEY_BACKSPACE) {
      currentMsgDeleteCharBeforeCursor();
      continue;
    } else if (key == KEY_DELETE) {
      currentMsgDeleteCharAtCursor();
      continue;
    } else if (key == KEY_ENTER) {
      if (g_currentMsgFromKeyboard.length() > 0) {
        ESP_LOGI(TAG_BTKB, "ENTER — sending msg #%u: %s", g_mqttOutputMsgId, g_currentMsgFromKeyboard.c_str());
        routeMessage(String(g_currentMsgFromKeyboard), MessageSource::LOCAL);
        currentMsgClear();
      } else {
        ESP_LOGD(TAG_BTKB, "ENTER on empty buffer — nothing to send");
      }
      continue;
    } else if (key == KEY_LEFT) {
      currentMsgMoveCursorLeft();
      continue;
    } else if (key == KEY_RIGHT || key == KEY_UP) {
      // KEY_UP doubles as "right" because the BT keyboard bonded to this
      // device doesn't emit KEY_RIGHT (the dedicated right arrow is either
      // absent on the layout or mapped to a FN layer we never receive).
      currentMsgMoveCursorRight();
      continue;
    } else if (key == KEY_ESC) {
      ESP_LOGI(TAG_BTKB, "ESC pressed — resetting message buffer");
      currentMsgClear();
      continue;
    } else if (key == KEY_TAB || key == KEY_DOWN) {
      ESP_LOGD(TAG_BTKB, "HID code [%u] explicitly ignored", key);
      continue;
    }

    char ascii = 0;
    if (key < 128) {
      if ((kbIsCapsLockOn ^ usingSomeShift) && keymapUpper[key]) {
        ascii = keymapUpper[key];
      } else {
        ascii = keymapLower[key];
      }
    }

    if (ascii) {
      currentMsgInsertCharAtCursor(ascii);
    } else {
      ESP_LOGD(TAG_BTKB, "Unknown HID code: %u", key);
    }
  }

  // Commit the new state so the next report can diff against it.
  memcpy(s_prevKeys, curKeys, 6);
}


void onBluetoothKeyboardConnectionCallback(bool isFullyConnected) {
  ESP_LOGI(TAG_BTKB, "onKeyboardConnectionCallback(%d)", isFullyConnected ? 1 : 0);
}

static void onBluetoothKeyboardNotifyCallback(uint8_t* pData, size_t length) {
  decodeHIDReport(pData, length);
}



// ================================================================================
// Connectivity
// ================================================================================

void identifyDevice() {
  // Read the MAC. On arduino-esp32 3.3.8, esp_read_mac(ESP_MAC_WIFI_STA) returns 00:00:00:00:00:00 when called before any WiFi driver init,
  // despite the IDF docs claiming the eFuse path is dependency-free. The reliable workaround is to bring the WiFi driver up in STA mode FIRST
  // (no AP connection, just netif registration) so WiFi.macAddress() can read the address. setupWifi() later issues disconnect(true,true) +
  // mode + begin which is well-defined on top of the already-initialised STA mode, so this early init has no side effect on the connect flow.
  String mac;
#ifdef PAC_ON_ESP32
  uint8_t macBytes[6] = {0};
  WiFi.mode(WIFI_STA);
  WiFi.macAddress(macBytes);
  char macStr[18];
  snprintf(macStr, sizeof(macStr), "%02X:%02X:%02X:%02X:%02X:%02X",
           macBytes[0], macBytes[1], macBytes[2], macBytes[3], macBytes[4], macBytes[5]);
  mac = macStr;
#else
  mac = WiFi.macAddress();
#endif
  ESP_LOGI(TAG_MM, "MAC Address: %s", mac.c_str());

  int recipientId = 3;

  if (mac == "xx:xx:xx:xx:xx:xx") {
    g_deviceIdMe = 1;
    snprintf(g_deviceName, sizeof(g_deviceName), "D1M_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Papa");
    g_deviceIdFriend1 = 2;
    g_deviceIdFriend2 = 3;

    //    g_displayType = DISPLAY_TYPE_OLEDSHIELD;
    g_displayType = DisplayType::ST7789;
  } else if (mac == "xx:xx:xx:xx:xx:xx") {
    g_deviceIdMe = 2;
    snprintf(g_deviceName, sizeof(g_deviceName), "D1M_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Maïa");
    g_deviceIdFriend1 = 1;
    g_deviceIdFriend2 = 3;
  } else if (mac == "xx:xx:xx:xx:xx:xx") {
    g_deviceIdMe = 3;
    snprintf(g_deviceName, sizeof(g_deviceName), "D1M_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Jolan");
    g_deviceIdFriend1 = 1;
    g_deviceIdFriend2 = 2;
    recipientId = 2;

    g_displayType = DisplayType::OLEDSHIELD;

  } else if (mac == "xx:xx:xx:xx:xx:xx") {
    // ESP32-02
    g_deviceIdMe = 4;

    snprintf(g_deviceName, sizeof(g_deviceName), "E32_%03d", g_deviceIdMe);

    strcpy(g_userPseudo, "Proto");
    g_deviceIdFriend1 = 2;
    g_deviceIdFriend2 = 3;

    //    g_displayType = DISPLAY_TYPE_OLEDSHIELD;
    g_displayType = DisplayType::ST7789;
  } else if (mac == "00:00:00:00:00:00") {

    ESP_LOGE(TAG_MM, "MAC address is all zeros — WiFi.begin() was not enough in bootstrap sequence");

  } else {
    strcpy(g_userPseudo, "JohnDoe");
    g_deviceIdMe = random(100, 1000);
    snprintf(g_deviceName, sizeof(g_deviceName), "E32_%03d", g_deviceIdMe);
  }

  // Non formated g_deviceIdMe (pour Will topic)
  snprintf(g_deviceIdChars, 4, "%d", g_deviceIdMe);

  ESP_LOGI(TAG_MM, "Identified device: name=%s id=%d screenType=%d",
           g_deviceName, g_deviceIdMe, (int)g_displayType);

  setRecipient(recipientId);
}


// ================================================================================
// WIFI
// ================================================================================
//
// The connection state machine and the NVS-backed network list live in wifi.ino (concatenated into the same translation unit by the Arduino IDE).
// setupWifi() is defined there and handles the whole WiFi bringup in one call: driver mode + hostname + NVS seed/load + WiFiManager config +
// state machine kick. The TLS root CA wiring stays below in setup() since it's an MQTT concern, not a WiFi one. wifiTick() in loop() drives the
// async association and reconnection.

// ================================================================================
// BLUETOOTH KEYBOARD
// ================================================================================

MiniMessengerBLEKeyboardInterface g_kb;

boolean setupKeyboard() {
  ESP_LOGI(TAG_BTKB, "setupKeyboard()...");

  g_currentMsgFromKeyboard.reserve(100);

  // Scan filter is now based on the HID GATT service UUID (see mm_blekb.cpp::onResult), not on the device name — no keyboard name to pass here.
  return g_kb.setup(
    false,  // clear bonds — flip to true once if a stale bond is blocking pairing with a new physical keyboard; prefer `cmd bonds` at runtime
    onBluetoothKeyboardConnectionCallback,
    onBluetoothKeyboardNotifyCallback);
}



// ================================================================================
// MQTT
// ================================================================================

#define MQTT_MSG_RETAINED true
#define MQTT_MSG_NOT_RETAINED false

#define MQTT_SESSION_VOLATILE true
#define MQTT_SESSION_PERSISTED false

#define MQTT_QOS_0 0
#define MQTT_QOS_1 1
#define MQTT_QOS_2 2

// Return true is reconnection is successfull
bool mqttReconnect() {
  // Pour voir s'il y a assez de bloc memoire pour la connection TLS.
  // mbedtls handshake = ~38-40 KB contigus (16 KB IN + 16 KB OUT + ~6 KB SSL ctx).
  // Heap dispo (largest block) observé :
  //   - Bluedroid : ~24 KB → insuffisant, rc=-2
  //   - NimBLE    : ~60-70 KB attendus → handshake OK
  ESP_LOGI(TAG_MQTT, "Attempting connection... heap free=%u largest block=%u",
           ESP.getFreeHeap(), ESP.getMaxAllocHeap());

  unsigned long t0 = millis();
  bool connected = g_mqttClient.connect(
    g_deviceName,
    mqtt_user, mqtt_password,
    g_mqttOutgoingTopicWill, MQTT_QOS_0, MQTT_MSG_NOT_RETAINED, g_deviceIdChars,
    MQTT_SESSION_VOLATILE);
  ESP_LOGI(TAG_MQTT, "connect() returned %d after %lums, rc=%d",
           connected ? 1 : 0, millis() - t0, g_mqttClient.state());

  if (connected) {
    ESP_LOGI(TAG_MQTT, "Connected, MQTT_MAX_PACKET_SIZE=%d", MQTT_MAX_PACKET_SIZE);

    g_mqttClient.subscribe(g_mqttIncomingTopicBroadcast, MQTT_QOS_1);

    String myUnicastTopic = String("msg/unicast/") + g_deviceIdMe;
    g_mqttClient.subscribe(myUnicastTopic.c_str(), MQTT_QOS_1);
    g_mqttClient.subscribe(g_mqttOutgoingTopicLive, MQTT_QOS_0);
    g_mqttClient.subscribe(g_mqttOutgoingTopicWill, MQTT_QOS_0);

    g_mqttWasConnected = true;
    g_mqttConnectionId++;
    ledSetState(LED_STATUS, LED_STATE_ON);

    // Send public liveness
    mqttSendAlive((g_mqttConnectionId == 0 ? 0 : 1));

    return true;
  } else {
    // rc=-4 : MQTT_CONNECTION_REFUSED_BAD_USERNAME_OR_PASSWORD (or not using WiFiClientSecure)
    // rc=-2 : MQTT_CONNECTION_REFUSED_SERVER_UNAVAILABLE
    ESP_LOGE(TAG_MQTT, "Connect failed (rc=%d), retrying in %dms",
             g_mqttClient.state(), MQTT_CONNECT_RETRY_INTERVAL);
    return false;
  }
}

// 0: boot, 1:reco, 2:keepalive
void mqttSendAlive(int liveType) {
  char payload[MSG_BUFFER_SIZE];
  snprintf(payload, MSG_BUFFER_SIZE,
           "%d %s mac:%s ssid:%s ip:%s recoId:%d",
           g_deviceIdMe,
           (liveType == 0 ? "boot" : (liveType == 1 ? "reco" : "keep")),
           WiFi.macAddress().c_str(),
           WiFi.SSID().c_str(),
           WiFi.localIP().toString().c_str(),
           g_mqttConnectionId);
  mqttPushFormattedMessage(g_mqttOutgoingTopicLive, payload);
}


// Returns true if the publish was accepted by PubSubClient (sent on the wire — no broker ACK at QoS 0 so this is best-effort). Callers that need
// to react to the failure (e.g. routeMessage tagging the local message with "[ERROR] ") should check the return value; keepalive callers can
// safely ignore it — the next interval will retry.
bool mqttPushFormattedMessage(const char* topic, const char* payload) {
  snprintf(g_mqttOutgoingMsg, MSG_BUFFER_SIZE,
           "%s ### ts:%s deviceId:%d msgId:%d",
           payload,
           getCurrentDateTime(), g_deviceIdMe, g_mqttOutputMsgId);

  // Publishing. Only QoS 0 is possible at publish time with PubSubClient
  bool ok = g_mqttClient.publish(topic, g_mqttOutgoingMsg, MQTT_MSG_RETAINED);
  if (ok) {
    ESP_LOGI(TAG_MQTT, "Published #%u to [%s]: [%s]",
             g_mqttOutputMsgId, topic, g_mqttOutgoingMsg);
  } else {
    // On failure, include state() and the payload size so we can tell apart the four PubSubClient failure modes (see CLAUDE.md / discussions):
    //   state =  0 (MQTT_CONNECTED)         → write to the socket failed mid-send (TCP buffer full, TLS error, link dropped between connected()
    //                                          check and write). If size > ~240 bytes, may also be MQTT_MAX_PACKET_SIZE = 256 rejecting it.
    //   state = -1 (MQTT_DISCONNECTED)      → we called disconnect() ourselves.
    //   state = -3 (MQTT_CONNECTION_LOST)   → broker / WiFi dropped; connected() detected it on this call.
    //   state = -4 (MQTT_CONNECTION_TIMEOUT)→ TCP-level timeout. Mostly during a fresh connect, not on publish.
    ESP_LOGE(TAG_MQTT, "Publish FAILED for #%u to [%s] state=%d size=%u : [%s]",
             g_mqttOutputMsgId, topic, g_mqttClient.state(),
             (unsigned)strlen(g_mqttOutgoingMsg), g_mqttOutgoingMsg);
  }

  g_mqttOutputMsgId++;
  return ok;
}


// ================================================================================
// LED
// ================================================================================

void ledSetState(int pin, int requiredState) {
  ESP_LOGD(TAG_MM, "led pin=%d state=%d", pin, requiredState);
  g_ledRequiredState[pin] = requiredState;

  if (requiredState == LED_STATE_OFF) {
    digitalWrite(pin, LOW);
  } else if (requiredState == LED_STATE_ON) {
    digitalWrite(pin, HIGH);
  } else {
    g_ledBlinkStateIsHigh[pin] = false;
    g_ledBlinkLastTimestampMs[pin] = millis();
    digitalWrite(pin, g_ledBlinkStateIsHigh[pin] ? HIGH : LOW);
    //hlogn("details pin #", pin, " g_ledBlinkStateIsHigh[pin]=", g_ledBlinkStateIsHigh[pin], " g_ledBlinkLastTimestampMs[pin]=", g_ledBlinkLastTimestampMs[pin]);
  }

  // drawIndicatorAt
}

void ledCommuteBlinkState(int pin) {
  g_ledBlinkStateIsHigh[pin] = !g_ledBlinkStateIsHigh[pin];
  g_ledBlinkLastTimestampMs[pin] = millis();
  digitalWrite(pin, g_ledBlinkStateIsHigh[pin] ? HIGH : LOW);
  //hlogn("Switching led state for blinking pin #", pin, " to new state ", g_ledBlinkStateIsHigh[pin]);
}

void setupLeds() {
  pinMode(LED_STATUS, OUTPUT);
  pinMode(LED_FRIEND_1, OUTPUT);
  pinMode(LED_FRIEND_2, OUTPUT);

  for (int i = 0; i < 4; i++) {
    digitalWrite(LED_STATUS, HIGH);
    digitalWrite(LED_FRIEND_1, HIGH);
    digitalWrite(LED_FRIEND_2, HIGH);
    delay(150);
    digitalWrite(LED_STATUS, LOW);
    digitalWrite(LED_FRIEND_1, LOW);
    digitalWrite(LED_FRIEND_2, LOW);
    delay(150);
  }

  for (int pin = 0; pin < LED_QTY; pin++) {
    g_ledRequiredState[pin] = LED_STATE_NOT_CONFIGURED;
  }
  ledSetState(LED_STATUS, LED_STATE_BLINK_FAST);
  ledSetState(LED_FRIEND_1, LED_STATE_OFF);
  ledSetState(LED_FRIEND_2, LED_STATE_OFF);
}



// ================================================================================
// OLED
// ================================================================================

// === Hardware vertical scroll helpers (ST7789, MIPI DCS commands) ===
// See docs/howto_hardware_scrolling.md for the full design rationale.
// 0x33 (VSCRDEF) declares the scroll area partition; 0x37 (VSCSAD) sets the
// virtual top line within that partition. No high-level API in Adafruit_GFX
// exposes this, hence the raw sendCommand() calls.

void hwScrollSetupArea() {
  if (g_displayType != DisplayType::ST7789) return;
  Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;
  // TFA = STATUS_BAR_H, VSA = SCROLL_AREA_H, BFA = FOOTER_H.
  // TFA + VSA + BFA must equal FB_HEIGHT (=320 for ST7789).
  uint8_t args[6] = {
    0,
    STATUS_BAR_H,
    (uint8_t)(SCROLL_AREA_H >> 8),
    (uint8_t)(SCROLL_AREA_H & 0xFF),
    0,
    FOOTER_H,
  };
  pDisp->sendCommand(0x33, args, 6);  // VSCRDEF
}

// `scrollOffset` is the offset within the scroll area in [0, SCROLL_AREA_H).
// The absolute VSCSAD value sent to the controller must be in [TFA, TFA+VSA).
void hwScrollTo(uint16_t scrollOffset) {
  g_scrollY = scrollOffset % SCROLL_AREA_H;
  if (g_displayType != DisplayType::ST7789) return;
  Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;
  uint16_t absoluteScrollY = g_scrollY + STATUS_BAR_H;
  uint8_t args[2] = { (uint8_t)(absoluteScrollY >> 8), (uint8_t)(absoluteScrollY & 0xFF) };
  pDisp->sendCommand(0x37, args, 2);  // VSCSAD
}

// Reset scroll state and clear the ENTIRE framebuffer (status bar and footer
// included). Used by splash / info screens that paint full-screen content.
// goAndResetConversationScreen() (the conversation-mode entry point) calls this AND then
// redraws the status bar and footer borders on top.
void hwScrollReset() {
  g_scrollY = 0;
  g_drawY = 0;
  hwScrollTo(0);
  if (g_displayType == DisplayType::ST7789) {
    g_disp->fillScreen(ST77XX_BLACK);
  }
  // Force status bar to redraw next time it's polled (state cache is now stale).
  g_statusBarDirty = true;
}


// === Status bar (TFA) ===
// Three indicators on the left, one chip on the right. Filled = ON, outline only = OFF.
static void drawIndicatorAt(int x, bool filled, uint16_t color) {
  if (filled) {
    g_disp->fillCircle(x, ICON_Y_CENTER, ICON_RADIUS, color);
  } else {
    g_disp->drawCircle(x, ICON_Y_CENTER, ICON_RADIUS, color);
  }
}

// CapsLock indicator: glyph 'A' (caps ON) ou 'a' (caps OFF) en blanc, à droite du chip BT. La détection est portée par la variable globale
// kbIsCapsLockOn, basculée dans decodeHIDReport() à la frappe du KEY_CAPSLOCK ; ce dernier marque g_statusBarDirty pour un rafraîchissement immédiat
// sans attendre le tick périodique. Police par défaut 5×7 à setTextSize(2) → glyphe 10×14 px, comparable au diamètre des disques voisins. Le cursor
// est offset de la moitié des dimensions du glyphe pour centrer visuellement sur (cx, ICON_Y_CENTER).
static void drawCapsAt(int cx, bool capsOn, uint16_t color) {
  g_disp->setFont(NULL);
  g_disp->setTextSize(2);
  g_disp->setTextColor(color);
  g_disp->setCursor(cx - 5, ICON_Y_CENTER - 7);
  g_disp->print(capsOn ? 'A' : 'a');
}

// Person silhouette used for the contact chip on the right of the status bar: small head + rounded shoulders/torso, sized to match visually the
// radius-6 disc indicators on the left. Plein si filled=true (contact présent), simple contour sinon. Tête = cercle r=3 centré à (cx, 8) ; corps =
// RoundRect 11×7 démarrant à (cx-5, 12) avec coins r=3 pour évoquer les épaules. Un pixel d'air entre la tête (y=5..11) et le corps (y=12..18) sert
// de cou et garde la silhouette lisible en mode contour.
static void drawPersonAt(int cx, bool filled, uint16_t color) {
  const int headCy = ICON_Y_CENTER - 4;  // 8
  const int headR = 3;
  const int bodyX = cx - 5;
  const int bodyY = ICON_Y_CENTER;  // 12
  const int bodyW = 11;
  const int bodyH = 7;
  const int bodyR = 3;

  if (filled) {
    g_disp->fillCircle(cx, headCy, headR, color);
    g_disp->fillRoundRect(bodyX, bodyY, bodyW, bodyH, bodyR, color);
  } else {
    g_disp->drawCircle(cx, headCy, headR, color);
    g_disp->drawRoundRect(bodyX, bodyY, bodyW, bodyH, bodyR, color);
  }
}

// Read current connection states and repaint the bar if any of them changed
// since the last draw (or if forced by g_statusBarDirty). No-op when a
// fullscreen mode (splash, info) is showing — would otherwise paint icons
// over their content.
void redrawStatusBar() {
  if (!g_inConversationMode) return;

  bool bt = g_kb.isFullyConnected();
  bool wifi = (WiFi.status() == WL_CONNECTED);
  bool mqtt = g_mqttClient.connected();
  bool caps = kbIsCapsLockOn;
  bool contact = true;  // TODO wire to actual friend-presence tracking

  if (!g_statusBarDirty
      && bt == g_lastDrawnBt
      && wifi == g_lastDrawnWifi
      && mqtt == g_lastDrawnMqtt
      && caps == g_lastDrawnCaps
      && contact == g_lastDrawnContact) {
    return;
  }

  if (g_displayType != DisplayType::ST7789) return;

  g_disp->fillRect(0, 0, FB_WIDTH, STATUS_BAR_H, ST77XX_BLACK);
  // Left cluster (network reachability): WiFi puis MQTT côte à côte.
  drawIndicatorAt(ICON_WIFI_X, wifi, ST77XX_WHITE);
  drawIndicatorAt(ICON_MQTT_X, mqtt, ST77XX_YELLOW);
  // Right cluster (keyboard input state): BT puis indicateur CapsLock 'A'/'a', séparés des chips réseau par le spacer de 50 px défini dans ICON_BT_X.
  drawIndicatorAt(ICON_BT_X, bt, ST77XX_BLUE);
  drawCapsAt(ICON_CAPS_X, caps, ST77XX_WHITE);
  // Contact chip: hardcoded ON for now (see TODO above). Silhouette de personnage plutôt qu'un disque pour la distinguer des indicateurs réseau.
  drawPersonAt(ICON_CONTACT_X, contact, ST77XX_RED);
  // Separator hairline, one pixel above the bottom of the bar — the very
  // bottom row stays black to give the icons breathing room.
  g_disp->drawFastHLine(0, STATUS_BAR_H - 2, FB_WIDTH, STATUS_BAR_SEPARATOR_COLOR);

  g_lastDrawnBt = bt;
  g_lastDrawnWifi = wifi;
  g_lastDrawnMqtt = mqtt;
  g_lastDrawnCaps = caps;
  g_lastDrawnContact = contact;
  g_statusBarDirty = false;
}


// === Input feedback footer (BFA) ===
// Shows the current `g_currentMsgFromKeyboard` being typed via the BT keyboard, with the
// yellow cursor bar tracking g_msgCursorIdx (movable via arrow keys). Repainted
// on every keystroke (insert / delete / move / send).
void redrawInputFooter() {
  if (!g_inConversationMode) return;
  if (g_displayType != DisplayType::ST7789) return;

  // Wipe the whole footer strip.
  g_disp->fillRect(0, FOOTER_Y_FB, FB_WIDTH, FOOTER_H, ST77XX_BLACK);

  // Footer vertical layout (19 px total, rows FOOTER_Y_FB..FOOTER_Y_FB+18):
  //   +0       : 1 px black aération against the scroll area above
  //   +1       : white hairline separator (light gray, matches upper bar)
  //   +2       : 1 px black margin
  //   +3..+18  : 16 px text zone (size-2 default font) + yellow cursor bar
  g_disp->drawFastHLine(0, FOOTER_Y_FB + 1, FB_WIDTH, STATUS_BAR_SEPARATOR_COLOR);

  // Typed text, default 5×7 font at size 2 → 12 px per char, fits ~18 chars.
  // Right-aligned: the rightmost glyph of the viewport is pinned 2 px to the
  // left of the screen edge, and the text grows leftward as the user types.
  const int kCharWidth = 12;
  const int kInsideX = 6;
  const int kRightEdgeX = FB_WIDTH - 8;
  const int kTextAreaW = kRightEdgeX - kInsideX - 2;
  const int kMaxChars = kTextAreaW / kCharWidth;  // 18
  const char* full = g_currentMsgFromKeyboard.c_str();
  const int len = (int)g_currentMsgFromKeyboard.length();
  const int cur = (int)g_msgCursorIdx;

  // Viewport [viewStart, viewEnd) — at most kMaxChars chars, always contains
  // the cursor. Anchored to the message end by default; if the cursor is
  // further to the right than that window would allow (which only matters
  // when len <= kMaxChars but cur could equal len), the math degenerates to
  // showing the whole message.
  int viewEnd = cur;
  const int defaultEnd = (len > kMaxChars) ? kMaxChars : len;
  if (viewEnd < defaultEnd) viewEnd = defaultEnd;
  if (viewEnd > len) viewEnd = len;
  const int viewStart = (viewEnd > kMaxChars) ? (viewEnd - kMaxChars) : 0;
  const int visibleLen = viewEnd - viewStart;
  const char* shown = full + viewStart;
  const int textStartX = kRightEdgeX - 2 - visibleLen * kCharWidth;

  g_disp->setFont(NULL);
  g_disp->setTextSize(2);
  g_disp->setTextColor(ST77XX_WHITE);
  g_disp->setCursor(textStartX, FOOTER_Y_FB + 3);
  g_disp->print(shown);

  // Yellow cursor bar, drawn at the insertion-point gap (1 px wide, slightly shorter than the text height so it never visually touches the
  // white hairline separator just above. When the cursor sits at the end of the visible window it lands in the 2 px right-edge gap; when in
  // the middle it falls in the inter-character spacing of the previous glyph.
  const int cursorOffset = cur - viewStart;  // 0..visibleLen
  const int yellowX = textStartX + cursorOffset * kCharWidth - 1;
  g_disp->drawFastVLine(yellowX, FOOTER_Y_FB + 5, 14, ST77XX_YELLOW);
}


void setupDisplay() {
  if (g_displayType == DisplayType::ST7789) {
    Adafruit_ST7789* pDisp = new Adafruit_ST7789(TFT_CS, TFT_DC, TFT_RST);

    pDisp->init(240, 320);
    // Portrait. Hardware scroll operates in framebuffer-native (portrait)
    // coordinates; using setRotation(1) would make the scroll go sideways
    // from the user's POV. We use rotation 2 (180° flip vs rotation 0) so
    // that GFX's framebuffer-bottom matches the user's visual bottom on this
    // specific module — without this the chat scroll would feel inverted
    // (new lines at top, scrolling down). See docs/howto_hardware_scrolling.md.
    pDisp->setRotation(2);

    g_disp = pDisp;

    // Declare the scroll area (idempotent, sent only once).
    hwScrollSetupArea();
    hwScrollTo(0);
  } else {
    ESP_LOGW(TAG_MM, "setupDisplay: DISPLAY_TYPE_NOT_CONFIGURED");
  }

#if TFT_BL >= 0
  pinMode(TFT_BL, OUTPUT);
  analogWrite(TFT_BL, 255);  // full brightness at boot
#endif
  g_lastActivityMs = millis();
}


// Apply a power state to the panel. Idempotent.
void setDisplayPowerState(DisplayPowerState nextState) {
  if (nextState == g_displayPowerState) return;

  ESP_LOGI(TAG_MM, "setDisplayPowerState(%d -> %d)", (int)g_displayPowerState, (int)nextState);

  if (g_displayType == DisplayType::ST7789) {
    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    switch (nextState) {
      case DISPLAY_ON:
        pDisp->enableDisplay(true);
#if TFT_BL >= 0
        analogWrite(TFT_BL, 255);
#endif
        break;

      case DISPLAY_DIMMED:
#if TFT_BL >= 0
        analogWrite(TFT_BL, 128);  // 50% backlight
#endif
        // No panel-level dim command on ST7789 (the controller doesn't expose
        // a contrast register). Without a PWM backlight pin this transition
        // is silent — only the timer keeps progressing toward DISPLAY_OFF.
        break;

      case DISPLAY_OFF:
#if TFT_BL >= 0
        analogWrite(TFT_BL, 0);
#endif
        pDisp->enableDisplay(false);  // controller stops driving the matrix
        break;
    }
  }

  g_displayPowerState = nextState;
}


// Reset the idle timer. If the screen was dim or off, restore it to ON and
// return true so callers can swallow the input that caused the wake.
bool noteUserActivity() {
  g_lastActivityMs = millis();
  if (g_displayPowerState != DISPLAY_ON) {
    setDisplayPowerState(DISPLAY_ON);
    return true;  // caller should treat this as a wake event, not a real input
  }
  return false;
}


// Drive the dim/off state machine. Call from loop().
void updateDisplayPowerState() {
  unsigned long idleMs = millis() - g_lastActivityMs;

  if (g_displayPowerState == DISPLAY_ON && idleMs >= DISPLAY_IDLE_BEFORE_DIM_MS) {
    setDisplayPowerState(DISPLAY_DIMMED);
  } else if (g_displayPowerState == DISPLAY_DIMMED && idleMs >= DISPLAY_IDLE_BEFORE_OFF_MS) {
    setDisplayPowerState(DISPLAY_OFF);
  }
}


void showSplashScreen() {
  // Show image buffer on the display hardware.
  // Since the buffer is intialized with an Adafruit splashscreen internally, this will display the splashscreen.
  int duration = 1000;

  if (g_displayType == DisplayType::ST7789) {
    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    g_inConversationMode = false;  // fullscreen mode, suppress status bar repaint
    hwScrollReset();               // ensure we draw at framebuffer Y = screen Y = 0
    pDisp->print("MiniMessenger !");

    // Center the 16×16 splash bitmap on the panel. drawBitmap() paints monochrome pixels in the given foreground color where the bit is 1 and leaves
    // the existing background untouched where the bit is 0 — no need to pre-fill a rectangle.
    pDisp->drawBitmap((FB_WIDTH - 16) / 2, (FB_HEIGHT - 16) / 2, logo16_glcd_bmp, 16, 16, ST77XX_WHITE);

    duration = 1000;
  } else {
    ESP_LOGW(TAG_MM, "Display: no splash screen (display not configured)");
    duration = 0;
  }

  delay(duration);
}


// Replay every entry of the ring buffer through the same HW-scroll draw
// algorithm as addConversationBlock. After this:
//   - status bar and footer are untouched (protected by VSCRDEF — we only
//     fillRect the scroll area, never fillScreen)
//   - the latest block ends up at the bottom of the scroll area with older
//     blocks stacked above (or scrolled off the top if cumulated height
//     exceeds SCROLL_AREA_H) — visually identical to live message arrival
//   - g_drawY / g_scrollY are left in the "next slot" position so a new
//     addConversationBlock right after lands naturally below the last block
//
// Triggered by the `cmd redraw` command (see processPayloadAsCommand).
// We draw directly from the stored TextLine fields — no re-bound, no
// re-utf8-conversion, no re-alignment compute, no ring rewrite. Everything
// needed was captured at original send time.
void redrawAllConversations() {
  if (g_displayType != DisplayType::ST7789) {
    ESP_LOGW(TAG_MM, "redrawAllConversations: DISPLAY_TYPE_NOT_CONFIGURED");
    return;
  }
  ESP_LOGI(TAG_MM, "Full redraw — replaying %d block(s) from ring", g_lineCount);

  // Reset HW scroll state and wipe ONLY the scroll area.
  g_drawY = 0;
  g_scrollY = 0;
  hwScrollTo(0);
  g_disp->fillRect(0, SCROLL_AREA_Y_FB, FB_WIDTH, SCROLL_AREA_H, ST77XX_BLACK);

  for (int k = 0; k < g_lineCount; k++) {
    const TextLine& line = lines[(g_lineHead + k) % MAX_LINES];
    uint16_t H = line.tsHeightWithBottomMargin + line.msgHeightWithBottomMargin;

    // Wrap avoidance, mirroring addConversationBlock: if the block would
    // cross the scroll-area top boundary, skip the remaining tail and
    // restart at scroll-offset 0, bumping the scroll register to swallow
    // the skipped pixels.
    if (g_drawY + H > SCROLL_AREA_H) {
      uint16_t skipped = SCROLL_AREA_H - g_drawY;
      g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, skipped, ST77XX_BLACK);
      g_drawY = 0;
      g_scrollY = (g_scrollY + skipped) % SCROLL_AREA_H;
    }

    g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, H, ST77XX_BLACK);

    uint16_t fbY = g_drawY + SCROLL_AREA_Y_FB;
    if (line.ts[0] != '\0') {
      g_disp->setFont(NULL);
      g_disp->setTextSize(line.tsFontSize);
      g_disp->setTextColor(line.tsColor);
      g_disp->setCursor(line.tsX - line.tsBounds[BOX_X], fbY - line.tsBounds[BOX_Y]);
      g_disp->print(line.ts);
      fbY += line.tsHeightWithBottomMargin;
    }
    g_disp->setFont(&CONVO_MSG_FONT);
    g_disp->setTextSize(line.msgFontSize);
    g_disp->setTextColor(line.msgColor);
    g_disp->setCursor(line.msgX - line.msgBounds[BOX_X], fbY - line.msgBounds[BOX_Y]);
    g_disp->print(line.msg);

    g_drawY = (g_drawY + H) % SCROLL_AREA_H;
    g_scrollY = (g_scrollY + H) % SCROLL_AREA_H;
    hwScrollTo(g_scrollY);
  }
}


// Convert in-place from UTF-8 to Latin-1 (ISO-8859-1). Two-byte UTF-8
// sequences `0xC2 0xXX` (control / Latin-1 supplement) and `0xC3 0xXX`
// (most accented letters) collapse to a single Latin-1 byte. Codepoints
// outside U+0000..U+00FF are replaced with '?'. Returns the new length.
size_t utf8ToLatin1(char* s) {
  uint8_t* in = (uint8_t*)s;
  uint8_t* out = (uint8_t*)s;
  while (*in) {
    uint8_t b = *in++;
    if (b < 0x80) {
      *out++ = b;  // ASCII passthrough
    } else if ((b & 0xE0) == 0xC0 && *in) {
      uint8_t b2 = *in++;
      uint32_t cp = ((b & 0x1F) << 6) | (b2 & 0x3F);
      *out++ = (cp <= 0xFF) ? (uint8_t)cp : '?';
    } else if ((b & 0xF0) == 0xE0 && in[0] && in[1]) {
      in += 2;  // BMP > U+00FF
      *out++ = '?';
    } else if ((b & 0xF8) == 0xF0 && in[0] && in[1] && in[2]) {
      in += 3;  // outside BMP
      *out++ = '?';
    } else {
      *out++ = '?';  // malformed
    }
  }
  *out = '\0';
  return out - (uint8_t*)s;
}

void addConversationBlock(String ts, String msg, uint16_t msgColor, Align align) {
  // Any new block on screen counts as activity — wakes the panel if it was off.
  noteUserActivity();

  //   Adapt the message right after the noteUserActivity() call:
  char msgBuf[CONVO_MSG_MAX_LEN];
  strncpy(msgBuf, msg.c_str(), sizeof(msgBuf) - 1);
  msgBuf[sizeof(msgBuf) - 1] = '\0';
  utf8ToLatin1(msgBuf);
  // Then use msgBuf everywhere instead of msg.c_str() for the on-screen draw.

  // Timestamp clustering: if a timestamp was drawn less than
  // CONVO_TS_HIDE_THRESHOLD_S ago, drop this one to declutter. Only "real"
  // timestamps (non-empty ts) update the tracker — status lines like
  // "Lost server" / "Ready !" pass ts="" and don't reset the window.
  if (!ts.isEmpty()) {
    time_t now = time(nullptr);
    if (now - g_lastShownTsEpoch < CONVO_TS_HIDE_THRESHOLD_S) {
      ts = "";  // suppress the timestamp; the rest of the function handles it
    }
    // Reset dans tous les cas, on compare chaque message à la date de son précédent (meme si TS pas affiché)
    g_lastShownTsEpoch = now;
  }

  // Dimension TS
  uint16_t tsBlockHWithMargin = 0;

  static int16_t tsBox[4] = { 0, 0, 0, 0 };  // x1, y1, w, h

  /*
1. Pourquoi getTextBounds retourne des valeurs de y négatives avec certaines polices comme FreeSans9pt8b ?
Dans les bibliothèques graphiques comme Adafruit_GFX, le système de coordonnées pour le texte est basé sur le point de base (baseline) du texte. Voici ce qui se passe :


Origine du texte :
Le point (0, 0) pour le texte est généralement placé sur la ligne de base (baseline) du texte, c'est-à-dire la ligne sur laquelle reposent les lettres (sans les descendantes comme "j", "p", "g", etc.).

Valeurs négatives de y :
Pour les polices avec des ascendantes (parties des lettres qui montent au-dessus de la ligne de base, comme "h", "b", "d"), la coordonnée y du rectangle englobant (getTextBounds) peut être négative. Cela signifie que la partie supérieure du texte s'étend au-dessus de la ligne de base.

Exemple : Si la police a une hauteur de 9 pixels et que la ligne de base est à y=0, le sommet des ascendantes pourrait être à y=-2 (selon la police).

Polices comme FreeSans9pt8b :
Ces polices sont souvent conçues avec des ascendantes et descendantes importantes, ce qui explique pourquoi getTextBounds peut retourner des valeurs de y négatives.


Dans la méthode getTextBounds de la bibliothèque Adafruit_GFX, les paramètres retournés sont généralement les suivants :

x : Coordonnée horizontale du coin supérieur gauche du rectangle englobant.
y : Coordonnée verticale du coin supérieur gauche du rectangle englobant (peut être négative si le texte dépasse au-dessus de la ligne de base).
w : Largeur du rectangle englobant.
h : Hauteur totale du rectangle englobant, c'est-à-dire la distance entre le point le plus haut (ascendantes) et le point le plus bas (descendantes) du texte.
Pas besoin d'ajouter l'opposé de y : h est déjà calculé comme la distance entre le point le plus haut (même s'il est au-dessus de la ligne de base, donc y négatif) et le point le plus bas.
*/

  if (!ts.isEmpty()) {
    g_disp->setFont(NULL);
    g_disp->setTextSize(CONVO_TS_FONT_SIZE);
    g_disp->getTextBounds(ts, 0, 0, &tsBox[BOX_X], &tsBox[BOX_Y], (uint16_t*)&tsBox[BOX_W], (uint16_t*)&tsBox[BOX_H]);

    tsBlockHWithMargin = tsBox[BOX_H] + CONVO_TS_MARGIN_BOTTOM;
  }

  // Dimension msg
  uint16_t msgBlockHWithMargin = 0;
  static int16_t msgBox[4] = { 0, 0, 0, 0 };

  g_disp->setFont(&CONVO_MSG_FONT);
  g_disp->setTextSize(CONVO_MSG_FONT_SIZE);
  g_disp->getTextBounds(msgBuf, 0, 0, &msgBox[BOX_X], &msgBox[BOX_Y], (uint16_t*)&msgBox[BOX_W], (uint16_t*)&msgBox[BOX_H]);
  msgBlockHWithMargin = msgBox[BOX_H] + CONVO_MSG_MARGIN_BOTTOM;


  uint16_t H = tsBlockHWithMargin + msgBlockHWithMargin;

  // Compute X alignment in screen-space (g_disp->width() reflects rotation 0
  // → 240 px, so this works directly in framebuffer coords too).
  uint16_t tsX = 0, msgX = 0;
  if (align == RIGHT) {
    tsX = g_disp->width() - tsBox[BOX_W];
    msgX = g_disp->width() - msgBox[BOX_W];
  } else if (align == CENTER) {
    tsX = (g_disp->width() - tsBox[BOX_W]) / 2;
    msgX = (g_disp->width() - msgBox[BOX_W]) / 2;
  }

  // === Maintain the logical ring buffer (state only — not used for drawing) ===
  while (g_lineCount >= MAX_LINES) {
    g_lineHead = (g_lineHead + 1) % MAX_LINES;
    g_lineCount--;
  }
  int writeIdx = (g_lineHead + g_lineCount) % MAX_LINES;
  lines[writeIdx] = TextLine(ts, CONV0_TS_COLOR, NULL, CONVO_TS_FONT_SIZE, tsBlockHWithMargin, tsX, tsBox,
                             msgBuf, msgColor, &CONVO_MSG_FONT, CONVO_MSG_FONT_SIZE, msgBlockHWithMargin, msgX, msgBox);
  g_lineCount++;

  // === HW scroll draw path: write the block directly into the framebuffer
  // ring, then bump VSCSAD by H. Old content scrolls off the top as the
  // controller re-maps the visible window — no full redraw. ===

  // Wrap avoidance: if the block would cross the scroll-area top boundary,
  // skip the remaining tail and restart at scroll-offset 0. The skipped tail
  // is wiped (otherwise stale content from a previous wrap would scroll back
  // into view), and the same number of pixels is added to the scroll so the
  // user perceives a single (slightly bigger than H) smooth scroll.
  // NOTE: `g_drawY` and `g_scrollY` are offsets INSIDE the scroll area
  // ([0, SCROLL_AREA_H)). All fillRect / setCursor positions are absolute
  // framebuffer Y, so we add SCROLL_AREA_Y_FB (= STATUS_BAR_H) at draw time.
  if (g_drawY + H > SCROLL_AREA_H) {
    uint16_t skipped = SCROLL_AREA_H - g_drawY;
    g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, skipped, ST77XX_BLACK);
    g_drawY = 0;
    g_scrollY = (g_scrollY + skipped) % SCROLL_AREA_H;
  }

  // Wipe the strip we're about to overdraw (stale content from the previous
  // wrap of the framebuffer ring).
  g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, H, ST77XX_BLACK);

  // Draw TS then MSG at framebuffer Y = g_drawY + SCROLL_AREA_Y_FB.
  // getTextBounds returns negative tsBox/msgBox y for ascender-using fonts,
  // so we offset the cursor by `- bounds[BOX_Y]` (cf. the big French comment
  // above).
  uint16_t fbY = g_drawY + SCROLL_AREA_Y_FB;
  if (!ts.isEmpty()) {
    g_disp->setFont(NULL);
    g_disp->setTextSize(CONVO_TS_FONT_SIZE);
    g_disp->setTextColor(CONV0_TS_COLOR);
    g_disp->setCursor(tsX - tsBox[BOX_X], fbY - tsBox[BOX_Y]);
    g_disp->print(ts);
    fbY += tsBlockHWithMargin;
  }
  g_disp->setFont(&CONVO_MSG_FONT);
  g_disp->setTextSize(CONVO_MSG_FONT_SIZE);
  g_disp->setTextColor(msgColor);
  g_disp->setCursor(msgX - msgBox[BOX_X], fbY - msgBox[BOX_Y]);
  g_disp->print(msgBuf);

  // Bump scroll-area cursor and the user-visible scroll register.
  g_drawY = (g_drawY + H) % SCROLL_AREA_H;
  g_scrollY = (g_scrollY + H) % SCROLL_AREA_H;
  hwScrollTo(g_scrollY);
}


// ================================================================================
// Messaging
// ================================================================================

void setRecipient(int recipientDeviceId) {
  snprintf(g_mqttOutoingRecipientTopic, MQTT_TOPIC_SIZE,
           "msg/unicast/%d",
           recipientDeviceId);
  ESP_LOGI(TAG_MQTT, "Setting recipient topic to [%s]", g_mqttOutoingRecipientTopic);
}

// Called once per successful MQTT (re)connect. Two distinct cases:
//   - first connect after boot: we were sitting on the info screen waiting for MQTT to come up. Transition to conversation mode via goAndResetConversationScreen
//     (which wipes the scroll area and paints the status bar + footer borders), then drop a "Ready !" line in the conversation.
//   - any later reconnect (we lost connection mid-conversation and got it back): we stay in conversation mode — the "Lost server" / "Trying to
//     reconnect..." stack is still visible — and just append "Ready !" so the reconnect is acknowledged in-line.
void onMQTTReconnected() {
  if (!g_inConversationMode) {
    goAndResetConversationScreen();
  }
  addConversationBlock("", "Ready !", CONVO_INFO_COLOR, CENTER);
}

// ----------------------------------------------------------------------------
// Local commands + message funnel
//
// routeMessage() is the SINGLE insertion point for any complete payload
// landing in this device, whether it arrived over MQTT (REMOTE) or was just
// composed locally on the serial monitor (LOCAL). Both channels converge here
// so the same three steps happen exactly once:
//
//   1. Wake the screen via noteUserActivity() — every payload is a real
//      user-initiated event and must be visible, regardless of dim/off state.
//   2. Try to interpret the payload as a local command (CMD_* below).
//      Commands run locally and are NEITHER displayed in the conversation
//      NOR republished to peers, so an MQTT 'cmd wifi' cleanly disconnects
//      the recipient without polluting anyone's screen, and a serial 'cmd
//      bonds' wipes BLE bonds without leaking that string to other devices.
//   3. Otherwise route to display: LEFT for REMOTE, RIGHT for LOCAL — and
//      for LOCAL, also publish to peers over MQTT so they receive the text.
//
// Why ONE funnel rather than scattering the wake / interpret logic across
// each channel's handler: it keeps the command vocabulary in one place,
// and any future channel (BLE keyboard Enter, web UI, etc.) just has to
// call routeMessage() with the right source to inherit all three steps.
// ----------------------------------------------------------------------------

const char* const CMD_DISCONNECT_WIFI = "/wifi";
const char* const CMD_DISCONNECT_MQTT = "/mqtt";
const char* const CMD_BT_CLEAN        = "/bt-clean";
const char* const CMD_REDRAW          = "/redraw";
const char* const CMD_HELP            = "/help";
const char* const CMD_STATUS          = "/status";
// WiFi config commands — match the verbs in wifi.ino. /wifi-forget takes an SSID argument so it's matched via startsWith() rather than equality.
const char* const CMD_WIFI_CLEAN      = "/wifi-clean";
const char* const CMD_WIFI_LIST       = "/wifi-list";
const char* const CMD_WIFI_FORGET     = "/wifi-forget";   // payload: "/wifi-forget <ssid>"
const char* const CMD_WIFI_PORTAL     = "/wifi-portal";

bool processPayloadAsCommand(const String& message) {
  if (message == CMD_DISCONNECT_WIFI) {
    ESP_LOGI(TAG_MM, "Command [%s] — disconnecting WiFi", CMD_DISCONNECT_WIFI);
    WiFi.disconnect();
    return true;
  }

  if (message == CMD_DISCONNECT_MQTT) {
    ESP_LOGI(TAG_MM, "Command [%s] — disconnecting MQTT", CMD_DISCONNECT_MQTT);
    g_mqttClient.disconnect();
    return true;
  }

  if (message == CMD_BT_CLEAN) {
    // Going through NimBLEDevice directly (rather than the keyboard wrapper's protected clearAllExistingBonds()) keeps mm_blekb's API surface
    // intact. Renamed from /bonds to /bt-clean for symmetry with /wifi-clean.
    ESP_LOGI(TAG_MM, "Command [%s] — clearing all BLE bonds", CMD_BT_CLEAN);
    NimBLEDevice::deleteAllBonds();
    return true;
  }

  if (message == CMD_WIFI_CLEAN) {
    // Wipes the entire NVS WiFi namespace. On the next boot the compile-time defaults in compiled_wifi.h re-seed (if any); otherwise the device
    // boots straight into the captive portal. The current STA connection survives this call — only future boots are affected.
    ESP_LOGI(TAG_MM, "Command [%s] — clearing NVS WiFi list", CMD_WIFI_CLEAN);
    wifiClearNvs();
    addConversationBlock("", "NVS WiFi cleared — reboot to re-seed", CONVO_CMD_COLOR, LEFT);
    return true;
  }

  if (message == CMD_WIFI_LIST) {
    // Prints each saved SSID into the conversation in pink. Handy when the user wants to see what's in NVS without rebooting / opening serial.
    ESP_LOGI(TAG_MM, "Command [%s] — listing saved WiFi networks", CMD_WIFI_LIST);
    wifiPrintListToConversation();
    return true;
  }

  if (message.startsWith(String(CMD_WIFI_FORGET) + " ")) {
    // Parse the SSID argument: anything after the first space. We use startsWith with a trailing space so "/wifi-forget-x" doesn't match.
    String ssid = message.substring(strlen(CMD_WIFI_FORGET) + 1);
    ssid.trim();
    ESP_LOGI(TAG_MM, "Command [%s] — forgetting SSID [%s]", CMD_WIFI_FORGET, ssid.c_str());
    if (ssid.length() == 0) {
      addConversationBlock("", "Usage: /wifi-forget <ssid>", CONVO_ERROR_COLOR, LEFT);
    } else if (wifiForgetFromNvs(ssid.c_str())) {
      addConversationBlock("", String("Forgot: ") + ssid, CONVO_CMD_COLOR, LEFT);
    } else {
      addConversationBlock("", String("Not found: ") + ssid, CONVO_ERROR_COLOR, LEFT);
    }
    return true;
  }

  if (message == CMD_WIFI_PORTAL) {
    // Force the captive portal open right now — useful to add a new network without waiting for the current connection to fail.
    ESP_LOGI(TAG_MM, "Command [%s] — forcing portal", CMD_WIFI_PORTAL);
    wifiForcePortal();
    return true;
  }

  if (message == CMD_REDRAW) {
    // Full repaint: status bar + footer + scroll area refilled from the ring buffer. Same path as the auto-revert from "/status" so a user
    // who lost faith in the screen state always has one single recovery command. Useful after visual glitches or framebuffer/state drift.
    ESP_LOGI(TAG_MM, "Command [%s] — full redraw of the 3 zones", CMD_REDRAW);
    returnToConversationsScreen();
    return true;
  }

  if (message == CMD_STATUS) {
    // Switch to the info screen for STATUS_SCREEN_DURATION_MS, then auto-revert. The timer is honored by loop() (non-blocking, so MQTT/BLE keep
    // running). Re-issuing "/status" during the overlay just resets the timer; "/redraw" cancels it explicitly via returnToNominalScreen.
    ESP_LOGI(TAG_MM, "Command [%s] — info screen overlay for %ums", CMD_STATUS, (unsigned)STATUS_SCREEN_DURATION_MS);
    showUpdatedInfoScreen();
    g_statusScreenEndMs = millis() + STATUS_SCREEN_DURATION_MS;
    return true;
  }

  if (message == CMD_HELP) {
    // Lists the available command vocabulary in the conversation, left-aligned and pink so it stands out from normal traffic. One block per row keeps
    // each entry on its own line in the scroll area; the leading two spaces inside each string give the description column some breathing room.
    ESP_LOGI(TAG_MM, "Command [%s] — listing commands", CMD_HELP);
    addConversationBlock("", "Commands:",                  CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "help          list cmds",    CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "status        info screen",  CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "redraw        full repaint", CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "mqtt          drop MQTT",    CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "bt-clean      clear bonds",  CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "wifi          drop WiFi",    CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "wifi-clean    wipe NVS",     CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "wifi-list     known nets",   CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "wifi-forget <ssid>",         CONVO_CMD_COLOR, LEFT);
    addConversationBlock("", "wifi-portal   open portal",  CONVO_CMD_COLOR, LEFT);
    return true;
  }
  return false;
}

void routeMessage(const String& message, MessageSource source) {
  // Step 1 — always wake the screen. We ignore noteUserActivity()'s "was sleeping"
  // return value: unlike a stray keypress (which is swallowed on wake to avoid
  // typing accidental characters), a command-or-message must actually run on
  // wake-up too.
  noteUserActivity();

  // Step 2 — if it's a known command, execute and stop. No display, no
  // republish — this is the whole point of the funnel.
  if (processPayloadAsCommand(message)) return;

  // Step 3 — render in the conversation; for LOCAL, also publish so peers see it.
  if (source == MessageSource::REMOTE) {
    addConversationBlock(getCurrentTime(), message, ST77XX_YELLOW, LEFT);
  }
  // LOCAL (serial ou BT)
  else {
    addConversationBlock(getCurrentTime(), message, ST77XX_WHITE, RIGHT);
    bool published = mqttPushFormattedMessage(g_mqttOutoingRecipientTopic, message.c_str());
    if (!published) {
      // Naive WhatsApp-style "send failed" indicator: append a second block right under the original one, in error red, prefixed with [ERROR] so
      // the user knows that specific message didn't reach the broker. To be replaced later with a per-message status icon (sending / sent / failed)
      // overlaid on the original block — but the present block-pair is enough to surface the failure without any new UI machinery.
      addConversationBlock("", "[ERROR] " + message, CONVO_ERROR_COLOR, RIGHT);
    }
  }
}




// ================================================================================
// Entrypoints
// ================================================================================

void goAndResetConversationScreen() {
  if (g_displayType == DisplayType::ST7789) {
    // hwScrollReset() wipes the entire framebuffer (status bar / footer
    // included). Right after, we mark conversation mode and repaint the
    // status bar + the empty input footer.
    hwScrollReset();
    g_inConversationMode = true;
    redrawStatusBar();
    redrawInputFooter();
  } else {
    ESP_LOGW(TAG_MM, "goAndResetConversationScreen: DISPLAY_TYPE_NOT_CONFIGURED");
  }
}

// Returns to the nominal 3-zone screen (upper status bar + scroll area + footer) and repaints all three from their in-memory state. Called by
// "/redraw" and by the "/status" timeout in loop(). Also clears g_statusScreenEndMs so a pending timeout doesn't fire a redundant revert
// when the user triggers a manual redraw mid-overlay.
void returnToConversationsScreen() {
  g_statusScreenEndMs = 0;
  goAndResetConversationScreen();  // HW scroll reset + repaint of status bar + footer
  redrawAllConversations();        // refill the scroll area from the ring buffer
}

// Print `value` at (x, y) wrapping to a second line at (x, y + lineH) if it doesn't fit in `availableWidth`. Both lines start at the same x.
// Returns the total vertical pixels consumed (lineH for a single line, 2*lineH if wrapped).
//
// Uses the default 5×7 font at setTextSize(2) → 12 px advance per glyph. The split prefers the rightmost natural separator
// (':', '.', '-', '_', '/', ' ') that keeps the first half within the line, so the cut feels meaningful (e.g. a MAC splits cleanly on a colon).
// Falls back to a hard cut at maxChars when no separator is present. A leading space on the second half is trimmed so the two lines align on x.
static int printValueWrapped(Adafruit_ST7789* pDisp, const String& value, int x, int y, int availableWidth, int lineH) {
  const int charW = 12;
  int len = value.length();
  pDisp->setCursor(x, y);
  if (len * charW <= availableWidth) {
    pDisp->print(value);
    return lineH;
  }
  int maxChars = availableWidth / charW;
  int upperBound = (maxChars - 1 < len - 1) ? (maxChars - 1) : (len - 1);
  int breakAt = -1;
  for (int i = upperBound; i > 0; i--) {
    char c = value[i];
    if (c == ':' || c == '.' || c == '-' || c == '_' || c == '/' || c == ' ') {
      breakAt = i + 1;  // first half keeps the separator for visual continuity
      break;
    }
  }
  if (breakAt < 1) breakAt = maxChars;  // hard cut fallback
  String first = value.substring(0, breakAt);
  String second = value.substring(breakAt);
  while (second.length() > 0 && second[0] == ' ') second.remove(0, 1);
  pDisp->print(first);
  pDisp->setCursor(x, y + lineH);
  pDisp->print(second);
  return 2 * lineH;
}

// Draw one info-screen row: red header at colHeaders, white value at colValues (wrapped to a 2nd line via printValueWrapped if too wide).
// Returns the row height consumed (lineHeight or 2 × lineHeight when the value wrapped) so the caller can advance nextY accordingly.
static int drawInfoRow(Adafruit_ST7789* pDisp, const char* header, const String& value,
                       int colHeaders, int colValues, int nextY, int lineHeight) {
  pDisp->setTextSize(2);
  pDisp->setCursor(colHeaders, nextY);
  pDisp->setTextColor(ST77XX_RED);
  pDisp->print(header);
  pDisp->setTextColor(ST77XX_WHITE);
  return printValueWrapped(pDisp, value, colValues, nextY, FB_WIDTH - colValues, lineHeight);
}

void showUpdatedInfoScreen() {
  String mac = WiFi.macAddress();

  if (g_displayType == DisplayType::ST7789) {

    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    g_inConversationMode = false;  // fullscreen mode, suppress status bar repaint
    hwScrollReset();               // info screen draws at fixed coordinates, scroll must be 0

    pDisp->setFont(NULL);  // font par défaut

    int colHeaders = 2;
    int colValues = 68;
    int lineHeight = 22;

    int nextY = 0;

    // Top rows: device identity — always shown regardless of WiFi state since these don't depend on the network being up.
    nextY += drawInfoRow(pDisp, "ID:", String(g_deviceIdMe), colHeaders, colValues, nextY, lineHeight);
    nextY += drawInfoRow(pDisp, "Name:", String(g_deviceName), colHeaders, colValues, nextY, lineHeight);
    nextY += drawInfoRow(pDisp, "MAC:", mac, colHeaders, colValues, nextY, lineHeight);
    nextY += drawInfoRow(pDisp, "BTKB:", g_kb.isFullyConnected() ? "Connected" : "Not found",
                         colHeaders, colValues, nextY, lineHeight);

    // Branch on the current WiFi state — in PORTAL we replace the SSID/IP/MQTT/TIME rows with config instructions, otherwise we keep the
    // standard runtime info layout. The "Connecting…" / "Lost" variants reuse the SSID/IP rows with placeholder values so the row positions
    // stay stable across transitions (less visual jitter when state changes between two info-screen refreshes).
    WifiState st = wifiGetState();
    if (st == WifiState::PORTAL) {
      drawPortalInstructions(pDisp, nextY, colHeaders, colValues, lineHeight);
    } else {
      String ssidStr = (st == WifiState::CONNECTED) ? WiFi.SSID() : String("(searching)");
      String ipStr;
      if (WiFi.status() == WL_CONNECTED)       ipStr = WiFi.localIP().toString();
      else if (st == WifiState::TRYING_KNOWN)  ipStr = "Connecting...";
      else if (st == WifiState::LOST)          ipStr = "Lost, retrying";
      else                                     ipStr = "Booting...";
      nextY += drawInfoRow(pDisp, "SSID:", ssidStr, colHeaders, colValues, nextY, lineHeight);
      nextY += drawInfoRow(pDisp, "IP:",   ipStr,   colHeaders, colValues, nextY, lineHeight);
      nextY += drawInfoRow(pDisp, "MQTT:", g_mqttClient.connected() ? "OK" : "NOT OK",
                           colHeaders, colValues, nextY, lineHeight);
      nextY += drawInfoRow(pDisp, "TIME:", String(getTimezoneLabel()),
                           colHeaders, colValues, nextY, lineHeight);
    }

    nextY += lineHeight * 2;
    nextY += drawInfoRow(pDisp, "HELP:", "/help", colHeaders, colValues, nextY, lineHeight);

  } else {
    ESP_LOGW(TAG_MM, "showUpdatedInfoScreen: DISPLAY_TYPE_NOT_CONFIGURED");
  }
}


void setupTests() {
  // ==== Font default
  // lineAdvance : 8
  // Bounds for text [jjjjj]: x1=0, y1=0, w=30, h=8
  // Bounds for text [Abefg]: x1=0, y1=0, w=30, h=8
  // Bounds for text [     ]: x1=0, y1=0, w=30, h=8
  // Bounds for text [_____]: x1=0, y1=0, w=30, h=8
  // ==== Font FreeSans9pt8b
  // yAdvance : 22
  // lineAdvance : 22
  // Bounds for text [aaaaa]: x1=1, y1=-9, w=49, h=10
  // Bounds for text [ttttt]: x1=1, y1=-11, w=24, h=12
  // Bounds for text [jjjjj]: x1=0, y1=-12, w=20, h=17
  // Bounds for text [Abefg]: x1=0, y1=-12, w=46, h=17
  // Bounds for text [     ]: x1=0, y1=0, w=20, h=0
  // Bounds for text [_____]: x1=0, y1=3, w=50, h=1

  uint8_t textSize = 1;
  String texts[] = { "aaaaa", "AAAAA", "ttttt", "qqqqq", "Attqq", "     ", "_____" };
  String fontNames[] = { "default", "FreeSans9pt8b" };
  const GFXfont* fonts[] = { NULL, &CONVO_MSG_FONT };

  int16_t x1, y1;
  uint16_t w, h;

  for (int f = 0; f < 2; f++) {
    ESP_LOGD(TAG_MM, "==== Font %s", fontNames[f].c_str());
    const GFXfont* font = fonts[f];

    g_disp->setFont(font);
    g_disp->setTextSize(textSize);

    uint8_t yAdvance = 8;
    if (font != NULL) {
      yAdvance = pgm_read_byte(&font->yAdvance);
      ESP_LOGD(TAG_MM, "yAdvance: %u", yAdvance);
    }
    uint8_t lineAdvance = yAdvance * textSize;
    ESP_LOGD(TAG_MM, "lineAdvance: %u", lineAdvance);

    for (auto& text : texts) {
      g_disp->getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
      ESP_LOGD(TAG_MM, "Bounds for [%s]: x1=%d y1=%d w=%u h=%u",
               text.c_str(), x1, y1, w, h);
    }
  }

  //     g_disp->fillScreen(ST77XX_BLACK);
  //     g_disp->setFont(&CONVO_MSG_FONT);
  //         g_disp->setTextColor(ST77XX_YELLOW);
  //             g_disp->setTextSize(2);
  //       g_disp->setCursor(0,0);  // "- bound.y" = decale vers le bas qd .y est négatif (sinon=0)
  //       g_disp->print("Abbppgg");
  //g_disp->display();
  // delay(10000);
}

void setup() {
  Serial.begin(115200);
  delay(1000);
  delay(1000);

  // Si rien n'apparait après cette ligne: ArduinoIDE: Tools >> Core Debug Level : Verbose ; puis reflash
  Serial.println("Setup logging...");
  // Install per-tag log levels before anything else logs:
  //   default = INFO ; BTKB = DEBUG (HID keystrokes are debug-level).
  setupLogging();
  ESP_LOGI(TAG_MM, "setup()");
  ESP_LOGI(TAG_MM, "=== minimessenger build %s %s ===", __DATE__, __TIME__);


  // Initialise le générateur de nombres aléatoires
  // Utilise une broche non connectée pour varier la graine (seed)
  randomSeed(analogRead(A0));  // A0 est une broche non connectée (bruit analogique)

  identifyDevice();

  setupDisplay();
  setupLeds();

  //setupTests();

  showSplashScreen();
  showUpdatedInfoScreen();

  // Connect to BT
  setupKeyboard();

  // WiFi: full bringup — driver mode + hostname + NVS seed/load + WiFiManager config + state machine kick (TRYING_KNOWN or PORTAL). Non-blocking;
  // wifiTick() in loop() drives the actual association. The info screen polled every 2 s reflects each WifiState transition.
  setupWifi();

  // MQTT (server + callback registration) and TLS root CA — independent of the WiFi link being up, safe at any point after setupWifi().
  g_wifiClient.setCACert(g_hiveMQRootCA);
  g_mqttClient.setServer(mqtt_server, mqtt_port);
  g_mqttClient.setCallback(onMqttIncomingMessage);

  //g_mqttWasConnected = true;
  // Test blinking
  //g_mqttLastReconnectTryTimestampMs = millis();

  resetSerialBuffer();

  ESP_LOGI(TAG_MM, "setup() completed");
}

void resetSerialBuffer() {
  // Reset g_inNextCharIndex and clean buffer (then no need to add '\0' at end of current msg)
  g_inNextCharIndex = 0;
  for (int i = 0; i <= MAX_SERIAL_MSG_LENGTH; i++) {
    g_fullMsgFromSerial[i] = 0;
  }
}

bool g_firstLoop = true;

void loop() {
  unsigned long currentMillis = millis();  // Temps actuel en millisecondes depuis le démarrage

  g_kb.tryToMaintainConnection();

  // WiFi: drive the state machine in wifi.ino. Handles TRYING_KNOWN → CONNECTED / PORTAL transitions, portal HTTP traffic, rising/falling edge
  // banners, and the LOST → PORTAL fallback after extended outages. Non-blocking — BT keyboard and serial input keep running through outages.
  wifiTick(currentMillis);

  if (!g_mqttClient.connected()) {
    if (g_mqttWasConnected) {
      g_mqttWasConnected = false;
      ledSetState(LED_STATUS, LED_STATE_BLINK_FAST);

      // Only surface the MQTT-down banner when WiFi is actually up. If the link is down, the WiFi block above already showed "WiFi lost" and a
      // second "Lost server" banner is just noise about a known consequence. The internal flag flip + LED still happen regardless so the rising
      // edge logic and the status bar indicator stay accurate.
      if (WiFi.status() == WL_CONNECTED) {
        addConversationBlock("", "Lost server — Retrying...", CONVO_ERROR_COLOR, CENTER);
      }
    }

    // Time to try to reconnect ?
    if (g_firstLoop || currentMillis - g_mqttLastReconnectTryTimestampMs > MQTT_CONNECT_RETRY_INTERVAL) {
      // Arm the back-off gate BEFORE the attempt: a TLS handshake can block
      // up to ~30 s; starting the timer from the call's *end* would compound.
      g_mqttLastReconnectTryTimestampMs = currentMillis;

      if (mqttReconnect()) {
        onMQTTReconnected();
      }
      // On failure: no delay() — the time gate above throttles the next retry.
    }
  } else {
    g_mqttClient.loop();

    // MQTT: Send keep-alive
    if (currentMillis - g_mqttPreviousKeepAliveTimestampMs >= MQTT_KEEPALIVE_INTERVAL) {
      // Met à jour le temps de la dernière exécution
      g_mqttPreviousKeepAliveTimestampMs = currentMillis;

      // Send public liveness
      mqttSendAlive(2);
    }
  }



#ifdef FLAG_READ_SERIAL_INPUTS

  // Add a new char to the buffer
  while (Serial.available() > 0) {
    g_inChar = Serial.read();

    // Wake screen on any serial char. If we were sleeping, swallow this char:
    // the user typed it to light the screen, not to compose a message.
    if (noteUserActivity()) {
      continue;
    }

    // 'Enter key' : send message
    if (g_inChar == '\n') {
      if (g_inNextCharIndex > 0) {
        ESP_LOGI(TAG_MM, "Serial: read msg #%u: %s", g_mqttOutputMsgId, g_fullMsgFromSerial);
        // Hand the buffer to the common funnel: wakes the screen, intercepts
        // CMD_* commands locally, otherwise renders RIGHT + publishes via
        // MQTT. Don't inline displayLocalMessage + mqttPushFormattedMessage
        // here — that would skip command interception and force every serial
        // 'cmd ...' string to be echoed/published to peers.
        routeMessage(String(g_fullMsgFromSerial), MessageSource::LOCAL);
        resetSerialBuffer();
      } else {
        // Message is empty. Do nothing
        ESP_LOGD(TAG_MM, "Serial: empty message, skipping publish");
      }
    } else {
      // Too long ?
      if (g_inNextCharIndex >= MAX_SERIAL_MSG_LENGTH) {
        // Force reset all
        ESP_LOGW(TAG_MM, "Serial: msg too long, dropping it");
        resetSerialBuffer();
      } else {
        g_fullMsgFromSerial[g_inNextCharIndex] = g_inChar;
        g_inNextCharIndex++;
      }
    }
  }
#endif


  // Blinking leds management
  for (int pin = 0; pin < LED_QTY; pin++) {
    if (g_ledRequiredState[pin] == LED_STATE_BLINK_FAST) {
      if (currentMillis - g_ledBlinkLastTimestampMs[pin] > LED_BLINK_FAST_DURATION) {
        ledCommuteBlinkState(pin);
      }
    } else if (g_ledRequiredState[pin] == LED_STATE_BLINK_SLOW) {
      if (currentMillis - g_ledBlinkLastTimestampMs[pin] > LED_BLINK_SLOW_DURATION) {
        ledCommuteBlinkState(pin);
      }
    }
  }

  // Two mutually-exclusive periodic UI refreshes:
  //   - in conversation mode  →  status bar (BT/WiFi/MQTT/contact icons) every ~500 ms.
  //                              redrawStatusBar short-circuits internally if nothing changed since the last paint, so this is cheap on average.
  //   - in boot phase         →  full info screen repaint every ~2 s so that BTKB / WiFi / MQTT state transitions show up while the user waits
  //                              for everything to come online. Stops the moment onMQTTReconnected() flips into conversation mode.
  if (g_inConversationMode) {
    if (currentMillis - g_lastStatusBarPollMs >= STATUS_BAR_POLL_INTERVAL_MS) {
      g_lastStatusBarPollMs = currentMillis;
      redrawStatusBar();
    }
  } else {
    if (currentMillis - g_lastInfoScreenRefreshMs >= INFO_SCREEN_REFRESH_INTERVAL_MS) {
      g_lastInfoScreenRefreshMs = currentMillis;
      showUpdatedInfoScreen();
    }
  }

  // Auto-revert from the "/status" info-screen overlay back to the nominal 3-zone view after STATUS_SCREEN_DURATION_MS. Non-blocking so MQTT
  // and BLE keep running during the overlay; the same returnToNominalScreen() path is used by "/redraw" for consistency.
  if (g_statusScreenEndMs != 0 && currentMillis >= g_statusScreenEndMs) {
    returnToConversationsScreen();
  }

  // Burn-in protection: advance the dim → off state machine based on idle time.
  updateDisplayPowerState();

  g_firstLoop = false;

  // Short cooperative yield. delay(5) on ESP cores calls yield()/vTaskDelay()
  // internally, which lets the lwIP / BLE / Wi-Fi background tasks run and
  // feeds the watchdog. We keep some delay (rather than 0) so a tight loop
  // does not starve those background tasks on single-core paths or hog the CPU
  // for nothing — but we don't want it large because BLE scan, keystroke
  // dispatch, MQTT keepalive and the LED blink tick all live in this loop and
  // each extra millisecond shows up directly as input lag.
  delay(5);
}

void onMqttIncomingMessage(char* topic, byte* payload, unsigned int length) {
  String message;
  for (unsigned int i = 0; i < length; i++) {
    message += (char)payload[i];
  }
  message.trim();

  if (strcmp(topic, g_mqttOutgoingTopicLive) == 0) {
    int remoteDeviceId = atoi(message.c_str());
    onReceivedContactOnline(remoteDeviceId, true);
  } else if (strcmp(topic, g_mqttOutgoingTopicWill) == 0) {
    int remoteDeviceId = atoi(message.c_str());
    onReceivedContactOnline(remoteDeviceId, false);
  }
  // msg/unicast/<me> or msg/broadcast
  else if (topic[0] == 'm') {
    ESP_LOGI(TAG_MQTT, "Incoming message [%s]", message.c_str());
    // Route through the common funnel: wakes the screen, intercepts CMD_*
    // commands, otherwise renders LEFT.
    routeMessage(message, MessageSource::REMOTE);

  } else {
    ESP_LOGW(TAG_MQTT, "Message received in unknown topic [%s]: [%s]", topic, message.c_str());
  }
}

void onReceivedContactOnline(int remoteDeviceId, bool isLive) {
  if (remoteDeviceId == g_deviceIdMe) {
    return;
  }

  ESP_LOGI(TAG_MQTT, "Liveness device #%d isLive=%d", remoteDeviceId, isLive ? 1 : 0);
  if (remoteDeviceId == g_deviceIdFriend1) {
    ledSetState(LED_FRIEND_1, (isLive ? LED_STATE_ON : LED_STATE_OFF));
    //digitalWrite(LED_FRIEND_1, (isLive ? HIGH : LOW) );
  } else if (remoteDeviceId == g_deviceIdFriend2) {
    ledSetState(LED_FRIEND_2, (isLive ? LED_STATE_ON : LED_STATE_OFF));
    //digitalWrite(LED_FRIEND_2, (isLive ? HIGH : LOW) );
  }
}