/*
MiniMessenger avec
    - microcontroller   : ESP32 (wifi, BT)
    - périphériques     : Ecran STT7789v. Limitations de ce modèle alixp : pas de pin pour TFT_BL pour dimmer le backlight ; besoin de connecter CS (pas sur GND)
                          BT keyboard (qwerty)
    - internet services : MQTT HiveMQ freebroker

Santé du projet au 2020-06:
    ArduinoIDE :               2.3.8_Linux_64bit.AppImage
    Tools > Boards  :          ESP32 >> ESP32 Dev Module,
                               /dev/ttyUSB0, Baud 115200
    Tools > Partition Scheme : "Huge APP (3MB No OTA / 1MB SPIFFS)"
    Tools > Core Debug Level : "Verbose"  (flasher après tout changement - pour les libs systèmes, pas notre code qui a ses propres niveaux)

    COMPILE: OK
    LINK   : OK
    UPLOAD : OK
    RUN    : OK

Docs (/docs):
- layout des écrans : screens.md
- cablage : wiring.md
- Envois et formats des msgs MQTT, cf mqtt.h
- et tous les autres documents de /docs à lire
*/

// ================================================================================
// Librairies
// ================================================================================


// Provided by ESP32 boards
#include <WiFi.h>

// esp_read_mac(ESP_MAC_EFUSE_FACTORY) reads the silicon eFuse directly with no cache layer — works in setup() before any driver init. The
// related esp_efuse_mac_get_default() is a TRAP on arduino-esp32 3.3.8 (IDF 5.x): it wraps esp_read_mac(ESP_MAC_BASE) which queries a RAM cache
// populated late in IDF startup, returning ESP_OK + zeros when called too early. See identifyDevice() for the 3-strategy waterfall.
#include <esp_mac.h>
#include <esp_efuse.h>        // esp_efuse_read_field_blob — lowest-level eFuse access, used as fallback in identifyDevice()
#include <esp_efuse_table.h>  // ESP_EFUSE_MAC field descriptor
// For the /dbg chip command: silicon model / revision / features (esp_chip_info, esp_get_idf_version, esp_reset_reason). See docs/howto_efuse.md.
#include <esp_chip_info.h>
#include <esp_system.h>
// esp_coex_preference_set(): tells the ESP-IDF coexistence scheduler which radio (WiFi or BT/BLE) gets priority when both contend for the 2.4 GHz
// front-end. Default on arduino-esp32 is ESP_COEX_PREFER_BALANCE which gives BLE roughly the same slots as WiFi; when our BLE keyboard reconnects
// at boot (scan + auth + 3× subscribe in ~2 s), that balance is enough to starve the first WiFi association and cause ASSOC_EXPIRE. We flip to
// ESP_COEX_PREFER_WIFI in setup() so the scheduler favours WiFi management frames during the critical assoc window. Header is part of esp_coex
// component, ships with the arduino-esp32 board package — no extra library needed.
#include <esp_coexist.h>

// WiFi state machine + onboarding (NVS / WiFiMulti / WiFiManager) lives in wifi.ino. This header pulls in the shared enum and the function
// prototypes that minimessenger.ino calls (setupWifi, wifiTick, wifiGetState, drawPortalInstructions, /wifi-* command helpers).
#include "wifi.h"

// MQTT plumbing (topics, globals, reconnect, publish, incoming dispatch, TLS root CA) lives in mqtt.ino. This header pulls in PubSubClient and the
// shared constants / extern declarations / function prototypes. Library Manager: "PubSubClient" (2.8).
#include "mqtt.h"

// DeviceDataEntry type + static find* method declarations + extern decl of the compiled table. The actual table (with per-deployment data) lives
// in personal-data.h, materialised when wifi.ino — last in the Arduino concatenation — includes that file. Pulling contacts.h here is what gives
// minimessenger.ino the struct definition it needs to declare `DeviceDataEntry g_deviceData` and to read its fields throughout the sketch.
#include "contacts.h"

// Provided by Arduino IDE (with ESP8266 board plugins ?)
#include <WiFiClientSecure.h>

// Install from library manager:
// - "Adafruit ST7735 and ST7789" (1.11.0)
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_ST7789.h>  // 320x240

// To get current date & time for timestamping messages.
// configTime() sets the ESP system clock via SNTP; required for TLS cert
// validity checks against the HiveMQ broker.
#include <time.h>

// Cf howto_fond pour la bascule vers une font buildée pour les accents
//#include <Fonts/FreeSans9pt8b.h>  // Police SANS accents 9x7 au lieu de 7x5 de la font par defaut
#include "FreeSans9pt8b_latin1.h"   // Police AVEC accents (et 9x7 au lieu de 7x5)
#include "FreeSans10pt8b_latin1.h"  // Police AVEC accents (et 9x7 au lieu de 7x5)

// Alias to decouple the sketch from the specific generated font. To switch
// font size or range (7b/8b), change ONLY the #include above + this #define.
#define CONVO_CMD_FONT FreeSans9pt8b
#define CONVO_MSG_FONT FreeSans10pt8b


// Numerical values of HID codes generated by the keyboard on keystrokes
#include "hid_keys.h"

// Our code to manage scan+connection to a BT keyboard
#include "mm_blekb.h"

// Our misc enums
#include "symbols.h"

// ESP_LOG* facade + tag definitions (shared with mm_blekb.cpp). Per-tag
// severity is set by setupLogging() in setup().
#include "mm_log.h"

// Auto-generated splash bitmap (see docs/howto_logo.md). Must be a .h, not a .ino: Arduino IDE concatene les .ino apres minimessenger.ino, donc un splash.ino
// arrive trop tard pour que showSplashScreen() voie les declarations de splash_bmp / splash_bmp_w / splash_bmp_h.
#include "splash.h"


// ================================================================================
// Toggles
// ================================================================================

// Serial
#define FLAG_READ_SERIAL_INPUTS

#define WITH_LOGS


// ================================================================================
// User configuration
// ================================================================================


// POSIX timezone string for Paris (Europe/Paris). Decoded:
//   CET-1     standard time name = CET, POSIX offset -1 → human UTC+1
//   CEST      daylight time name = CEST (implicit offset = CET + 1h = UTC+2)
//   M3.5.0    DST starts: Month 3 (March), week 5 (= last), day 0 (Sunday) → last Sunday of March
//   M10.5.0/3 DST ends:   last Sunday of October at 03:00 local
// With this in configTzTime(), the libc handles DST automatically; tm.tm_isdst tells us which side we are on.
#define TZ_PARIS "CET-1CEST,M3.5.0,M10.5.0/3"


// ================================================================================
// Configurable behaviour
// ================================================================================

#define LED_BLINK_FAST_DURATION_MS 150
#define LED_BLINK_SLOW_DURATION_MS 700

// MQTT timing constants (MQTT_KEEPALIVE_INTERVAL_MS, MQTT_CONNECT_RETRY_BASE_MS, MQTT_CONNECT_RETRY_MAX_MS) moved to mqtt.h.

// "Screen saver" Burn-in protection: time without local input (BT keystroke / serial) and
// without a remote message before the screen dims, then fully turns off.
#define DISPLAY_IDLE_BEFORE_DIM_MS 60'000UL   // 5 min  -> dim to 50%
#define DISPLAY_IDLE_BEFORE_OFF_MS 800'000UL  // 5 + 1 min -> panel off


// ================================================================================
// Hardware configuration
// ================================================================================

// Pins configuration
// ------------------

// Pin assignments use the ESP-IDF `GPIO_NUM_x` enum (from `<soc/gpio_num.h>`, pulled in by `Arduino.h`) rather than raw integers. Two reasons:
// (1) `GPIO_NUM_5` is unambiguous — no need to wonder whether "5" means GPIO5, header pin 5, or some generic small integer. It also matches the
// `D5` silkscreen on the HW-394 / DOIT V1 board (Dxx = GPIOxx on this board family — but NOT on D1 mini, where D2 = GPIO4).
// (2) The sentinel `GPIO_NUM_NC = -1` documents "this pin is intentionally not connected", which is clearer than a bare `-1` literal.

#define LED_STATUS   GPIO_NUM_32
#define LED_FRIEND_1 GPIO_NUM_33
#define LED_FRIEND_2 GPIO_NUM_25


// Scren configuration
// -------------------
// On TFT to D1mini :
//   CS:  D1Mini pin D2 (GPIO4)
//   RST: D1Mini pin D3 (GPIO0)
//   DC:  D1Mini pin D4 (GPIO2)
//   No need for constants if using std pins:
//     SCK (CLK) ---> D1Mini pin D5 (GPIO14, SLCK).  By default
//     MOSI(DIN) ---> D1Mini pin D7 (GPIO13)

// On ESP32:
// STT7789v pins, vue de dessus : GND, VCC, SCL, SDA, RST, DC, CS
// - TFT_SCL : D18 = GPIO18 "SCK" by default
// - TFT_SDA : D23 = GPIO23 "MOSI" by default
#define TFT_RST GPIO_NUM_NC  // not wired — the ST7789 has an internal Power-On Reset, see docs/info_tft_rst.md
#define TFT_DC  GPIO_NUM_2   // Data/Command select

// Chip select — MUST be wired to a real GPIO on this module. Empirically tested: tying the TFT's CS pin to GND on the breadboard side and setting
// `TFT_CS = GPIO_NUM_NC` (so Adafruit_SPITFT skips every CS digitalWrite via its `if (_cs >= 0)` guard) leaves the panel dark — only the backlight
// stays lit. The Sitronix datasheet says CS-permanently-low should work in single-device mode, but this particular AliExpress clone of the ST7789
// controller does not behave that way; it apparently needs the rising edge of CS between commands to reset its parser state. Keep CS on a real
// GPIO and let Adafruit_SPITFT toggle it per transaction.
#define TFT_CS GPIO_NUM_5

// Backlight pin for PWM dimming. Set to a GPIO if the BL/LED pin of the panel
// is wired to one (then dim = 50% PWM, off = 0% PWM). Set to -1 if the BL pin
// is tied straight to 3.3 V — the dim phase becomes invisible but the OFF
// state still works because it uses Adafruit_ST7789::enableDisplay(false).
//
// /!\ My STT7789v (Alixp) does NOT have this pin. Feature not possible here.
#define TFT_BL -1



// ================================================================================
// Global variables
// ================================================================================

// === Hardware scroll state (ST7789, portrait, partitioned framebuffer) ===
// FB_HEIGHT is the ST7789 framebuffer height in its NATIVE portrait
// orientation. The scroll commands (VSCRDEF / VSCSAD) always operate on
// framebuffer coordinates, irrespective of setRotation().
//
// We partition the 320 framebuffer lines into three regions:
//   [0, 25)             Top Fixed Area     → status bar (indicators)
//   [25, 301)           Vertical Scroll    → conversation messages
//   [301, 320)          Bottom Fixed Area  → input feedback footer
// The Top/Bottom Fixed areas are not affected by VSCSAD — we draw to them
// directly with normal GFX calls.
#define FB_WIDTH  240
#define FB_HEIGHT 320
// STATUS_BAR_H = 24 (icons + separator hairline) + 1 (black gap to aerate
// before the scroll area). The separator is drawn at line STATUS_BAR_H - 2.
#define STATUS_BAR_H 25
// FOOTER_H = 1 (top aération) + 1 (white hairline) + 1 (margin) + 16 (size-2
// text) + 0 (text flush with screen bottom). See the diagram at the top of
// this file for the row-by-row breakdown.
#define FOOTER_H         19
#define SCROLL_AREA_H    (FB_HEIGHT - STATUS_BAR_H - FOOTER_H)  // 276
#define SCROLL_AREA_Y_FB STATUS_BAR_H                           // 25
#define FOOTER_Y_FB      (FB_HEIGHT - FOOTER_H)                 // 301

// g_scrollY: scroll OFFSET inside the scroll area, in [0, SCROLL_AREA_H).
//            The absolute VSCSAD value sent to the controller is
//            g_scrollY + STATUS_BAR_H.
// g_drawY:   offset inside the scroll area where the next conversation
//            block's top will be drawn. In [0, SCROLL_AREA_H).
//            After a draw + scroll, g_drawY == g_scrollY (mod SCROLL_AREA_H).
uint16_t g_scrollY = 0;
uint16_t g_drawY   = 0;

// === Status bar layout ===
// Two network-state chips on the left (WiFi white, MQTT yellow), a 50 px visual spacer, two input-state chips (BT blue + CapsLock A/a in white), then
// the contact silhouette in red on the right. The radius is sized to fit comfortably in the 24 px high bar with a few pixels of margin.
#define ICON_RADIUS   6
#define ICON_Y_CENTER (STATUS_BAR_H / 2)  // 12
// Order from left to right: WiFi, MQTT, [50 px spacer], BT, CapsLock, …, Contact. The 50 px gap separates "network reachability" indicators (left
// cluster) from "keyboard input" indicators (right cluster) so the user can scan their meaning at a glance.
#define ICON_WIFI_X 12
#define ICON_MQTT_X 32
// BT sits 50 px right of MQTT's right edge: ICON_MQTT_X + ICON_RADIUS + 50 + ICON_RADIUS = 32 + 6 + 50 + 6 = 94.
#define ICON_BT_X      94
#define ICON_CAPS_X    114
#define ICON_CONTACT_X (FB_WIDTH - 12)  // 228 — used when 0 or 1 contact is online (single silhouette on the historical anchor).
// When 2+ contacts are online, two silhouettes are drawn straddling ICON_CONTACT_X. Body width = 11 px and head r = 3 px, so a ±9 px split leaves
// ~7 px d'air entre les deux silhouettes : assez pour rester lisibles en mode plein, sans déborder du framebuffer 240 px de large (X_RIGHT atteint au
// pire 237+5 = 242, soit 2 px hors champ — réduire l'écart à ±8 si jamais le débordement est visible à l'écran).
#define ICON_CONTACT_X_LEFT  (ICON_CONTACT_X - 15)
#define ICON_CONTACT_X_RIGHT (ICON_CONTACT_X)

// Last-drawn-state cache + color palette + bar drawing functions all live in bars.ino. Two globals stay here because they are SET from many
// places in this file (boot, mode switches, caps toggle, etc.): g_statusBarDirty toggles a forced repaint, g_lastStatusBarPollMs is the
// debounce timer.
bool          g_statusBarDirty      = true;
unsigned long g_lastStatusBarPollMs = 0;
#define STATUS_BAR_POLL_INTERVAL_MS 500

// Info-screen refreshes are event-driven (no periodic polling). Each state change that can affect what the info screen displays — WiFi state
// transition, MQTT connect, BLE keyboard connect/disconnect, NTP sync — calls refreshInfoScreenIfShown(), which forwards to showUpdatedInfoScreen
// only when the info screen is currently visible (i.e. !g_inConversationMode). Two consequences:
//   - During boot phase, the info screen is shown and each subsystem coming online pushes a refresh — same effect as the old 2s timer, but
//     reactive rather than polled, and no risk of a double-render race with /status (which used to fire its own showUpdatedInfoScreen and then
//     the timer would re-fire 5-100 ms later because the timer's last-refresh timestamp wasn't updated).
//   - During conversation mode, refreshInfoScreenIfShown is a no-op; only the status bar polls.

// Non-zero value = the info screen is currently shown as a temporary overlay (triggered by "/status") and we should auto-revert to nominal once
// millis() crosses it. Zero = not in the status-overlay state. The revert path is in loop() near the status bar polling block.
unsigned long g_statusScreenEndMs = 0;
#define STATUS_SCREEN_DURATION_MS 10'000

// Conversation mode = status bar + scroll area + input footer are all live.
// Fullscreen modes (splash, info) set this to false to suppress the periodic
// status bar repaint that would otherwise draw indicators over their content.
bool g_inConversationMode = false;

// Pour le calcul des bounds d'un texte construit avec une font donnée
#define BOX_X 0
#define BOX_Y 1
#define BOX_W 2
#define BOX_H 3

#include "display.h"


const int MAX_LINES = 13;  // nombre max de lignes gardées en mémoire. Utile uniquement quand on redessine les conversations depuis l'écran de status

// True ring buffer: no per-element shift, no copy on scroll. Logical index i
// (0 = oldest visible line) maps to `lines[(g_lineHead + i) % MAX_LINES]`.
// Adding a line: write at (g_lineHead + g_lineCount) % MAX_LINES, ++g_lineCount.
// Dropping the oldest: ++g_lineHead, --g_lineCount.
TextLine lines[MAX_LINES];
int      g_lineHead  = 0;
int      g_lineCount = 0;

#define CONVO_TS_FONT_SIZE     1
#define CONVO_TS_MARGIN_BOTTOM 3  // avec font par defaut: 3
#define CONV0_TS_COLOR         ST77XX_CYAN

#define CONVO_MSG_FONT_SIZE      1  // 2 est vraiment trop énorme avec la font FreeSans9pt8b
#define CONVO_MSG_MARGIN_BOTTOM  7  //
#define CONVO_HELP_MARGIN_BOTTOM 4  //

#define CONVO_INFO_COLOR  ST77XX_GREEN
#define CONVO_ERROR_COLOR ST77XX_RED
// Hot pink (RGB565 ≈ #FF69B4). Used by command-output listings (help / cmd echoes) to make them visually distinct from regular messages and from info/error notices.
#define CONVO_CMD_COLOR 0xFB56

// Pixel column where the right-hand text starts when printInfoLine() is called with two strings (cmd-name + description in /help listings).
// Mirrors the colValues=70 fixed-column layout of the status info screen, slightly shifted because /help uses the proportional CONVO_CMD_FONT
// instead of the default 5×7 font: the longest command name "/wifi forget" is ~75 px wide in FreeSans 9pt — 90 px leaves a clean ~15 px gap.
#define INFO_LINE_RIGHT_COL_X 90

// When two messages (incoming or outgoing) land within this many seconds,
// suppress the second one's timestamp to declutter the conversation view.
// The "last visible timestamp" tracking continues until a message arrives
// outside the window, at which point the timestamp is shown again.
#define CONVO_TS_HIDE_THRESHOLD_S 10
time_t g_lastShownTsEpoch = 0;

// WiFi
WiFiClientSecure g_wifiClient;

// WiFi reconnection state moved to wifi.ino along with the rest of the WiFi machinery. The state machine there drives banners on rising / falling
// edges; this .ino just exposes UI surfaces.


// OLED Display
Adafruit_GFX* g_disp = NULL;

// Burn-in protection state
DisplayPowerState g_displayPowerState = DISPLAY_ON;
unsigned long     g_lastActivityMs    = 0;

// format "YYYY-MM-DD HH:MM:SS"
char g_ts[20];


// Serial
#ifdef FLAG_READ_SERIAL_INPUTS
#define MAX_SERIAL_MSG_LENGTH 100
char g_fullMsgFromSerial[MAX_SERIAL_MSG_LENGTH + 1];
char g_inChar;
byte g_inNextCharIndex = 0;
#endif

// Messaging — per-device identity
// Device IDs are unsigned bytes [0..255]. 0xFF is the "unset" sentinel — only used by contacts.ino as the free-slot marker for the dynamic peer
// table (`g_contacts[i].deviceId == DEVICE_ID_UNSET`). The local device's identity lives entirely in g_deviceData below.
#define DEVICE_ID_UNSET 0xFF

// Unified per-device identity record — populated once by identifyDevice() at boot. Two paths: clone the matching row of COMPILED_DEVICE_DATA_ENTRIES
// (known MAC), or synthesise an entry on the fly (unknown MAC: random ID, "JohnDoe" pseudo, "UNK" prefix, ST7789 screen). After identifyDevice()
// returns this is the single source of truth — read directly via `g_deviceData.deviceId / pseudo / screen / namePrefix`, or via the formatted-name
// method `g_deviceData.name()` (defined as a member of DeviceDataEntry in contacts.h).
DeviceDataEntry g_deviceData;


#define LED_STATE_NOT_CONFIGURED -1
#define LED_STATE_OFF            0
#define LED_STATE_ON             1
#define LED_STATE_BLINK_FAST     2
#define LED_STATE_BLINK_SLOW     3
// LED arrays are indexed by raw GPIO pin number (ledSetState(pin, …) → g_ledRequiredState[pin] = …). The ESP32 exposes GPIOs up to 39, so the arrays
// must be sized to cover that range — otherwise ledSetState(32, …) writes 32 bytes past a too-small array and corrupts adjacent BSS globals. The
// previously-used value of 17 came from the D1 mini era (ESP8266, GPIO 0..16) and stealthily wrote on top of adjacent identity BSS globals on ESP32,
// producing 0x02 (LED_STATE_BLINK_FAST as a byte → rendered as a smiley by the Adafruit GLCD font) at the offset matching LED_STATUS=GPIO32 minus
// the array's actual length. 40 covers the full ESP32 GPIO range (0..39); bump to 48 if porting to ESP32-S2/S3/C3 with larger GPIO maps.
#define LED_QTY                  40
byte          g_ledRequiredState[LED_QTY];
bool          g_ledBlinkStateIsHigh[LED_QTY];
unsigned long g_ledBlinkLastTimestampMs[LED_QTY];

// Keyboard
bool   kbIsCapsLockOn           = false;
String g_currentMsgFromKeyboard = "";

// Insertion point inside g_currentMsgFromKeyboard, range [0, g_currentMsgFromKeyboard.length()].
// When equal to length(), the cursor sits after the last character (default
// state — equivalent to "append at end").
// Mutated only via the currentMsgXxxCursor() helpers so the invariant is centrally enforced.
size_t g_msgCursorIdx = 0;


// ================================================================================
// Forward declarations — needed because the Arduino IDE's auto-prototype generator can be flaky when the sketch has multiple .ino files / mixes
// modern C++ types in headers. List functions called from earlier in the file than their definition.
// ================================================================================

void setUnicastRecipient(int recipientDeviceId);
void setBroadcastRecipient();
void showUpdatedInfoScreen();
void refreshInfoScreenIfShown();
void redrawStatusBar();
void redrawInputFooter();
bool noteUserActivity();
void routeMessage(const String& message, MessageSource source);
void ledSetState(int pin, int requiredState);
// mqttSendAlive / mqttPushFormattedMessage / onMqttIncomingMessage prototypes provided by mqtt.h.
void goAndResetConversationScreen();
void returnToConversationsScreen();
void clearConversationHistory();
void resetSerialBuffer();
// contacts.ino API — explicit forward decls because the Arduino auto-prototype pass occasionally misses cross-.ino calls (notably from bars.ino into
// contacts.ino, which is concatenated AFTER bars.ino in alphabetical order). Without these the build fails with "not declared in this scope".
void contactsSetup();
void contactsTick();
void onReceivedContactOnline(int remoteDeviceId, bool isLive);
int  contactGetActiveCount();
// Two overloads — see definitions for the contract.
//   single-string: prints `msg` left-aligned, full line. Used for banners / status messages.
//   two-string:    prints `left` left-aligned and `right` at a fixed column (INFO_LINE_RIGHT_COL_X). Used for /help listings: cmd + description.
// The compiler picks via overload resolution: a const-char* literal as 2nd arg → 2-string ; a numeric color as 2nd arg → 1-string. See the
// String-vs-uint16_t ambiguity analysis in the .cpp impl docstring.
void printInfoLine(const String& msg, uint16_t color = CONVO_CMD_COLOR, const GFXfont* font = &CONVO_CMD_FONT);
void printInfoLine(const String& left, const String& right, uint16_t color = CONVO_CMD_COLOR, const GFXfont* font = &CONVO_CMD_FONT);

// String utilities — defined in strings.ino. Called from printInfoLine / addConversationBlock below, which would compile before the strings.ino
// concatenation appends the definition, so the forward decl is mandatory.
size_t utf8ToLatin1(char* s);

// Command layer — defined in commands.ino. routeMessage() (this file) calls processPayloadAsCommand() to interpret /cmd payloads; the rest is
// internal to commands.ino but kept declared here too so any future caller in minimessenger.ino can resolve them without ordering surprises.
bool processPayloadAsCommand(const String& message);
bool processWifiSubcommand(const String& message);
bool processDbgSubcommand(const String& message);
void printHelpGlobal();
void printHelpWifi();
void printHelpDbg();


// ================================================================================
// Logging
// ================================================================================
// All logging uses ESP-IDF's esp_log via mm_log.h. Per-tag severity is
// configured in setup() through setupLogging().

void assertTrue(bool condition, String msg) {
    if (!condition) {
        ESP_LOGE(TAG_MM, "ASSERT FAILED: %s", msg.c_str());
    }
}

// ================================================================================
// char* & Strings
// ================================================================================

char* trim(char* str) {
    // Left trim
    while (isspace((unsigned char)*str)) {
        str++;
    }

    if (*str == 0) {  // all spaces?
        return str;
    }

    // Right trim
    char* end = str + strlen(str) - 1;
    while (end > str && isspace((unsigned char)*end)) {
        end--;
    }

    // Write new null terminator
    *(end + 1) = '\0';

    return str;
}

// ================================================================================
// Time
// ================================================================================
void setupNTP() {
    ESP_LOGI(TAG_MM, "Init NTP...");
    // configTzTime (vs configTime with a fixed offset) installs a POSIX TZ rule that auto-switches between CET and CEST. localtime_r will then
    // populate tm.tm_isdst correctly twice a year without us touching anything.
    configTzTime(TZ_PARIS, "europe.pool.ntp.org", "pool.ntp.org");

    // Block until SNTP returns a plausible epoch (after 2023-11) so the first
    // TLS handshake doesn't run with a 1970 clock and reject the broker cert.
    time_t now   = 0;
    int    tries = 0;
    while ((now = time(nullptr)) < 1700000000 && tries++ < 30) {
        delay(500);
    }
    ESP_LOGI(TAG_MM, "NTP synced after %d tries, epoch=%ld", tries, (long)now);

    // Push a refresh to the info screen if it's shown — the TIME row label is computed from the local TZ which is only valid post-NTP.
    refreshInfoScreenIfShown();
}

char* getCurrentDateTime() {
    time_t    epochTime = time(nullptr);
    struct tm timeInfo;
    localtime_r(&epochTime, &timeInfo);

    snprintf(g_ts,
             sizeof(g_ts),
             "%04d-%02d-%02d|%02d:%02d:%02d",
             timeInfo.tm_year + 1900,
             timeInfo.tm_mon + 1,
             timeInfo.tm_mday,
             timeInfo.tm_hour,
             timeInfo.tm_min,
             timeInfo.tm_sec);

    return g_ts;
}

char* getCurrentTime() {
    time_t    epochTime = time(nullptr);
    struct tm timeInfo;
    localtime_r(&epochTime, &timeInfo);

    snprintf(g_ts, sizeof(g_ts), "%02d:%02d:%02d", timeInfo.tm_hour, timeInfo.tm_min, timeInfo.tm_sec);

    return g_ts;
}

// Returns "Paris (UTC+1)" in winter (CET) or "Paris (UTC+2)" in summer (CEST). Relies on the POSIX TZ rule installed by setupNTP() via
// configTzTime(TZ_PARIS, ...): the libc populates tm.tm_isdst correctly and we just translate it to the human label.
const char* getTimezoneLabel() {
    time_t    epochTime = time(nullptr);
    struct tm timeInfo;
    localtime_r(&epochTime, &timeInfo);
    // tm_isdst > 0 → DST in effect (CEST, UTC+2). 0 → standard (CET, UTC+1). < 0 → unknown (would happen if TZ isn't set; we still default to UTC+1).
    return (timeInfo.tm_isdst > 0) ? "Paris (UTC+2)" : "Paris (UTC+1)";
}


// ============================================================================
// Keystrokes
// ============================================================================

// USB HID keycode to ASCII lookup tables
char keymapLower[128] = {
    0,   0,   0,   0,   'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',  'i', 'j',  'k',  'l', 'm', 'n', 'o', 'p', 'q',  'r', 's', 't',  'u', 'v', 'w', 'x', 'y',
    'z', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '\n', 0,   '\b', '\t', ' ', '-', '=', '[', ']', '\\', '#', ';', '\'', '`', ',', '.', '/',
    // extend if needed
};

char keymapUpper[128] = {
    0,   0,   0,   0,   'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',  'I', 'J',  'K',  'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
    'Z', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '\n', 0,   '\b', '\t', ' ', '_', '+', '{', '}', '|', '~', ':', '"', '~', '<', '>', '?',
    // extend if needed
};


// === Message buffer editing helpers ==========================================
// All keystroke effects on g_currentMsgFromKeyboard go through these helpers so that the
// cursor invariant (0 <= g_msgCursorIdx <= length()) is enforced in one place
// and decodeHIDReport() stays a flat dispatch table.
// Each helper redraws the footer at the end so callers don't have to.

void currentMsgClear() {
    g_currentMsgFromKeyboard = "";
    g_msgCursorIdx           = 0;
    redrawInputFooter();
}

void currentMsgInsertCharAtCursor(char c) {
    const size_t lenBefore = g_currentMsgFromKeyboard.length();
    if (g_msgCursorIdx > lenBefore) {
        return;  // invariant violated — should never happen since the caller helpers clamp the cursor; bail rather than corrupting the buffer.
    }
    // In-place edit: append the char at the end (String::concat reuses the reserve(100) buffer with no heap allocation as long as length stays below
    // capacity), then if the cursor was somewhere before the end, walk the tail right one position with setCharAt so the new char ends up at the cursor.
    // This avoids the previous substring+concat reassignment which allocated four short-lived String temporaries per keystroke and fragmented the heap.
    g_currentMsgFromKeyboard.concat(c);
    if (g_msgCursorIdx < lenBefore) {
        for (size_t i = lenBefore; i > g_msgCursorIdx; i--) {
            g_currentMsgFromKeyboard.setCharAt(i, g_currentMsgFromKeyboard.charAt(i - 1));
        }
        g_currentMsgFromKeyboard.setCharAt(g_msgCursorIdx, c);
    }
    g_msgCursorIdx++;
    ESP_LOGD(TAG_BTKB, "Insert [%c] at %u → msg=[%s] cur=%u", c, (unsigned)(g_msgCursorIdx - 1), g_currentMsgFromKeyboard.c_str(), (unsigned)g_msgCursorIdx);
    redrawInputFooter();
}

// Backspace: removes the character just left of the cursor (and the cursor
// follows). No-op when at the beginning of the buffer. Uses String::remove()
// to shrink in place — no reallocation, friendly to the reserved capacity.
void currentMsgDeleteCharBeforeCursor() {
    if (g_msgCursorIdx == 0) {
        return;
    }
    g_currentMsgFromKeyboard.remove(g_msgCursorIdx - 1, 1);
    g_msgCursorIdx--;
    ESP_LOGD(TAG_BTKB, "Backspace → msg=[%s] cur=%u", g_currentMsgFromKeyboard.c_str(), (unsigned)g_msgCursorIdx);
    redrawInputFooter();
}

// Delete (Suppr): removes the character under the cursor. Cursor stays put.
// No-op when at the end of the buffer (nothing to the right).
void currentMsgDeleteCharAtCursor() {
    if (g_msgCursorIdx >= g_currentMsgFromKeyboard.length()) {
        return;
    }
    g_currentMsgFromKeyboard.remove(g_msgCursorIdx, 1);
    ESP_LOGD(TAG_BTKB, "Delete → msg=[%s] cur=%u", g_currentMsgFromKeyboard.c_str(), (unsigned)g_msgCursorIdx);
    redrawInputFooter();
}

void currentMsgMoveCursorLeft() {
    if (g_msgCursorIdx == 0) {
        ESP_LOGD(TAG_BTKB, "LEFT at cur=0 — no-op");
        return;
    }
    g_msgCursorIdx--;
    ESP_LOGD(TAG_BTKB, "LEFT → cur=%u", (unsigned)g_msgCursorIdx);
    redrawInputFooter();
}

void currentMsgMoveCursorRight() {
    if (g_msgCursorIdx >= g_currentMsgFromKeyboard.length()) {
        ESP_LOGD(TAG_BTKB, "RIGHT at cur=%u (end) — no-op", (unsigned)g_msgCursorIdx);
        return;
    }
    g_msgCursorIdx++;
    ESP_LOGD(TAG_BTKB, "RIGHT → cur=%u", (unsigned)g_msgCursorIdx);
    redrawInputFooter();
}


void decodeHIDReport(uint8_t* pData, size_t length) {
    if (length < 8) {
        return;  // HID boot keyboard report is 8 bytes
    }

    // HID Boot Keyboard report layout:
    //   pData[0]    = modifier bitmask (Shift/Ctrl/Alt/GUI, left+right)
    //   pData[1]    = reserved (always 0)
    //   pData[2..7] = up to 6 currently-held key codes (6KRO — 6-key rollover)
    //
    // IMPORTANT: a report describes the CURRENT STATE (which keys are held
    // right now), not an event. The keyboard emits a new report on every
    // state change — press OR release. Slots [2..7] are unordered and a given
    // key can migrate between slots from one report to the next.
    //
    // To turn this state stream into discrete keypresses we keep the previous
    // report's key set and only fire for keys that are NEWLY present. This
    // fixes two real-world bugs:
    //
    //   1. Duplicates on dwell / HID auto-repeat
    //      Holding a key past ~500 ms makes the keyboard re-emit the same
    //      report periodically. Reading pData[2] naively appended the same
    //      character on every notification. With press-edge diffing, the key
    //      stays in s_prevKeys[] for the whole hold and triggers exactly once.
    //
    //   2. Lost keys on fast two-hand typing
    //      When B is pressed before A is released, a single report carries
    //      [A, B] together — and the old code (which only looked at pData[2])
    //      never saw B. The diff loop below walks all 6 slots and catches
    //      every newly-pressed one, even when several arrive in the same
    //      notification.

    static uint8_t s_prevKeys[6] = { 0 };
    uint8_t        curKeys[6]    = { pData[2], pData[3], pData[4], pData[5], pData[6], pData[7] };
    uint8_t        modifiers     = pData[0];

    // Wake screen on any keystroke. If we were sleeping, discard this report:
    // the user pressed a key to light the screen, not to type. We still commit
    // curKeys into s_prevKeys so a key held across the wake-up boundary isn't
    // mistakenly seen as "newly pressed" on the next report.
    bool anyKeyHeld = false;
    for (int i = 0; i < 6; i++) {
        if (curKeys[i] != 0) {
            anyKeyHeld = true;
            break;
        }
    }
    if (anyKeyHeld && noteUserActivity()) {
        memcpy(s_prevKeys, curKeys, 6);
        return;
    }

    bool usingSomeShift = (modifiers & 0x22);  // LeftShift(0x02) or RightShift(0x20)

    // Walk every slot in the new report; handle each key that wasn't already
    // present in the previous report. Order within [2..7] is whatever the
    // keyboard firmware chose — in practice it matches the press order for the
    // common alternating-fingers case.
    for (int i = 0; i < 6; i++) {
        uint8_t key = curKeys[i];
        if (key == 0) {
            continue;
        }

        bool wasHeldBefore = false;
        for (int j = 0; j < 6; j++) {
            if (s_prevKeys[j] == key) {
                wasHeldBefore = true;
                break;
            }
        }
        if (wasHeldBefore) {
            continue;  // still held since the previous report, not a new press
        }

        // --- Press edge: handle this newly-pressed key ---

        // Log every press at DEBUG so missing keys (e.g. KEY_RIGHT not reaching us
        // at all) are distinguishable from "received but unhandled by our dispatch".
        ESP_LOGD(TAG_BTKB, "HID press code=%u modifiers=%u shift=%d", key, modifiers, usingSomeShift ? 1 : 0);

        if (key == KEY_CAPSLOCK) {
            kbIsCapsLockOn   = !kbIsCapsLockOn;
            g_statusBarDirty = true;  // pousse un repaint immédiat de la barre pour faire basculer le glyphe 'A'/'a' sans attendre le tick périodique.
            ESP_LOGD(TAG_BTKB, "CapsLock toggled: %s", kbIsCapsLockOn ? "ON" : "OFF");
            continue;
        } else if (key == KEY_BACKSPACE) {
            currentMsgDeleteCharBeforeCursor();
            continue;
        } else if (key == KEY_DELETE) {
            currentMsgDeleteCharAtCursor();
            continue;
        } else if (key == KEY_ENTER) {
            if (g_currentMsgFromKeyboard.length() > 0) {
                ESP_LOGI(TAG_BTKB, "ENTER — sending msg #%u: %s", g_mqttOutputMsgId, g_currentMsgFromKeyboard.c_str());
                routeMessage(String(g_currentMsgFromKeyboard), MessageSource::LOCAL);
                currentMsgClear();
            } else {
                ESP_LOGD(TAG_BTKB, "ENTER on empty buffer — nothing to send");
            }
            continue;
        } else if (key == KEY_LEFT) {
            currentMsgMoveCursorLeft();
            continue;
        } else if (key == KEY_RIGHT || key == KEY_UP) {
            // KEY_UP doubles as "right" because the BT keyboard bonded to this
            // device doesn't emit KEY_RIGHT (the dedicated right arrow is either
            // absent on the layout or mapped to a FN layer we never receive).
            currentMsgMoveCursorRight();
            continue;
        } else if (key == KEY_ESC) {
            ESP_LOGI(TAG_BTKB, "ESC pressed — resetting message buffer");
            currentMsgClear();
            continue;
        } else if (key == KEY_TAB || key == KEY_DOWN) {
            ESP_LOGD(TAG_BTKB, "HID code [%u] explicitly ignored", key);
            continue;
        }

        char ascii = 0;
        if (key < 128) {
            if ((kbIsCapsLockOn ^ usingSomeShift) && keymapUpper[key]) {
                ascii = keymapUpper[key];
            } else {
                ascii = keymapLower[key];
            }
        }

        if (ascii) {
            currentMsgInsertCharAtCursor(ascii);
        } else {
            ESP_LOGD(TAG_BTKB, "Unknown HID code: %u", key);
        }
    }

    // Commit the new state so the next report can diff against it.
    memcpy(s_prevKeys, curKeys, 6);
}


void onBluetoothKeyboardConnectionCallback(bool isFullyConnected) {
    ESP_LOGI(TAG_BTKB, "onKeyboardConnectionCallback(%d)", isFullyConnected ? 1 : 0);
    // Repaint the input footer so the "<no keyboard>" placeholder appears/disappears immediately on (dis)connect, without waiting for the next
    // keystroke or screen-state event. Safe at boot: redrawInputFooter() early-returns if g_inConversationMode is false.
    redrawInputFooter();
    // And push a refresh to the info screen if it's shown — the BTKB row flips between "Not found" and "Connected".
    refreshInfoScreenIfShown();
}

static void onBluetoothKeyboardNotifyCallback(uint8_t* pData, size_t length) {
    decodeHIDReport(pData, length);
}



// ================================================================================
// Connectivity
// ================================================================================

// Read the real factory MAC from silicon eFuse with a 3-strategy waterfall. Background: the obvious-looking esp_efuse_mac_get_default() turned
// out to be a TRAP — on arduino-esp32 3.3.8 (IDF 5.x) it is now a wrapper that internally calls esp_read_mac(mac, ESP_MAC_BASE). ESP_MAC_BASE
// does NOT read the silicon eFuse; it returns a static cached value populated by esp_base_mac_addr_set() during the IDF startup sequence. If
// we call before that startup hook has run, the function returns ESP_OK with all zeros (silently, no error). That's why every previous attempt
// to "just read the eFuse" failed: we were actually reading an empty RAM cache.
//
// The fix is to use ESP_MAC_EFUSE_FACTORY, which is documented to read DIRECTLY from the silicon eFuse with no cache layer. If for any reason
// that fails too (e.g. on a non-ESP32 variant where the field is differently mapped), fall back to esp_efuse_read_field_blob() which is the
// lowest-level eFuse access we have. Last-resort fallback: bring WiFi up and read WiFi.macAddress() — slow (~100 ms) but rock solid because the
// WiFi driver itself queries the eFuse during init.
//
// Returns the canonical "XX:XX:XX:XX:XX:XX" string. Returns "00:00:00:00:00:00" if every strategy failed (extremely unusual — would mean the
// eFuse is unreadable AND WiFi refuses to come up). Callers can detect this via direct comparison with that literal.
String getRealHardwareMAC() {
    uint8_t macBytes[6] = { 0 };
    auto    isAllZero   = [](const uint8_t* m) { return (m[0] | m[1] | m[2] | m[3] | m[4] | m[5]) == 0; };

    const char* strategy = "EFUSE_FACTORY";
    esp_err_t   err      = esp_read_mac(macBytes, ESP_MAC_EFUSE_FACTORY);
    if (err != ESP_OK || isAllZero(macBytes)) {
        ESP_LOGW(TAG_MM, "Strategy 1 (esp_read_mac EFUSE_FACTORY) failed: err=%d zero=%d — trying field_blob", err, isAllZero(macBytes));
        strategy = "FIELD_BLOB";
        err      = esp_efuse_read_field_blob(ESP_EFUSE_MAC, macBytes, 48);
    }
    if (err != ESP_OK || isAllZero(macBytes)) {
        ESP_LOGW(TAG_MM, "Strategy 2 (field_blob) failed: err=%d zero=%d — falling back to WiFi.macAddress", err, isAllZero(macBytes));
        strategy = "WIFI_STA";
        WiFi.mode(WIFI_STA);
        delay(100);
        WiFi.macAddress(macBytes);
    }

    char macStr[18];
    snprintf(macStr, sizeof(macStr), "%02X:%02X:%02X:%02X:%02X:%02X", macBytes[0], macBytes[1], macBytes[2], macBytes[3], macBytes[4], macBytes[5]);

    if (isAllZero(macBytes)) {
        ESP_LOGE(TAG_MM, "All MAC read strategies failed — falling through with %s (last attempted: %s)", macStr, strategy);
    } else {
        ESP_LOGD(TAG_MM, "MAC Address: %s (read via %s)", macStr, strategy);
    }

    return String(macStr);
}


void identifyDevice() {
    String mac = getRealHardwareMAC();

    const DeviceDataEntry* entry = DeviceDataEntry::findByMac(mac.c_str());
    if (entry != nullptr) {
        // Known device: clone the compiled entry into the mutable global. The const char* members (mac, pseudo, namePrefix) keep pointing at the
        // flash literals from personal-data.h, which is fine since those literals outlive the device boot.
        g_deviceData = *entry;
    } else {
        // Unknown MAC: prototype / new device not yet listed in personal-data.h. Synthesise an entry on the fly so the rest of the code keeps a
        // single source of truth (g_deviceData). The dynamic MAC string is parked in a function-local static so its address stays valid for the
        // device lifetime — pseudo and namePrefix point at string literals (persistent automatically).
        static char s_dynamicMacBuf[18];
        strncpy(s_dynamicMacBuf, mac.c_str(), sizeof(s_dynamicMacBuf) - 1);
        s_dynamicMacBuf[sizeof(s_dynamicMacBuf) - 1] = '\0';

        g_deviceData.mac        = s_dynamicMacBuf;
        g_deviceData.deviceId   = (byte)random(100, 1000);  // [100..999] avoids colliding with the small IDs declared in COMPILED_DEVICE_DATA_ENTRIES.
        g_deviceData.pseudo     = "JohnDoe";
        g_deviceData.namePrefix = "UNK";
        g_deviceData.screen     = ST7789;  // default — the only target with a working renderer today; OLEDSHIELD branch is still a stub.
    }

    ESP_LOGI(TAG_MM, "Identified device: name=[%s] id=%d screenType=%d for [%s]",
             g_deviceData.name(), g_deviceData.deviceId, (int)g_deviceData.screen, g_deviceData.pseudo);

    // La version courante du code n'envoie pas sur un topic specifique à un recipient avec setUnicastRecipient(recipientId)
    setBroadcastRecipient();
}


// ================================================================================
// WIFI
// ================================================================================
//
// The connection state machine and the NVS-backed network list live in wifi.ino (concatenated into the same translation unit by the Arduino IDE).
// setupWifi() is defined there and handles the whole WiFi bringup in one call: driver mode + hostname + NVS seed/load + WiFiManager config +
// state machine kick. The TLS root CA wiring stays below in setup() since it's an MQTT concern, not a WiFi one. wifiTick() in loop() drives the
// async association and reconnection.

// ================================================================================
// BLUETOOTH KEYBOARD
// ================================================================================

MiniMessengerBLEKeyboardInterface g_kb;

boolean setupKeyboard() {
    ESP_LOGI(TAG_BTKB, "setupKeyboard()...");

    g_currentMsgFromKeyboard.reserve(100);

    // Scan filter is now based on the HID GATT service UUID (see mm_blekb.cpp::onResult), not on the device name — no keyboard name to pass here.
    return g_kb.setup(false,  // clear bonds — flip to true once if a stale bond is blocking pairing with a new physical keyboard; prefer `cmd bonds` at runtime
                      onBluetoothKeyboardConnectionCallback,
                      onBluetoothKeyboardNotifyCallback);
}


// ================================================================================
// LED
// ================================================================================

void ledSetState(int pin, int requiredState) {
    ESP_LOGD(TAG_MM, "led pin=%d state=%d", pin, requiredState);
    g_ledRequiredState[pin] = requiredState;

    if (requiredState == LED_STATE_OFF) {
        digitalWrite(pin, LOW);
    } else if (requiredState == LED_STATE_ON) {
        digitalWrite(pin, HIGH);
    } else {
        g_ledBlinkStateIsHigh[pin]     = false;
        g_ledBlinkLastTimestampMs[pin] = millis();
        digitalWrite(pin, g_ledBlinkStateIsHigh[pin] ? HIGH : LOW);
    }
}

void ledCommuteBlinkState(int pin) {
    g_ledBlinkStateIsHigh[pin]     = !g_ledBlinkStateIsHigh[pin];
    g_ledBlinkLastTimestampMs[pin] = millis();
    digitalWrite(pin, g_ledBlinkStateIsHigh[pin] ? HIGH : LOW);
}

void setupLeds() {
    pinMode(LED_STATUS, OUTPUT);
    pinMode(LED_FRIEND_1, OUTPUT);
    pinMode(LED_FRIEND_2, OUTPUT);

    for (int i = 0; i < 4; i++) {
        digitalWrite(LED_STATUS, HIGH);
        digitalWrite(LED_FRIEND_1, HIGH);
        digitalWrite(LED_FRIEND_2, HIGH);
        delay(150);
        digitalWrite(LED_STATUS, LOW);
        digitalWrite(LED_FRIEND_1, LOW);
        digitalWrite(LED_FRIEND_2, LOW);
        delay(150);
    }

    for (int pin = 0; pin < LED_QTY; pin++) {
        g_ledRequiredState[pin] = LED_STATE_NOT_CONFIGURED;
    }
    ledSetState(LED_STATUS, LED_STATE_BLINK_FAST);
    ledSetState(LED_FRIEND_1, LED_STATE_OFF);
    ledSetState(LED_FRIEND_2, LED_STATE_OFF);
}



// ================================================================================
// OLED
// ================================================================================

// === Hardware vertical scroll helpers (ST7789, MIPI DCS commands) ===
// See docs/howto_hardware_scrolling.md for the full design rationale.
// 0x33 (VSCRDEF) declares the scroll area partition; 0x37 (VSCSAD) sets the
// virtual top line within that partition. No high-level API in Adafruit_GFX
// exposes this, hence the raw sendCommand() calls.

void hwScrollSetupArea() {
    if (g_deviceData.screen != DisplayType::ST7789) {
        return;
    }
    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;
    // TFA = STATUS_BAR_H, VSA = SCROLL_AREA_H, BFA = FOOTER_H.
    // TFA + VSA + BFA must equal FB_HEIGHT (=320 for ST7789).
    uint8_t args[6] = {
        0, STATUS_BAR_H, (uint8_t)(SCROLL_AREA_H >> 8), (uint8_t)(SCROLL_AREA_H & 0xFF), 0, FOOTER_H,
    };
    pDisp->sendCommand(0x33, args, 6);  // VSCRDEF
}

// `scrollOffset` is the offset within the scroll area in [0, SCROLL_AREA_H).
// The absolute VSCSAD value sent to the controller must be in [TFA, TFA+VSA).
void hwScrollTo(uint16_t scrollOffset) {
    g_scrollY = scrollOffset % SCROLL_AREA_H;
    if (g_deviceData.screen != DisplayType::ST7789) {
        return;
    }
    Adafruit_ST7789* pDisp           = (Adafruit_ST7789*)g_disp;
    uint16_t         absoluteScrollY = g_scrollY + STATUS_BAR_H;
    uint8_t          args[2]         = { (uint8_t)(absoluteScrollY >> 8), (uint8_t)(absoluteScrollY & 0xFF) };
    pDisp->sendCommand(0x37, args, 2);  // VSCSAD
}

// Reset scroll state and clear the ENTIRE framebuffer (status bar and footer
// included). Used by splash / info screens that paint full-screen content.
// goAndResetConversationScreen() (the conversation-mode entry point) calls this AND then
// redraws the status bar and footer borders on top.
void hwScrollReset() {
    g_scrollY = 0;
    g_drawY   = 0;
    hwScrollTo(0);
    if (g_deviceData.screen == DisplayType::ST7789) {
        g_disp->fillScreen(ST77XX_BLACK);
    }
    // Force status bar to redraw next time it's polled (state cache is now stale).
    g_statusBarDirty = true;
}


// Bar drawing (status bar + input footer) + the per-indicator color palette live in bars.ino — see that file for redrawStatusBar(),
// redrawInputFooter(), drawIndicatorAt/CapsAt/PersonAt, and the ICON_*_COLOR / KB_BAR_*_COLOR / STATUS_BAR_*_COLOR macros.


void setupDisplay() {
    if (g_deviceData.screen == DisplayType::ST7789) {
        Adafruit_ST7789* pDisp = new Adafruit_ST7789(TFT_CS, TFT_DC, TFT_RST);

        pDisp->init(240, 320);
        // Portrait. Hardware scroll operates in framebuffer-native (portrait)
        // coordinates; using setRotation(1) would make the scroll go sideways
        // from the user's POV. We use rotation 2 (180° flip vs rotation 0) so
        // that GFX's framebuffer-bottom matches the user's visual bottom on this
        // specific module — without this the chat scroll would feel inverted
        // (new lines at top, scrolling down). See docs/howto_hardware_scrolling.md.
        pDisp->setRotation(2);

        g_disp = pDisp;

        // Declare the scroll area (idempotent, sent only once).
        hwScrollSetupArea();
        hwScrollTo(0);
    } else {
        ESP_LOGW(TAG_MM, "setupDisplay: DISPLAY_TYPE_NOT_CONFIGURED");
    }

#if TFT_BL >= 0
    pinMode(TFT_BL, OUTPUT);
    analogWrite(TFT_BL, 255);  // full brightness at boot
#endif
    g_lastActivityMs = millis();
}


// Apply a power state to the panel. Idempotent.
void setDisplayPowerState(DisplayPowerState nextState) {
    if (nextState == g_displayPowerState) {
        return;
    }

    ESP_LOGI(TAG_MM, "setDisplayPowerState(%d -> %d)", (int)g_displayPowerState, (int)nextState);

    if (g_deviceData.screen == DisplayType::ST7789) {
        Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

        switch (nextState) {
        case DISPLAY_ON:
            pDisp->enableDisplay(true);
#if TFT_BL >= 0
            analogWrite(TFT_BL, 255);
#endif
            break;

        case DISPLAY_DIMMED:
#if TFT_BL >= 0
            analogWrite(TFT_BL, 128);  // 50% backlight
#endif
            // No panel-level dim command on ST7789 (the controller doesn't expose
            // a contrast register). Without a PWM backlight pin this transition
            // is silent — only the timer keeps progressing toward DISPLAY_OFF.
            break;

        case DISPLAY_OFF:
#if TFT_BL >= 0
            analogWrite(TFT_BL, 0);
#endif
            pDisp->enableDisplay(false);  // controller stops driving the matrix
            break;
        }
    }

    g_displayPowerState = nextState;
}


// Reset the idle timer. If the screen was dim or off, restore it to ON and
// return true so callers can swallow the input that caused the wake.
bool noteUserActivity() {
    g_lastActivityMs = millis();
    if (g_displayPowerState != DISPLAY_ON) {
        setDisplayPowerState(DISPLAY_ON);
        return true;  // caller should treat this as a wake event, not a real input
    }
    return false;
}


// Drive the dim/off state machine. Call from loop().
void updateDisplayPowerState() {
    unsigned long idleMs = millis() - g_lastActivityMs;

    if (g_displayPowerState == DISPLAY_ON && idleMs >= DISPLAY_IDLE_BEFORE_DIM_MS) {
        setDisplayPowerState(DISPLAY_DIMMED);
    } else if (g_displayPowerState == DISPLAY_DIMMED && idleMs >= DISPLAY_IDLE_BEFORE_OFF_MS) {
        setDisplayPowerState(DISPLAY_OFF);
    }
}


void showSplashScreen() {
    // Show image buffer on the display hardware.
    // Since the buffer is intialized with an Adafruit splashscreen internally, this will display the splashscreen.

    if (g_deviceData.screen == DisplayType::ST7789) {
        Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

        g_inConversationMode = false;  // fullscreen mode, suppress status bar repaint
        hwScrollReset();               // ensure we draw at framebuffer Y = screen Y = 0

        // Vertical layout: trois gaps égaux entourent le texte et l'image. Le texte (default 5×7 font à setTextSize(2)) est traité comme 24 px de
        // hauteur — c'est la hauteur visuelle "encombrement" décidée côté UI, pas la hauteur de glyphe stricte (16 px) — et l'image est de
        // splash_bmp_h (128 px). gap = (FB_HEIGHT - kTitleH - splash_bmp_h) / 3 = (320 - 24 - 128) / 3 = 56 px → texte à Y=56, image à Y=136.
        // Avec setFont(NULL) le setCursor(y) cible le TOP du texte (pas la baseline comme avec les fontes GFX), et drawRGBBitmap place le coin
        // haut-gauche → on peut écrire les Y directement sans compensation.
        constexpr int16_t kTitleH = 24;
        const int16_t     gap     = (FB_HEIGHT - kTitleH - (int16_t)splash_bmp_h) / 3;

        // Title centered horizontally. Default 5×7 font at setTextSize(2) → 12 px advance per glyph. Text width = strlen × 12 ; centered X.
        pDisp->setFont(NULL);
        pDisp->setTextSize(2);
        pDisp->setTextColor(ST77XX_WHITE);
        const char* title  = "MiniMessenger !";
        int16_t     titleW = (int16_t)strlen(title) * 12;
        pDisp->setCursor((FB_WIDTH - titleW) / 2, gap);
        pDisp->print(title);

        // Logo Goku, centré horizontalement, positionné verticalement après texte + gap.
        pDisp->drawRGBBitmap((FB_WIDTH - splash_bmp_w) / 2, gap + kTitleH + gap, splash_bmp, splash_bmp_w, splash_bmp_h);

        delay(2'000);
    } else {
        ESP_LOGW(TAG_MM, "Display: no splash screen (display not configured)");
    }
}


// Replay every entry of the ring buffer through the same HW-scroll draw
// algorithm as addConversationBlock. After this:
//   - status bar and footer are untouched (protected by VSCRDEF — we only
//     fillRect the scroll area, never fillScreen)
//   - the latest block ends up at the bottom of the scroll area with older
//     blocks stacked above (or scrolled off the top if cumulated height
//     exceeds SCROLL_AREA_H) — visually identical to live message arrival
//   - g_drawY / g_scrollY are left in the "next slot" position so a new
//     addConversationBlock right after lands naturally below the last block
//
// Drop the in-memory conversation history and wipe the scroll area. After this call the ring buffer is empty, the HW scroll register is back
// at zero, and the panel's scroll zone is solid black. Status bar and footer are untouched — they live outside the VSCRDEF window and aren't
// affected by g_drawY / g_scrollY. Triggered by the "/clear" command. A subsequent addConversationBlock lands at the top of the scroll area
// because g_drawY = 0, exactly like a fresh boot.
void clearConversationHistory() {
    if (g_deviceData.screen != DisplayType::ST7789) {
        ESP_LOGW(TAG_MM, "clearConversationHistory: DISPLAY_TYPE_NOT_CONFIGURED");
        return;
    }
    ESP_LOGI(TAG_MM, "Clearing conversation history (%d block(s) discarded)", g_lineCount);
    g_lineHead  = 0;
    g_lineCount = 0;
    g_drawY     = 0;
    g_scrollY   = 0;
    hwScrollTo(0);
    g_disp->fillRect(0, SCROLL_AREA_Y_FB, FB_WIDTH, SCROLL_AREA_H, ST77XX_BLACK);
}


// Triggered by the `cmd redraw` command (see processPayloadAsCommand).
// We draw directly from the stored TextLine fields — no re-bound, no
// re-utf8-conversion, no re-alignment compute, no ring rewrite. Everything
// needed was captured at original send time.
void redrawAllConversations() {
    if (g_deviceData.screen != DisplayType::ST7789) {
        ESP_LOGW(TAG_MM, "redrawAllConversations: DISPLAY_TYPE_NOT_CONFIGURED");
        return;
    }
    ESP_LOGI(TAG_MM, "Full redraw — replaying %d block(s) from ring", g_lineCount);

    // Reset HW scroll state and wipe ONLY the scroll area.
    g_drawY   = 0;
    g_scrollY = 0;
    hwScrollTo(0);
    g_disp->fillRect(0, SCROLL_AREA_Y_FB, FB_WIDTH, SCROLL_AREA_H, ST77XX_BLACK);

    for (int k = 0; k < g_lineCount; k++) {
        const TextLine& line = lines[(g_lineHead + k) % MAX_LINES];
        uint16_t        H    = line.tsHeightWithBottomMargin + line.msgHeightWithBottomMargin;

        // Wrap avoidance, mirroring addConversationBlock: if the block would
        // cross the scroll-area top boundary, skip the remaining tail and
        // restart at scroll-offset 0, bumping the scroll register to swallow
        // the skipped pixels.
        if (g_drawY + H > SCROLL_AREA_H) {
            uint16_t skipped = SCROLL_AREA_H - g_drawY;
            g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, skipped, ST77XX_BLACK);
            g_drawY   = 0;
            g_scrollY = (g_scrollY + skipped) % SCROLL_AREA_H;
        }

        g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, H, ST77XX_BLACK);

        uint16_t fbY = g_drawY + SCROLL_AREA_Y_FB;
        if (line.ts[0] != '\0') {
            g_disp->setFont(NULL);
            g_disp->setTextSize(line.tsFontSize);
            g_disp->setTextColor(line.tsColor);
            g_disp->setCursor(line.tsX - line.tsBounds[BOX_X], fbY - line.tsBounds[BOX_Y]);
            g_disp->print(line.ts);
            fbY += line.tsHeightWithBottomMargin;
        }
        g_disp->setFont(&CONVO_MSG_FONT);
        g_disp->setTextSize(line.msgFontSize);
        g_disp->setTextColor(line.msgColor);
        g_disp->setCursor(line.msgX - line.msgBounds[BOX_X], fbY - line.msgBounds[BOX_Y]);
        g_disp->print(line.msg);

        g_drawY   = (g_drawY + H) % SCROLL_AREA_H;
        g_scrollY = (g_scrollY + H) % SCROLL_AREA_H;
        hwScrollTo(g_scrollY);
    }
}


// utf8ToLatin1 lives in strings.ino now — see the forward decl in the block at the top of this file.

// Drop a single line into the conversation scroll area, with optional two-column layout for command listings.
//
// Two overloads share the same impl below; the single-arg one is a thin forwarder that passes an empty `right`. Behavior:
//   - `right` empty  → just `left`, left-aligned at x=2. Used for banners ("Commands:"), status messages ("Forgot: X"), errors.
//   - `right` filled → `left` at x=2, `right` at x=INFO_LINE_RIGHT_COL_X. Used for /help listings (cmd name + description on the same row).
//
// Overload disambiguation: the 1-string version takes a uint16_t color as 2nd arg; the 2-string takes a String. A literal "foo" as 2nd arg
// resolves to String (direct match), beating the uint16_t version which would require a const-char* → uint16_t conversion that doesn't exist.
// A numeric color as 2nd arg resolves to uint16_t (direct match) over String (would need a user-defined conversion). No ambiguity in practice.
//
// HW-scroll primitives (g_drawY / g_scrollY / hwScrollTo) make successive calls accumulate visually like any other conversation content,
// and hwScrollReset() drops the lot during a screen switch.
//
// Defaults: pink CMD color + CONVO_CMD_FONT; both overridable.

void printInfoLine(const String& left, const String& right, uint16_t color, const GFXfont* font) {
    if (g_deviceData.screen != DisplayType::ST7789) {
        return;
    }

    // UTF-8 → Latin-1: bundled FreeSans*_latin1 fonts cap at 0xFF. Mirrors what addConversationBlock does to its message before drawing.
    char leftBuf[CONVO_MSG_MAX_LEN];
    strncpy(leftBuf, left.c_str(), sizeof(leftBuf) - 1);
    leftBuf[sizeof(leftBuf) - 1] = '\0';
    utf8ToLatin1(leftBuf);

    char rightBuf[CONVO_MSG_MAX_LEN];
    strncpy(rightBuf, right.c_str(), sizeof(rightBuf) - 1);
    rightBuf[sizeof(rightBuf) - 1] = '\0';
    utf8ToLatin1(rightBuf);
    const bool hasRight = (rightBuf[0] != '\0');

    g_disp->setFont(font);
    g_disp->setTextSize(CONVO_MSG_FONT_SIZE);
    g_disp->setTextColor(color);

    // Measure left for the row height. getTextBounds returns the bbox of the EXACT string (not the font's max metrics) — lines without
    // descenders take ~3-4 px less, saving vertical space across cumulative /help listings on the 320 px tall screen. With GFX fonts the
    // returned y is negative (bbox top above the baseline-anchored cursor) and we compensate at setCursor time below.
    int16_t  bx, by;
    uint16_t bw, bh;
    g_disp->getTextBounds(leftBuf, 0, 0, &bx, &by, &bw, &bh);

    // Defensive: if the right column has glyphs reaching further down/up than the left, take the max bbox height so the row reserves enough
    // vertical room. Same font / size means by is typically identical for both strings, so we keep `by` from the left for the cursor offset.
    if (hasRight) {
        int16_t  rbx, rby;
        uint16_t rbw, rbh;
        g_disp->getTextBounds(rightBuf, 0, 0, &rbx, &rby, &rbw, &rbh);

        // Important, la hauteur de ligne est la plus grande hauteur des 2 bouts de texte
        if (rbh > bh) {
            bh = rbh;
        }
    }

    const uint16_t lineH = bh + CONVO_HELP_MARGIN_BOTTOM;

    // Wrap avoidance, mirrors addConversationBlock: if the line would overflow the scroll area bottom, paint the leftover tail black and
    // restart at offset 0, bumping the scroll register to swallow the skipped pixels.
    if (g_drawY + lineH > SCROLL_AREA_H) {
        uint16_t skipped = SCROLL_AREA_H - g_drawY;
        g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, skipped, ST77XX_BLACK);
        g_drawY   = 0;
        g_scrollY = (g_scrollY + skipped) % SCROLL_AREA_H;
    }

    // Black background + draw left at x=2. setCursor compensation: top-of-box Y minus the (negative) by gives the baseline anchor.
    g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, lineH, ST77XX_BLACK);
    g_disp->setCursor(2 - bx, g_drawY + SCROLL_AREA_Y_FB - by);
    g_disp->print(leftBuf);

    // Draw right at the fixed column, same baseline as left.
    if (hasRight) {
        g_disp->setCursor(INFO_LINE_RIGHT_COL_X, g_drawY + SCROLL_AREA_Y_FB - by);
        g_disp->print(rightBuf);
    }

    // Bump the HW scroll — this is what makes successive calls accumulate visually.
    g_drawY   = (g_drawY + lineH) % SCROLL_AREA_H;
    g_scrollY = (g_scrollY + lineH) % SCROLL_AREA_H;
    hwScrollTo(g_scrollY);
}

// Single-string forwarder — kept so existing call sites that pass just a message (with or without an explicit color) keep working unchanged.
void printInfoLine(const String& msg, uint16_t color, const GFXfont* font) {
    printInfoLine(msg, String(), color, font);
}

void addConversationBlock(String ts, String msg, uint16_t msgColor, Align align) {
    char msgBuf[CONVO_MSG_MAX_LEN];
    strncpy(msgBuf, msg.c_str(), sizeof(msgBuf) - 1);
    msgBuf[sizeof(msgBuf) - 1] = '\0';
    utf8ToLatin1(msgBuf);
    // Then use msgBuf everywhere instead of msg.c_str() for the on-screen draw.

    // Timestamp clustering: if a timestamp was drawn less than
    // CONVO_TS_HIDE_THRESHOLD_S ago, drop this one to declutter. Only "real"
    // timestamps (non-empty ts) update the tracker — status lines like
    // "Lost server" / "Ready !" pass ts="" and don't reset the window.
    if (!ts.isEmpty()) {
        time_t now = time(nullptr);
        if (now - g_lastShownTsEpoch < CONVO_TS_HIDE_THRESHOLD_S) {
            ts = "";  // suppress the timestamp; the rest of the function handles it
        }
        // Reset dans tous les cas, on compare chaque message à la date de son précédent (meme si TS pas affiché)
        g_lastShownTsEpoch = now;
    }

    // Dimension TS
    uint16_t tsBlockHWithMargin = 0;

    static int16_t tsBox[4] = { 0, 0, 0, 0 };  // x1, y1, w, h

    /*
1. Pourquoi getTextBounds retourne des valeurs de y négatives avec certaines polices comme FreeSans9pt8b ?
Dans les bibliothèques graphiques comme Adafruit_GFX, le système de coordonnées pour le texte est basé sur le point de base (baseline) du texte. Voici ce qui se passe :


Origine du texte :
Le point (0, 0) pour le texte est généralement placé sur la ligne de base (baseline) du texte, c'est-à-dire la ligne sur laquelle reposent les lettres (sans les descendantes comme "j", "p", "g", etc.).

Valeurs négatives de y :
Pour les polices avec des ascendantes (parties des lettres qui montent au-dessus de la ligne de base, comme "h", "b", "d"), la coordonnée y du rectangle englobant (getTextBounds) peut être négative. Cela signifie que la partie supérieure du texte s'étend au-dessus de la ligne de base.

Exemple : Si la police a une hauteur de 9 pixels et que la ligne de base est à y=0, le sommet des ascendantes pourrait être à y=-2 (selon la police).

Polices comme FreeSans9pt8b :
Ces polices sont souvent conçues avec des ascendantes et descendantes importantes, ce qui explique pourquoi getTextBounds peut retourner des valeurs de y négatives.


Dans la méthode getTextBounds de la bibliothèque Adafruit_GFX, les paramètres retournés sont généralement les suivants :

x : Coordonnée horizontale du coin supérieur gauche du rectangle englobant.
y : Coordonnée verticale du coin supérieur gauche du rectangle englobant (peut être négative si le texte dépasse au-dessus de la ligne de base).
w : Largeur du rectangle englobant.
h : Hauteur totale du rectangle englobant, c'est-à-dire la distance entre le point le plus haut (ascendantes) et le point le plus bas (descendantes) du texte.
Pas besoin d'ajouter l'opposé de y : h est déjà calculé comme la distance entre le point le plus haut (même s'il est au-dessus de la ligne de base, donc y négatif) et le point le plus bas.
*/

    if (!ts.isEmpty()) {
        g_disp->setFont(NULL);
        g_disp->setTextSize(CONVO_TS_FONT_SIZE);
        g_disp->getTextBounds(ts, 0, 0, &tsBox[BOX_X], &tsBox[BOX_Y], (uint16_t*)&tsBox[BOX_W], (uint16_t*)&tsBox[BOX_H]);

        tsBlockHWithMargin = tsBox[BOX_H] + CONVO_TS_MARGIN_BOTTOM;
    }

    // Dimension msg
    uint16_t       msgBlockHWithMargin = 0;
    static int16_t msgBox[4]           = { 0, 0, 0, 0 };

    g_disp->setFont(&CONVO_MSG_FONT);
    g_disp->setTextSize(CONVO_MSG_FONT_SIZE);
    g_disp->getTextBounds(msgBuf, 0, 0, &msgBox[BOX_X], &msgBox[BOX_Y], (uint16_t*)&msgBox[BOX_W], (uint16_t*)&msgBox[BOX_H]);
    msgBlockHWithMargin = msgBox[BOX_H] + CONVO_MSG_MARGIN_BOTTOM;


    uint16_t H = tsBlockHWithMargin + msgBlockHWithMargin;

    // Compute X alignment in screen-space (g_disp->width() reflects rotation 0
    // → 240 px, so this works directly in framebuffer coords too).
    uint16_t tsX = 0, msgX = 0;
    if (align == RIGHT) {
        tsX  = g_disp->width() - tsBox[BOX_W];
        msgX = g_disp->width() - msgBox[BOX_W];
    } else if (align == CENTER) {
        tsX  = (g_disp->width() - tsBox[BOX_W]) / 2;
        msgX = (g_disp->width() - msgBox[BOX_W]) / 2;
    }

    // === Maintain the logical ring buffer (state only — not used for drawing) ===
    while (g_lineCount >= MAX_LINES) {
        g_lineHead = (g_lineHead + 1) % MAX_LINES;
        g_lineCount--;
    }
    int writeIdx    = (g_lineHead + g_lineCount) % MAX_LINES;
    lines[writeIdx] = TextLine(ts,
                               CONV0_TS_COLOR,
                               NULL,
                               CONVO_TS_FONT_SIZE,
                               tsBlockHWithMargin,
                               tsX,
                               tsBox,
                               msgBuf,
                               msgColor,
                               &CONVO_MSG_FONT,
                               CONVO_MSG_FONT_SIZE,
                               msgBlockHWithMargin,
                               msgX,
                               msgBox);
    g_lineCount++;

    // === HW scroll draw path: write the block directly into the framebuffer
    // ring, then bump VSCSAD by H. Old content scrolls off the top as the
    // controller re-maps the visible window — no full redraw. ===

    // Wrap avoidance: if the block would cross the scroll-area top boundary,
    // skip the remaining tail and restart at scroll-offset 0. The skipped tail
    // is wiped (otherwise stale content from a previous wrap would scroll back
    // into view), and the same number of pixels is added to the scroll so the
    // user perceives a single (slightly bigger than H) smooth scroll.
    // NOTE: `g_drawY` and `g_scrollY` are offsets INSIDE the scroll area
    // ([0, SCROLL_AREA_H)). All fillRect / setCursor positions are absolute
    // framebuffer Y, so we add SCROLL_AREA_Y_FB (= STATUS_BAR_H) at draw time.
    if (g_drawY + H > SCROLL_AREA_H) {
        uint16_t skipped = SCROLL_AREA_H - g_drawY;
        g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, skipped, ST77XX_BLACK);
        g_drawY   = 0;
        g_scrollY = (g_scrollY + skipped) % SCROLL_AREA_H;
    }

    // Wipe the strip we're about to overdraw (stale content from the previous
    // wrap of the framebuffer ring).
    g_disp->fillRect(0, g_drawY + SCROLL_AREA_Y_FB, FB_WIDTH, H, ST77XX_BLACK);

    // Draw TS then MSG at framebuffer Y = g_drawY + SCROLL_AREA_Y_FB.
    // getTextBounds returns negative tsBox/msgBox y for ascender-using fonts,
    // so we offset the cursor by `- bounds[BOX_Y]` (cf. the big French comment
    // above).
    uint16_t fbY = g_drawY + SCROLL_AREA_Y_FB;
    if (!ts.isEmpty()) {
        g_disp->setFont(NULL);
        g_disp->setTextSize(CONVO_TS_FONT_SIZE);
        g_disp->setTextColor(CONV0_TS_COLOR);
        g_disp->setCursor(tsX - tsBox[BOX_X], fbY - tsBox[BOX_Y]);
        g_disp->print(ts);
        fbY += tsBlockHWithMargin;
    }
    g_disp->setFont(&CONVO_MSG_FONT);
    g_disp->setTextSize(CONVO_MSG_FONT_SIZE);
    g_disp->setTextColor(msgColor);
    g_disp->setCursor(msgX - msgBox[BOX_X], fbY - msgBox[BOX_Y]);
    g_disp->print(msgBuf);

    // Bump scroll-area cursor and the user-visible scroll register.
    g_drawY   = (g_drawY + H) % SCROLL_AREA_H;
    g_scrollY = (g_scrollY + H) % SCROLL_AREA_H;
    hwScrollTo(g_scrollY);
}


// ================================================================================
// Messaging
// ================================================================================

void setBroadcastRecipient() {
    snprintf(g_mqttOutgoingRecipientTopic, MQTT_TOPIC_SIZE, "msg/broadcast");
    ESP_LOGI(TAG_MQTT, "Setting recipient topic to [%s]", g_mqttOutgoingRecipientTopic);
}

void setUnicastRecipient(int recipientDeviceId) {
    snprintf(g_mqttOutgoingRecipientTopic, MQTT_TOPIC_SIZE, "msg/unicast/%d", recipientDeviceId);
    ESP_LOGI(TAG_MQTT, "Setting recipient topic to [%s]", g_mqttOutgoingRecipientTopic);
}

// Called once per successful MQTT (re)connect. Two distinct cases:
//   - first connect after boot: we were sitting on the info screen waiting for MQTT to come up. Transition to conversation mode via goAndResetConversationScreen
//     (which wipes the scroll area and paints the status bar + footer borders), then drop a "Ready !" line in the conversation.
//   - any later reconnect (we lost connection mid-conversation and got it back): we stay in conversation mode — the "Lost server" / "Trying to
//     reconnect..." stack is still visible — and just append "Ready !" so the reconnect is acknowledged in-line.
void onMQTTReconnected() {
    if (!g_inConversationMode) {
        goAndResetConversationScreen();
    }
    addConversationBlock("", "Ready !", CONVO_INFO_COLOR, CENTER);
}

// ----------------------------------------------------------------------------
// Local commands + message funnel
//
// routeMessage() (below) is the SINGLE insertion point for any complete payload landing in this device. It wakes the screen, hands the message
// to processPayloadAsCommand() (defined in commands.ino) for /cmd interpretation, and only routes to display / MQTT-republish if the message
// wasn't consumed as a command. The full command vocabulary (CMD_* / GROUP_* constants, dispatchers, help printers) lives in commands.ino.
// ----------------------------------------------------------------------------


// Diagnostic dump of silicon identity (chip model, revision, cores, features, package, MACs, flash, IDF version, reset reason). Sent both to the
// serial log (multi-line, with structured fields) and to the conversation in compact form so the info is visible on the device too. See
// docs/howto_efuse.md for what each line means and which API gives it.
void dumpChipInfo() {
    esp_chip_info_t info;
    esp_chip_info(&info);

    ESP_LOGI(TAG_MM, "--- /dbg chip ---");
    ESP_LOGI(TAG_MM, "Chip: model=%d revision=%d cores=%d features=0x%lx", (int)info.model, info.revision, info.cores, (unsigned long)info.features);
    ESP_LOGI(TAG_MM,
             "Caps: WiFi:%s BT:%s BLE:%s EmbFlash:%s EmbPSRAM:%s",
             (info.features & CHIP_FEATURE_WIFI_BGN) ? "y" : "-",
             (info.features & CHIP_FEATURE_BT) ? "y" : "-",
             (info.features & CHIP_FEATURE_BLE) ? "y" : "-",
             (info.features & CHIP_FEATURE_EMB_FLASH) ? "y" : "-",
             (info.features & CHIP_FEATURE_EMB_PSRAM) ? "y" : "-");
    ESP_LOGI(TAG_MM, "CPU: %u MHz", ESP.getCpuFreqMHz());
    ESP_LOGI(TAG_MM, "Flash: size=%u mode=%d speed=%u Hz", ESP.getFlashChipSize(), ESP.getFlashChipMode(), ESP.getFlashChipSpeed());

    uint8_t mac[6];
    // Use ESP_MAC_EFUSE_FACTORY (direct silicon read) instead of esp_efuse_mac_get_default() — see identifyDevice() for the full explanation
    // of why the latter returns ESP_OK + zeros when called before the IDF base-MAC cache has been populated.
    esp_read_mac(mac, ESP_MAC_EFUSE_FACTORY);
    ESP_LOGI(TAG_MM, "MAC base/STA: %02X:%02X:%02X:%02X:%02X:%02X", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    esp_read_mac(mac, ESP_MAC_BT);
    ESP_LOGI(TAG_MM, "MAC BT:       %02X:%02X:%02X:%02X:%02X:%02X", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);

    ESP_LOGI(TAG_MM, "Sketch: size=%u free=%u", ESP.getSketchSize(), ESP.getFreeSketchSpace());
    ESP_LOGI(TAG_MM, "IDF: %s", esp_get_idf_version());
    ESP_LOGI(TAG_MM, "Last reset reason: %d", (int)esp_reset_reason());

    // Echo a compact summary into the conversation so it's visible on-device too.
    char line[64];
    snprintf(line, sizeof(line), "chip model=%d rev=%d cpu=%uMHz", (int)info.model, info.revision, ESP.getCpuFreqMHz());
    addConversationBlock("", line, CONVO_CMD_COLOR, LEFT);
    snprintf(line, sizeof(line), "flash=%uKB reset=%d", ESP.getFlashChipSize() / 1024, (int)esp_reset_reason());
    addConversationBlock("", line, CONVO_CMD_COLOR, LEFT);
}


// Diagnostic dump of heap state. "free" is the sum of all free bytes; "largest" is the biggest single contiguous run (the one mbedtls /
// TLS / SPI buffers need). "min ever" is the historical low-water mark — a value that keeps dropping over time is the classic signature
// of a leak. Sketch / partition counters are flash-side, not RAM, but useful in the same diagnostic dump.
void dumpMemInfo() {
    uint32_t totalHeap   = ESP.getHeapSize();
    uint32_t freeHeap    = ESP.getFreeHeap();
    uint32_t largest     = ESP.getMaxAllocHeap();
    uint32_t minEverFree = ESP.getMinFreeHeap();
    uint32_t usedHeap    = totalHeap - freeHeap;

    ESP_LOGI(TAG_MM, "--- /dbg mem ---");
    ESP_LOGI(TAG_MM, "Heap: total=%u used=%u free=%u largest=%u min-ever-free=%u", totalHeap, usedHeap, freeHeap, largest, minEverFree);
    ESP_LOGI(TAG_MM, "Heap fragmentation: %u%% (= 1 - largest/free)", freeHeap > 0 ? (100 - (largest * 100 / freeHeap)) : 0);

    // PSRAM is only present on certain ESP32 variants (e.g. WROVER). On chips without PSRAM these calls return 0.
    if (ESP.getPsramSize() > 0) {
        ESP_LOGI(TAG_MM, "PSRAM: total=%u free=%u largest=%u", ESP.getPsramSize(), ESP.getFreePsram(), ESP.getMaxAllocPsram());
    } else {
        ESP_LOGI(TAG_MM, "PSRAM: none");
    }

    // Stack high-water-mark for the task currently running this code (typically the Arduino loop task). Lower number = closer to overflow.
    // Returns the minimum free stack the task has ever had since boot, in WORDS (uint32_t units on ESP32) — multiply by 4 for bytes.
    UBaseType_t stackHWMWords = uxTaskGetStackHighWaterMark(NULL);
    ESP_LOGI(TAG_MM, "Loop task stack: min-ever-free=%u bytes", (unsigned)(stackHWMWords * 4));

    ESP_LOGI(TAG_MM, "Sketch: size=%u free=%u", ESP.getSketchSize(), ESP.getFreeSketchSpace());

    // Echo a compact summary into the conversation.
    char line[64];
    snprintf(line, sizeof(line), "heap free=%u largest=%u", freeHeap, largest);
    addConversationBlock("", line, CONVO_CMD_COLOR, LEFT);
    snprintf(line, sizeof(line), "min-ever-free=%u frag=%u%%", minEverFree, freeHeap > 0 ? (100 - (largest * 100 / freeHeap)) : 0);
    addConversationBlock("", line, CONVO_CMD_COLOR, LEFT);
}

void routeMessage(const String& message, MessageSource source) {
    //ESP_LOGI(TAG_MM, "routing msg [%s]", message.c_str());

    // Step 1 — always wake the screen. We ignore noteUserActivity()'s "was sleeping"
    // return value: unlike a stray keypress (which is swallowed on wake to avoid
    // typing accidental characters), a command-or-message must actually run on wake-up too.
    noteUserActivity();

    // Step 2 — if it's a known command, execute and stop. No display, no
    // republish — this is the whole point of the funnel.
    if (processPayloadAsCommand(message)) {
        return;
    }

    // Step 3 — render in the conversation; for LOCAL, also publish so peers see it.
    if (source == MessageSource::REMOTE) {
        addConversationBlock(getCurrentTime(), message, ST77XX_YELLOW, LEFT);
    }
    // LOCAL (serial ou BT)
    else {
        addConversationBlock(getCurrentTime(), message, ST77XX_WHITE, RIGHT);
        bool published = mqttPushFormattedMessage(g_mqttOutgoingRecipientTopic, message.c_str());
        if (!published) {
            // Naive WhatsApp-style "send failed" indicator: append a second block right under the original one, in error red, prefixed with [ERROR] so
            // the user knows that specific message didn't reach the broker. To be replaced later with a per-message status icon (sending / sent / failed)
            // overlaid on the original block — but the present block-pair is enough to surface the failure without any new UI machinery.
            addConversationBlock("", "[ERROR] " + message, CONVO_ERROR_COLOR, RIGHT);
        }
    }
}



// ================================================================================
// Entrypoints
// ================================================================================

void goAndResetConversationScreen() {
    if (g_deviceData.screen == DisplayType::ST7789) {
        // hwScrollReset() wipes the entire framebuffer (status bar / footer
        // included). Right after, we mark conversation mode and repaint the
        // status bar + the empty input footer.
        hwScrollReset();
        g_inConversationMode = true;
        redrawStatusBar();
        redrawInputFooter();
    } else {
        ESP_LOGW(TAG_MM, "goAndResetConversationScreen: DISPLAY_TYPE_NOT_CONFIGURED");
    }
}

// Returns to the nominal 3-zone screen (upper status bar + scroll area + footer) and repaints all three from their in-memory state. Called by
// "/dbg redraw" and by the "/status" timeout in loop(). Also clears g_statusScreenEndMs so a pending timeout doesn't fire a redundant revert
// when the user triggers a manual redraw mid-overlay.
void returnToConversationsScreen() {
    g_statusScreenEndMs = 0;
    goAndResetConversationScreen();  // HW scroll reset + repaint of status bar + footer
    redrawAllConversations();        // refill the scroll area from the ring buffer
}

// Print `value` at (x, y) wrapping to a second line at (x, y + lineH) if it doesn't fit in `availableWidth`. Both lines start at the same x.
// Returns the total vertical pixels consumed (lineH for a single line, 2*lineH if wrapped).
//
// Uses the default 5×7 font at setTextSize(2) → 12 px advance per glyph. The split prefers the rightmost natural separator
// (':', '.', '-', '_', '/', ' ') that keeps the first half within the line, so the cut feels meaningful (e.g. a MAC splits cleanly on a colon).
// Falls back to a hard cut at maxChars when no separator is present. A leading space on the second half is trimmed so the two lines align on x.
static int printValueWrapped(Adafruit_ST7789* pDisp, const String& value, int x, int y, int availableWidth, int lineH) {
    const int charW = 12;
    int       len   = value.length();
    pDisp->setCursor(x, y);
    if (len * charW <= availableWidth) {
        pDisp->print(value);
        return lineH;
    }
    int maxChars   = availableWidth / charW;
    int upperBound = (maxChars - 1 < len - 1) ? (maxChars - 1) : (len - 1);
    int breakAt    = -1;
    for (int i = upperBound; i > 0; i--) {
        char c = value[i];
        if (c == ':' || c == '.' || c == '-' || c == '_' || c == '/' || c == ' ') {
            breakAt = i + 1;  // first half keeps the separator for visual continuity
            break;
        }
    }
    if (breakAt < 1) {
        breakAt = maxChars;  // hard cut fallback
    }
    String first  = value.substring(0, breakAt);
    String second = value.substring(breakAt);
    while (second.length() > 0 && second[0] == ' ') {
        second.remove(0, 1);
    }
    pDisp->print(first);
    pDisp->setCursor(x, y + lineH);
    pDisp->print(second);
    return 2 * lineH;
}

// Draw one info-screen row: red header at colHeaders, white value at colValues (wrapped to a 2nd line via printValueWrapped if too wide).
// Returns the row height consumed (lineHeight or 2 × lineHeight when the value wrapped) so the caller can advance nextY accordingly.
static int drawInfoRow(Adafruit_ST7789* pDisp, const char* header, const String& value, int colHeaders, int colValues, int nextY, int lineHeight) {
    pDisp->setTextSize(2);
    pDisp->setCursor(colHeaders, nextY);
    pDisp->setTextColor(ST77XX_RED);
    pDisp->print(header);
    pDisp->setTextColor(ST77XX_WHITE);
    return printValueWrapped(pDisp, value, colValues, nextY, FB_WIDTH - colValues, lineHeight);
}

void showUpdatedInfoScreen() {
    if (g_deviceData.screen != DisplayType::ST7789) {
        ESP_LOGW(TAG_MM, "showUpdatedInfoScreen: DISPLAY_TYPE_NOT_CONFIGURED");
        return;
    }

    String mac = getRealHardwareMAC();

    // Diagnostic: trace every entry to this function with the exact state we're about to draw. Lets us tell apart 3 scenarios when the screen
    // shows scrambled data after /status: (1) called multiple times in rapid succession (double-render race), (2) called once with wrong data
    // (state-read bug), (3) called once with correct data (purely a rendering / VRAM-residue issue on the ST7789 side).
    ESP_LOGI(TAG_MM,
             "showUpdatedInfoScreen(): mac=%s ssid=%s ip=%s mqtt=%d ble=%d wifiState=%d",
             mac.c_str(),
             WiFi.SSID().c_str(),
             WiFi.localIP().toString().c_str(),
             (int)g_mqttClient.connected(),
             (int)g_kb.isFullyConnected(),
             (int)wifiGetState());


    Adafruit_ST7789* pDisp = (Adafruit_ST7789*)g_disp;

    g_inConversationMode = false;  // fullscreen mode, suppress status bar repaint
    hwScrollReset();               // info screen draws at fixed coordinates, scroll must be 0

    pDisp->setFont(NULL);  // font par défaut

    int colHeaders      = 2;
    int colValues       = 66;
    int lineHeight      = 22;
    int separatorHeight = 16;

    int nextY = 0;

    // Top rows: device identity — always shown regardless of WiFi state since these don't depend on the network being up.
    // Combined "ID: <id> <name>" row — replaces the previous separate "ID:" / "Name:" rows so the screen reclaims one row (~22 px) for the rest of
    // the status info. snprintf into a stack buffer keeps the formatting explicit and avoids the 3-alloc String-concat chain.
    char idAndNameBuf[20];  // worst case: "999 PROTO_999\0" = 14 bytes — 20 leaves slack for a longer namePrefix in the future.
    snprintf(idAndNameBuf, sizeof(idAndNameBuf), "%d %s", g_deviceData.deviceId, g_deviceData.name());
    nextY += drawInfoRow(pDisp, "ID:", idAndNameBuf, colHeaders, colValues, nextY, lineHeight);
    nextY += drawInfoRow(pDisp, "Owner:", String(g_deviceData.pseudo), colHeaders, colValues, nextY, lineHeight);
    nextY += drawInfoRow(pDisp, "MAC:", mac, colHeaders, colValues, nextY, lineHeight);

    nextY += separatorHeight;
    nextY += drawInfoRow(pDisp, "BTKB:", g_kb.isFullyConnected() ? "Connected" : "Not found", colHeaders, colValues, nextY, lineHeight);
    nextY += separatorHeight;

    // Branch on the current WiFi state — in PORTAL we replace the SSID/IP/MQTT/TIME rows with config instructions, otherwise we keep the
    // standard runtime info layout. The "Connecting…" / "Lost" variants reuse the SSID/IP rows with placeholder values so the row positions
    // stay stable across transitions (less visual jitter when state changes between two info-screen refreshes).
    WifiState st = wifiGetState();
    if (st == WifiState::PORTAL) {
        drawPortalInstructions(pDisp, nextY, colHeaders, colValues, lineHeight);
    } else {
        String ssidStr = (st == WifiState::CONNECTED) ? WiFi.SSID() : String("(searching)");
        String ipStr;
        if (WiFi.status() == WL_CONNECTED) {
            ipStr = WiFi.localIP().toString();
        } else if (st == WifiState::TRYING_KNOWN) {
            ipStr = "Connecting...";
        } else if (st == WifiState::LOST) {
            ipStr = "Lost, retrying";
        } else {
            ipStr = "Booting...";
        }
        nextY += drawInfoRow(pDisp, "SSID:", ssidStr, colHeaders, colValues, nextY, lineHeight);
        nextY += drawInfoRow(pDisp, "IP:", ipStr, colHeaders, colValues, nextY, lineHeight);
        nextY += drawInfoRow(pDisp, "MQTT:", g_mqttClient.connected() ? "OK" : "NOT OK", colHeaders, colValues, nextY, lineHeight);
        nextY += drawInfoRow(pDisp, "NTP:", String(getTimezoneLabel()), colHeaders, colValues, nextY, lineHeight);
    }

    nextY += separatorHeight;

    // Heap row — always shown, regardless of WiFi state. The largest contiguous block is the figure that matters for the TLS handshake (compared
    // against MQTT_TLS_MIN_FREE_HEAP_B in mqttReconnectAttempt()); the free figure is the headline number most users expect to see. Format keeps both
    // values on one row to avoid stealing two info-screen lines.
    char heapStr[24];
    snprintf(heapStr, sizeof(heapStr), "%u/%u", (unsigned)ESP.getMaxAllocHeap(), (unsigned)ESP.getFreeHeap());
    nextY += drawInfoRow(pDisp, "HEAP:", String(heapStr), colHeaders, colValues, nextY, lineHeight);
    nextY += drawInfoRow(pDisp, "HELP:", "/help", colHeaders, colValues, nextY, lineHeight);
}

// Single funnel for all event-driven info-screen refreshes. Callers (wifiTransitionTo, mqttReconnectAttempt, BLE connect callback, setupNTP, …) call
// this without checking whether the info screen is currently visible — the gate is here, so we never repaint when the user is in conversation
// mode (would clobber the chat). Safe to call from any hook on any state transition; no-op when the screen isn't ours.
void refreshInfoScreenIfShown() {
    if (!g_inConversationMode) {
        showUpdatedInfoScreen();
    }
}


void setupFontTests() {
    // ==== Font default
    // lineAdvance : 8
    // Bounds for text [jjjjj]: x1=0, y1=0, w=30, h=8
    // Bounds for text [Abefg]: x1=0, y1=0, w=30, h=8
    // Bounds for text [     ]: x1=0, y1=0, w=30, h=8
    // Bounds for text [_____]: x1=0, y1=0, w=30, h=8
    // ==== Font FreeSans9pt8b
    // yAdvance : 22
    // lineAdvance : 22
    // Bounds for text [aaaaa]: x1=1, y1=-9, w=49, h=10
    // Bounds for text [ttttt]: x1=1, y1=-11, w=24, h=12
    // Bounds for text [jjjjj]: x1=0, y1=-12, w=20, h=17
    // Bounds for text [Abefg]: x1=0, y1=-12, w=46, h=17
    // Bounds for text [     ]: x1=0, y1=0, w=20, h=0
    // Bounds for text [_____]: x1=0, y1=3, w=50, h=1

    uint8_t        textSize    = 1;
    String         texts[]     = { "aaaaa", "AAAAA", "ttttt", "qqqqq", "Attqq", "     ", "_____" };
    String         fontNames[] = { "default", "FreeSans9pt8b" };
    const GFXfont* fonts[]     = { NULL, &CONVO_MSG_FONT };

    int16_t  x1, y1;
    uint16_t w, h;

    for (int f = 0; f < 2; f++) {
        ESP_LOGD(TAG_MM, "==== Font %s", fontNames[f].c_str());
        const GFXfont* font = fonts[f];

        g_disp->setFont(font);
        g_disp->setTextSize(textSize);

        uint8_t yAdvance = 8;
        if (font != NULL) {
            yAdvance = pgm_read_byte(&font->yAdvance);
            ESP_LOGD(TAG_MM, "yAdvance: %u", yAdvance);
        }
        uint8_t lineAdvance = yAdvance * textSize;
        ESP_LOGD(TAG_MM, "lineAdvance: %u", lineAdvance);

        for (auto& text : texts) {
            g_disp->getTextBounds(text, 0, 0, &x1, &y1, &w, &h);
            ESP_LOGD(TAG_MM, "Bounds for [%s]: x1=%d y1=%d w=%u h=%u", text.c_str(), x1, y1, w, h);
        }
    }
}

void setup() {
    Serial.begin(115200);
    delay(1000);

    // Si rien n'apparait après cette ligne: ArduinoIDE: Tools >> Core Debug Level : Verbose ; puis reflash
    Serial.println("Setup logging...");
    // Install per-tag log levels before anything else logs:
    //   default = INFO ; BTKB = DEBUG (HID keystrokes are debug-level).
    setupLogging();
    ESP_LOGI(TAG_MM, "setup()");
    ESP_LOGI(TAG_MM, "=== minimessenger build %s %s ===", __DATE__, __TIME__);


    // Initialise le générateur de nombres aléatoires
    // Utilise une broche non connectée pour varier la graine (seed)
    randomSeed(analogRead(A0));  // A0 est une broche non connectée (bruit analogique)

    identifyDevice();

    setupDisplay();
    setupLeds();
    contactsSetup();

    //setupFontTests();

    showSplashScreen();
    showUpdatedInfoScreen();

    // Coex preference: WiFi over BT/BLE for the 2.4 GHz radio scheduler. Must be set BEFORE either WiFi.begin()-equivalents (i.e. before setupWifi
    // kicks the state machine) and before the BLE stack starts scanning. Defaults to BALANCE which lets the BLE keyboard's reconnect storm starve
    // WiFi assoc — see the rationale block on WIFI_BOOT_EXCLUSIVE_GRACE_MS in wifi.ino. Calling esp_coex_preference_set returns ESP_OK on success
    // and ESP_ERR_INVALID_ARG only for an out-of-range enum; we don't check the return because there's nothing sensible to do on failure here.
    esp_coex_preference_set(ESP_COEX_PREFER_WIFI);

    // WiFi FIRST — driver mode + hostname + NVS seed/load + WiFiManager config + state machine kick (TRYING_KNOWN or PORTAL). Non-blocking;
    // wifiTick() drives the actual association. We then pump wifiTick() in a tight loop for up to WIFI_BOOT_EXCLUSIVE_GRACE_MS so the first assoc
    // attempt completes with WiFi having exclusive radio access (no BLE keyboard scan/connect running in parallel). See the constant's comment in
    // wifi.ino for the full rationale and tuning advice. The loop exits early as soon as WiFi.status() == WL_CONNECTED.
    setupWifi();
    {
        unsigned long t0 = millis();
        while (WiFi.status() != WL_CONNECTED && millis() - t0 < WIFI_BOOT_EXCLUSIVE_GRACE_MS) {
            wifiTick(millis());
            delay(50);  // short yield — keeps the loop from hammering wifiTick() at CPU speed and gives the WiFi task room to run.
        }
        ESP_LOGI(TAG_MM,
                 "setup(): WiFi grace window elapsed after %lums (status=%d)",
                 millis() - t0,
                 (int)WiFi.status());
    }

    // BLE keyboard NOW that WiFi had its exclusive boot window. If WiFi is already CONNECTED here the keyboard's BLE storm has zero impact on it;
    // if WiFi is still trying, BLE will share the radio from now on under the ESP_COEX_PREFER_WIFI preference set above.
    setupKeyboard();

    // MQTT (server + callback registration) and TLS verification mode — independent of the WiFi link being up, safe at any point after setupWifi().
    setupMQTT();

    resetSerialBuffer();

    ESP_LOGI(TAG_MM, "setup() completed");
}

void resetSerialBuffer() {
    // Reset g_inNextCharIndex and clean buffer (then no need to add '\0' at end of current msg)
    g_inNextCharIndex = 0;
    for (int i = 0; i <= MAX_SERIAL_MSG_LENGTH; i++) {
        g_fullMsgFromSerial[i] = 0;
    }
}

bool g_firstLoop = true;

void loop() {
    unsigned long currentMillis = millis();  // Temps actuel en millisecondes depuis le démarrage

    g_kb.tryToMaintainConnection();

    // WiFi: drive the state machine in wifi.ino. Handles TRYING_KNOWN → CONNECTED / PORTAL transitions, portal HTTP traffic, rising/falling edge
    // banners, and the LOST → PORTAL fallback after extended outages. Non-blocking — BT keyboard and serial input keep running through outages.
    wifiTick(currentMillis);

    if (!g_mqttClient.connected()) {
        if (g_mqttWasConnected) {
            g_mqttWasConnected = false;
            ledSetState(LED_STATUS, LED_STATE_BLINK_FAST);

            // Only surface the MQTT-down banner when WiFi is actually up. If the link is down, the WiFi block above already showed "WiFi lost" and a
            // second "Lost server" banner is just noise about a known consequence. The internal flag flip + LED still happen regardless so the rising
            // edge logic and the status bar indicator stay accurate.
            if (WiFi.status() == WL_CONNECTED) {
                addConversationBlock("", "Lost server - Retrying...", CONVO_ERROR_COLOR, CENTER);
            }
        }

        // Don't even try to reconnect while the WiFi link is down. Without an IP the TLS connect just fails on DNS (errno 118 / "Host is unreachable",
        // lwIP rc -54) after wasting heap and spamming the serial console. The wifi state machine in wifi.ino is the one driving re-association; as soon
        // as it transitions back to CONNECTED, the time gate below will fire a fresh attempt. The delay grows exponentially across consecutive failures
        // (mqttReconnectDelayMs()) so a long broker outage doesn't burn TLS handshakes every 5 s.
        if (WiFi.status() == WL_CONNECTED && (g_firstLoop || currentMillis - g_mqttLastReconnectTryTimestampMs > mqttReconnectDelayMs())) {
            // Arm the back-off gate BEFORE the attempt: a TLS handshake can block
            // up to ~30 s; starting the timer from the call's *end* would compound.
            g_mqttLastReconnectTryTimestampMs = currentMillis;

            if (mqttReconnectAttempt()) {
                onMQTTReconnected();
            }
            // On failure: no delay() — the time gate above throttles the next retry.
        }
    } else {
        g_mqttClient.loop();

        // MQTT: Send keep-alive
        if (currentMillis - g_mqttPreviousKeepAliveTimestampMs >= MQTT_KEEPALIVE_INTERVAL_MS) {
            // Met à jour le temps de la dernière exécution
            g_mqttPreviousKeepAliveTimestampMs = currentMillis;

            // Send public liveness
            mqttSendAlive(2);
        }
    }

    // Contact tracking: expire any peer whose admin/live keepalive hasn't been refreshed for longer than CONTACT_TIMEOUT_MS. Placed after the MQTT
    // block so a freshly-received liveness on this same iteration (via g_mqttClient.loop() → onMqttIncomingMessage()) has already updated the slot's
    // lastSeenMs, avoiding a spurious one-cycle eviction. contactsTick() reads millis() itself rather than reusing the loop-top currentMillis — see
    // the comment above its definition for the underflow scenario this avoids.
    contactsTick();


#ifdef FLAG_READ_SERIAL_INPUTS
    // Add a new char to the buffer
    while (Serial.available() > 0) {
        g_inChar = Serial.read();

        // Wake screen on any serial char. If we were sleeping, swallow this char:
        // the user typed it to light the screen, not to compose a message.
        if (noteUserActivity()) {
            continue;
        }

        // 'Enter key' : send message
        if (g_inChar == '\n') {
            if (g_inNextCharIndex > 0) {
                ESP_LOGI(TAG_MM, "Serial: read msg #%u: %s", g_mqttOutputMsgId, g_fullMsgFromSerial);
                // Hand the buffer to the common funnel: wakes the screen, intercepts
                // CMD_* commands locally, otherwise renders RIGHT + publishes via
                // MQTT. Don't inline displayLocalMessage + mqttPushFormattedMessage
                // here — that would skip command interception and force every serial
                // 'cmd ...' string to be echoed/published to peers.
                routeMessage(String(g_fullMsgFromSerial), MessageSource::LOCAL);
                resetSerialBuffer();
            } else {
                // Message is empty. Do nothing
                ESP_LOGD(TAG_MM, "Serial: empty message, skipping publish");
            }
        } else {
            // Too long ?
            if (g_inNextCharIndex >= MAX_SERIAL_MSG_LENGTH) {
                // Force reset all
                ESP_LOGW(TAG_MM, "Serial: msg too long, dropping it");
                resetSerialBuffer();
            } else {
                g_fullMsgFromSerial[g_inNextCharIndex] = g_inChar;
                g_inNextCharIndex++;
            }
        }
    }
#endif


    // Blinking leds management
    for (int pin = 0; pin < LED_QTY; pin++) {
        if (g_ledRequiredState[pin] == LED_STATE_BLINK_FAST) {
            if (currentMillis - g_ledBlinkLastTimestampMs[pin] > LED_BLINK_FAST_DURATION_MS) {
                ledCommuteBlinkState(pin);
            }
        } else if (g_ledRequiredState[pin] == LED_STATE_BLINK_SLOW) {
            if (currentMillis - g_ledBlinkLastTimestampMs[pin] > LED_BLINK_SLOW_DURATION_MS) {
                ledCommuteBlinkState(pin);
            }
        }
    }

    // Periodic status bar polling (only in conversation mode). Cheap: redrawStatusBar short-circuits if nothing changed since the last paint.
    // The info screen is NOT polled — it's refreshed via refreshInfoScreenIfShown() called from the state-change hooks (wifiTransitionTo,
    // mqttReconnectAttempt, BLE connect callback, setupNTP). Avoids the double-render race that the old 2 s timer caused after /status.
    if (g_inConversationMode) {
        if (currentMillis - g_lastStatusBarPollMs >= STATUS_BAR_POLL_INTERVAL_MS) {
            g_lastStatusBarPollMs = currentMillis;
            redrawStatusBar();
        }
    }

    // Auto-revert from the "/status" info-screen overlay back to the nominal 3-zone view after STATUS_SCREEN_DURATION_MS. Non-blocking so MQTT
    // and BLE keep running during the overlay; the same returnToNominalScreen() path is used by "/dbg redraw" for consistency.
    if (g_statusScreenEndMs != 0 && currentMillis >= g_statusScreenEndMs) {
        returnToConversationsScreen();
    }

    // Burn-in protection: advance the dim → off state machine based on idle time.
    updateDisplayPowerState();

    g_firstLoop = false;

    // Short cooperative yield. delay(5) on ESP cores calls yield()/vTaskDelay()
    // internally, which lets the lwIP / BLE / Wi-Fi background tasks run and
    // feeds the watchdog. We keep some delay (rather than 0) so a tight loop
    // does not starve those background tasks on single-core paths or hog the CPU
    // for nothing — but we don't want it large because BLE scan, keystroke
    // dispatch, MQTT keepalive and the LED blink tick all live in this loop and
    // each extra millisecond shows up directly as input lag.
    delay(5);
}
